// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xB396243E, "LineupOverrideCharacter")]
    public class LineupOverrideCharacter : STUInstance {
        [STUField(0x7DD89F4F, "m_entityDef")]
        public teStructuredDataAssetRef<ulong> m_entityDef;

        [STUField(0xEF19F506, "m_poseUnlock")]
        public teStructuredDataAssetRef<STUUnlock> m_poseUnlock;

        [STUField(0xC0A83121, "m_skin")]
        public teStructuredDataAssetRef<ulong> m_skin;
    }
}
