// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x0E4B9278)]
    public class STU_0E4B9278 : STU_79862BCB {
        [STUField(0x23B3F791, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_23B3F791;

        [STUField(0x25E457E0, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_25E457E0;

        [STUField(0x70CCDE78, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_70CCDE78;
    }
}
