// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x588FF314)]
    public class STU_588FF314 : STUConfigVarVecBase {
        [STUField(0x1FDD7084, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_1FDD7084;

        [STUField(0x64E06CA4, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_64E06CA4;

        [STUField(0xA83C2C26, "m_entity", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_entity;

        [STUField(0x2D3CDFA9, "m_hardPoint", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_hardPoint;
    }
}
