// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0x5B028314)]
    public class STU_5B028314 : STUInstance {
        [STUField(0x767792E4)]
        public teUUID m_767792E4;

        [STUField(0xDAF86B4D)]
        public teStructuredDataAssetRef<STU_F3EB00D4> m_DAF86B4D;
    }
}
