// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x7BE698BC)]
    public class STU_7BE698BC : STUConfigVarNumeric {
        [STUField(0x1BB768BC, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_1BB768BC;
    }
}
