// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xCFCE55DC)]
    public class STU_CFCE55DC : STUStatescriptAction {
        [STUField(0xAF774F7D, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_AF774F7D;

        [STUField(0xE3779CD0, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_E3779CD0;

        [STUField(0x8A12D912, "m_target", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_target;
    }
}
