// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xBD2D717B)]
    public class STU_BD2D717B : STU_1361E674 {
        [STUField(0xB257A3A4)]
        public byte m_B257A3A4;
    }
}
