// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xAED5C736)]
    public class STU_AED5C736 : STU_D609A623 {
        [STUField(0x07DD813E, "m_value")]
        public teString m_value;
    }
}
