// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0xC294A43B)]
    public class STU_C294A43B : STU_895A2A7A {
        [STUField(0x2F922165)]
        public STUUnlockRarity m_2F922165;

        [STUField(0x3CC2088A)]
        public teStructuredDataAssetRef<STUHero> m_3CC2088A;

        [STUField(0x48A41554)]
        public byte m_48A41554;

        [STUField(0xD8A49A4D)]
        public int m_D8A49A4D;

        [STUField(0x7AB4E3F8, "m_lootboxType")]
        public Enum_BABC4175 m_lootboxType;
    }
}
