// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x0F310870)]
    public class STU_0F310870 : STU_646C40B7 {
        [STUField(0x619A9D2C)]
        public teString m_619A9D2C;
    }
}
