// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xC537444C)]
    public class STU_C537444C : STU_F7B7BBA0 {
        [STUField(0x2A9D4545, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_2A9D4545;

        [STUField(0x3AF0D54C, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_3AF0D54C;

        [STUField(0x3DD55449, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_3DD55449;

        [STUField(0x99684F0D, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_99684F0D;

        [STUField(0xA289F9A2, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_A289F9A2;

        [STUField(0xB57F3B36, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_B57F3B36;

        [STUField(0xC15762BE, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_C15762BE;

        [STUField(0xE739E94B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_E739E94B;
    }
}
