// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x91B76090)]
    public class STU_91B76090 : STUInstance {
        [STUField(0xCE872E16)]
        public float m_CE872E16;

        [STUField(0x4D2DB658, "m_identifier")]
        public teStructuredDataAssetRef<STUIdentifier> m_identifier;
    }
}
