// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0xA4C8F8DB)]
    public class STU_A4C8F8DB : STUInstance {
        [STUField(0x111738C8)]
        public float m_111738C8;

        [STUField(0x3A3F35A8)]
        public float m_3A3F35A8;

        [STUField(0x4AE1EDFB)]
        public float m_4AE1EDFB;

        [STUField(0xA1C4B45C)]
        public float m_A1C4B45C;

        [STUField(0xA80C59F3)]
        public byte m_A80C59F3;

        [STUField(0xA9EA3C49)]
        public byte m_A9EA3C49;

        [STUField(0xC1D2CB9D)]
        public float m_C1D2CB9D;

        [STUField(0xC3E03C7F, "m_color")]
        public teColorRGB m_color;

        [STUField(0xAF9D3A0C, "m_rotation")]
        public teQuat m_rotation;
    }
}
