// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x441B50E4)]
    public class STU_441B50E4 : STUStatescriptState {
        [STUField(0xD32CB484)]
        public teStructuredDataAssetRef<STUStat>[] m_D32CB484;

        [STUField(0xBC4326FF, "m_stat")]
        public teStructuredDataAssetRef<STUStat> m_stat;

        [STUField(0x118D9D9F, "m_stats")]
        public teStructuredDataAssetRef<STUStat>[] m_stats;

        [STUField(0xE3798C00, "m_targets", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_targets;
    }
}
