// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x13CB18F6)]
    public class STU_13CB18F6 : STU_B9FE55F9 {
        [STUField(0x215BFC34, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_25B808BD m_215BFC34;

        [STUField(0x93951836, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_ABD8FE73 m_93951836;

        [STUField(0x95231A42)]
        public byte m_95231A42;

        [STUField(0xBA891264, "m_dataFlow", ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_25B808BD m_dataFlow;

        [STUField(0xDF9357CF, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_ABD8FE73 m_DF9357CF;
    }
}
