// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xDC85DADE)]
    public class STU_DC85DADE : STUStatescriptState {
        [STUField(0x1338747A, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_1338747A;

        [STUField(0x333215B4, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_333215B4;

        [STUField(0x640D2848, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_640D2848;

        [STUField(0x67BEDFBE, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_67BEDFBE;

        [STUField(0x6A71FC84, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_6A71FC84;

        [STUField(0x7CBA482F, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_7CBA482F;

        [STUField(0x81759372, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_81759372;

        [STUField(0x8CBE558B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_8CBE558B;

        [STUField(0xBAA19EE4, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_BAA19EE4;

        [STUField(0xBE6570AD, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_BE6570AD;

        [STUField(0xA83C2C26, "m_entity", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_entity;
    }
}
