// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x0993C1FE)]
    public class STU_0993C1FE : STUComponentInstanceData {
        [STUField(0x1E03C2AE, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_0D7D53B3 m_1E03C2AE;
    }
}
