// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xA9F42153)]
    public class STU_A9F42153 : STU_851FBF1A {
        [STUField(0x3CD6DC1E, "m_texture")]
        public teStructuredDataAssetRef<STUTexture> m_texture;
    }
}
