// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x0D420A7C)]
    public class STU_0D420A7C : STU_837D6183 {
        [STUField(0xC0A83121, "m_skin")]
        public teStructuredDataAssetRef<STUSkin> m_skin;
    }
}
