// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x431E6901)]
    public class STU_431E6901 : STUStatescriptState {
        [STUField(0x357C2964, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_357C2964;

        [STUField(0x5BB38E35, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_5BB38E35;

        [STUField(0x7031B953, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_7031B953;
    }
}
