// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x5E4187C5)]
    public class STU_5E4187C5 : STUStatescriptScreenVM {
        [STUField(0x633851B6)]
        public ulong m_633851B6;

        [STUField(0x3F39322E, "m_isSelected")]
        public byte m_isSelected;

        [STUField(0xC08C4427, "m_name")]
        public teString m_name;
    }
}
