// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x75BB75C8)]
    public class STU_75BB75C8 : STU_64C11507 {
        [STUField(0xB9114C96, "m_default", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUUXObject m_default;

        [STUField(0x77B7FF8C, "m_entries", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_90B26AC5[] m_entries;
    }
}
