// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xA5EBDE9E)]
    public class STU_A5EBDE9E : STUStatescriptState {
        [STUField(0x0687866A, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_0687866A;

        [STUField(0x297E0B63, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_297E0B63;

        [STUField(0x73F1803C, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_73F1803C;

        [STUField(0x8C8C5285, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_8C8C5285;

        [STUField(0xA41A5134)]
        public teStructuredDataAssetRef<STUVoiceLine> m_A41A5134;

        [STUField(0xE0E02BD4, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_E0E02BD4;

        [STUField(0xE38A0060)]
        public teStructuredDataAssetRef<STUVoiceLineSet> m_E38A0060;

        [STUField(0xA0B58111, "m_onFinishedPlug", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_onFinishedPlug;

        [STUField(0xE3798C00, "m_targets", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_targets;
    }
}
