// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x4DB2D6D5)]
    public class STU_4DB2D6D5 : STUInstance {
        [STUField(0x6E6F8BB6, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_646C40B7[] m_6E6F8BB6;

        [STUField(0x6FDC4C29)]
        public byte m_6FDC4C29;

        [STUField(0x845223EE)]
        public long m_845223EE;

        [STUField(0xBC5E91CF, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_9631AFC2[] m_BC5E91CF;

        [STUField(0xF0FCEFBB, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_646C40B7[] m_F0FCEFBB;

        [STUField(0xF98AE7AD, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_9F9A2B5C[] m_F98AE7AD;
    }
}
