// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x018A2E44)]
    public class STU_018A2E44 : STU_B9FE55F9 {
        [STUField(0x34720CA1)]
        public byte m_34720CA1;

        [STUField(0x6983C85E)]
        public byte m_6983C85E;

        [STUField(0x7BCEFF2A)]
        public byte m_7BCEFF2A;

        [STUField(0x96194C8A)]
        public byte m_96194C8A;

        [STUField(0xABF34EEF, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_ABD8FE73 m_ABF34EEF;

        [STUField(0xC73B6DD4)]
        public ushort m_C73B6DD4;

        [STUField(0xBA891264, "m_dataFlow", ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_25B808BD m_dataFlow;

        [STUField(0xDCB88361, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_15EF3A7E m_DCB88361;
    }
}
