// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xEE825B6F)]
    public class STU_EE825B6F : STU_C71ECB5D {
        [STUField(0xF24E4110, "m_slot", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_slot;

        [STUField(0x0619C597, "m_type", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_type;
    }
}
