// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xE3E443AD)]
    public class STU_E3E443AD : STUStatescriptState {
        [STUField(0x14E5554D, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_14E5554D;

        [STUField(0xA54A5780, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_A54A5780;
    }
}
