// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x0349B182)]
    public class STU_0349B182 : STUStatescriptScreenVM {
        [STUField(0x11F768D6)]
        public teStructuredDataAssetRef<ulong> m_11F768D6;

        [STUField(0x3070B691)]
        public teString m_3070B691;

        [STUField(0x92175C11)]
        public teString m_92175C11;

        [STUField(0xF4EF993C)]
        public int m_F4EF993C;

        [STUField(0xF7CB5989)]
        public byte m_F7CB5989;

        [STUField(0x19F57DF6, "m_heroLevel")]
        public int m_heroLevel;

        [STUField(0x4ABFB43F, "m_heroPortrait")]
        public teStructuredDataAssetRef<ulong> m_heroPortrait;
    }
}
