// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x0AB74EE9)]
    public class STU_0AB74EE9 : STUInstance {
        [STUField(0x1EB5B02B)]
        public float[] m_1EB5B02B;

        [STUField(0x4DC48800)]
        public float[] m_4DC48800;
    }
}
