// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0x68A5034A)]
    public class STU_68A5034A : STUShippable {
        [STUField(0x0201671C)]
        public teStructuredDataAssetRef<STU_68A5034A> m_0201671C;

        [STUField(0x0ECC2AB8)]
        public byte m_0ECC2AB8;

        [STUField(0x159D1394)]
        public byte m_159D1394;

        [STUField(0x40F8879E, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_E75FE496[] m_40F8879E;

        [STUField(0x4DA666FF)]
        public Enum_0B764400 m_4DA666FF;

        [STUField(0x690071AC)]
        public teStructuredDataAssetRef<STU_68A5034A>[] m_690071AC;

        [STUField(0x7DB92D38)]
        public int[] m_7DB92D38;

        [STUField(0x7F09E612)]
        public teStructuredDataAssetRef<STU_68A5034A>[] m_7F09E612;

        [STUField(0x82FF1D0F)]
        public ulong m_82FF1D0F;

        [STUField(0x957ADFF3)]
        public ulong m_957ADFF3;

        [STUField(0x9F657FFB)]
        public teStructuredDataAssetRef<STU_68A5034A>[] m_9F657FFB;

        [STUField(0xACEBA02F)]
        public int[] m_ACEBA02F;

        [STUField(0xB4D8D9BB)]
        public byte m_B4D8D9BB;

        [STUField(0xC6B14E42)]
        public Enum_0B764400 m_C6B14E42;

        [STUField(0xCBA4B39F)]
        public teStructuredDataAssetRef<STU_68A5034A>[] m_CBA4B39F;

        [STUField(0xD9D3469B)]
        public byte m_D9D3469B;

        [STUField(0xE4AACE6E)]
        public byte m_E4AACE6E;

        [STUField(0xE7DE6A4B)]
        public teStructuredDataAssetRef<STU_68A5034A>[] m_E7DE6A4B;

        [STUField(0xF5F7640A)]
        public ulong m_F5F7640A;

        [STUField(0xFF565DCF)]
        public byte m_FF565DCF;

        [STUField(0xC0A83121, "m_skin")]
        public teStructuredDataAssetRef<STU_68A5034A> m_skin;
    }
}
