// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xAC5DF7D0)]
    public class STU_AC5DF7D0 : STU_C7C085F6 {
        [STUField(0x144E52FE)]
        public teStructuredDataAssetRef<STUAnimation> m_144E52FE;

        [STUField(0x428FCCDA)]
        public float m_428FCCDA;

        [STUField(0x4D198484)]
        public teStructuredDataAssetRef<STUDataFlow> m_4D198484;

        [STUField(0xB18F0094)]
        public float m_B18F0094;

        [STUField(0xC5E78E65)]
        public float m_C5E78E65;

        [STUField(0xD7F432F4)]
        public teStructuredDataAssetRef<STUAnimation> m_D7F432F4;
    }
}
