// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0x09B5DE67)]
    public class STU_09B5DE67 : STUInstance {
        [STUField(0x8355F260)]
        public float[] m_8355F260;

        [STUField(0xA4AD54FD, "m_colorDelta")]
        public teColorRGB[] m_colorDelta;

        [STUField(0xA8E85C23, "m_colorValues")]
        public teColorRGB[] m_colorValues;

        [STUField(0xEE030099)]
        public float[] m_EE030099;
    }
}
