// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x798B41F4)]
    public class STU_798B41F4 : STU_1C2FB897 {
        [STUField(0x0495F9E1, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_0495F9E1;

        [STUField(0x068B20CE, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_068B20CE;

        [STUField(0x1190FA0E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_1190FA0E;

        [STUField(0x24680BA9, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_24680BA9;

        [STUField(0x4128E7C3, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_4128E7C3;

        [STUField(0x4573AFA0, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_4573AFA0;

        [STUField(0x7F8E47ED, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_7F8E47ED;

        [STUField(0x82B8DE3B, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_D906F79D[] m_82B8DE3B;

        [STUField(0x9B56D892, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_9B56D892;

        [STUField(0xBA4F8248, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_BA4F8248;

        [STUField(0xBB4909D2, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_BB4909D2;

        [STUField(0xBC8CFAF7, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_BC8CFAF7;

        [STUField(0xC2ED064C, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_C2ED064C;

        [STUField(0xCAEC4C29, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_CAEC4C29;

        [STUField(0xDA00FE9C, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_DA00FE9C;

        [STUField(0xE83464F9, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_E83464F9;

        [STUField(0xF9129CF7, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_F9129CF7;
    }
}
