// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x07142C70)]
    public class STU_07142C70 : STUStatescriptScreenVM {
        [STUField(0x1F72D39F)]
        public byte m_1F72D39F;

        [STUField(0x67C1C70F)]
        public teString m_67C1C70F;

        [STUField(0xBFB85D17)]
        public teString m_BFB85D17;

        [STUField(0xF06C6608)]
        public float m_F06C6608;

        [STUField(0xF2B48985)]
        public int m_F2B48985;

        [STUField(0xE75BEDA5, "m_heroGUID")]
        public ulong m_heroGUID;

        [STUField(0x79DCD591, "m_hoverUnlock", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_A0BDC3D3 m_hoverUnlock;

        [STUField(0xCC84D865, "m_index")]
        public int m_index;

        [STUField(0xCAED3A4C, "m_isDuplicate")]
        public byte m_isDuplicate;

        [STUField(0xC08C4427, "m_name")]
        public teString m_name;

        [STUField(0x2A0F81E0, "m_previewUnlock", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_A0BDC3D3 m_previewUnlock;

        [STUField(0xFD53ECB8, "m_rarity")]
        public teStructuredDataAssetRef<STUUXLink> m_rarity;

        [STUField(0x12716D08, "m_type")]
        public teString m_type;

        [STUField(0x32BC347F, "m_unlockGUID")]
        public ulong m_unlockGUID;
    }
}
