// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xDFEC912B)]
    public class STU_DFEC912B : STUGenericSettings_Base {
        [STUField(0x2545CA9D, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_46AB3B40[] m_2545CA9D;
    }
}
