// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x27214F4A)]
    public class STU_27214F4A : STU_81C5DE19 {
        [STUField(0x4BAEFF23, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_A8EFC6F0 m_4BAEFF23;

        [STUField(0x89E1564D, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_A8EFC6F0 m_89E1564D;

        [STUField(0xAA38C74B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_A8EFC6F0 m_AA38C74B;

        [STUField(0xF891229F, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_8CD34A29 m_F891229F;
    }
}
