// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x0D9BE67D)]
    public class STU_0D9BE67D : STUUXViewModel {
        [STUField(0xAA142D9F)]
        public teString m_AA142D9F;

        [STUField(0xC08C4427, "m_name")]
        public teString m_name;
    }
}
