// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xA3EE7E1C)]
    public class STU_A3EE7E1C : STUStatescriptAction {
        [STUField(0x9CB952FC)]
        public byte m_9CB952FC;
    }
}
