// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xBDB250B9)]
    public class STU_BDB250B9 : STUUXObject {
        [STUField(0xABB40962)]
        public float m_ABB40962;

        [STUField(0xDCB339F4)]
        public float m_DCB339F4;

        [STUField(0xBFDEB7F1, "m_height")]
        public float m_height;

        [STUField(0xC0EDFA4B, "m_width")]
        public float m_width;
    }
}
