// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.Math;
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0x17262D9F)]
    public class STU_17262D9F : STU_C80FEB45 {
        [STUField(0x03D3F311)]
        public float m_03D3F311;

        [STUField(0x0403A33B)]
        public teStructuredDataAssetRef<STUTexture> m_0403A33B;

        [STUField(0x05E76907)]
        public teStructuredDataAssetRef<STUTexture> m_05E76907;

        [STUField(0x0992718A)]
        public Enum_1570A530 m_0992718A;

        [STUField(0x0A2D37DB)]
        public float m_0A2D37DB;

        [STUField(0x0D106FAE)]
        public teStructuredDataAssetRef<STUTexture> m_0D106FAE;

        [STUField(0x125251CF)]
        public Enum_1570A530 m_125251CF;

        [STUField(0x2A8AC2DE)]
        public float m_2A8AC2DE;

        [STUField(0x320EB966)]
        public teStructuredDataAssetRef<STUTexture> m_320EB966;

        [STUField(0x36517B3B)]
        public float m_36517B3B;

        [STUField(0x39CA1A20)]
        public teVec2 m_39CA1A20;

        [STUField(0x3C6E9515)]
        public teStructuredDataAssetRef<STUTexture> m_3C6E9515;

        [STUField(0x5CFD8E44)]
        public float m_5CFD8E44;

        [STUField(0x5F6CBA73)]
        public Enum_1570A530 m_5F6CBA73;

        [STUField(0x5FACFC68)]
        public Enum_1570A530 m_5FACFC68;

        [STUField(0x60C7A1E1)]
        public teStructuredDataAssetRef<STUTexture> m_60C7A1E1;

        [STUField(0x6FA6AE0D)]
        public teStructuredDataAssetRef<STUTexture> m_6FA6AE0D;

        [STUField(0x7360ADDD)]
        public Enum_1570A530 m_7360ADDD;

        [STUField(0x7E62BAD4)]
        public teStructuredDataAssetRef<STUTexture> m_7E62BAD4;

        [STUField(0x81CBCB37)]
        public teStructuredDataAssetRef<STUTexture> m_81CBCB37;

        [STUField(0x88288958)]
        public float m_88288958;

        [STUField(0x8BD52D53)]
        public float m_8BD52D53;

        [STUField(0xB85D5504)]
        public Enum_1570A530 m_B85D5504;

        [STUField(0xB99D8B71)]
        public teStructuredDataAssetRef<STUTexture> m_B99D8B71;

        [STUField(0xC25B4E70)]
        public float m_C25B4E70;

        [STUField(0xCB353443)]
        public float m_CB353443;

        [STUField(0xE45C5E73)]
        public teStructuredDataAssetRef<STUTexture> m_E45C5E73;

        [STUField(0xE67B54B9)]
        public teStructuredDataAssetRef<STUTexture> m_E67B54B9;

        [STUField(0xEFCB22D2)]
        public teStructuredDataAssetRef<STUTexture> m_EFCB22D2;

        [STUField(0x7D5499A6, "m_speed")]
        public float m_speed;
    }
}
