// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x66F94CA8)]
    public class STU_66F94CA8 : STUInstance {
        [STUField(0xC0CC557A, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_102C607C[] m_C0CC557A;
    }
}
