// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x882807BA)]
    public class STU_882807BA : STUInstance {
        [STUField(0xC16A0BCD, "m_generatedSkinTheme")]
        public teStructuredDataAssetRef<STUSkinTheme> m_generatedSkinTheme;

        [STUField(0xF0A9405A, "m_sourceTeam")]
        public teStructuredDataAssetRef<STUTeamColor> m_sourceTeam;
    }
}
