// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0xD37B551C)]
    public class STU_D37B551C : STUInstance {
        [STUField(0x27E94AA8)]
        public teVec3 m_27E94AA8;

        [STUField(0xFC770D15)]
        public teVec3 m_FC770D15;
    }
}
