// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x7CB2AE01)]
    public class STU_7CB2AE01 : STUStatescriptState {
        [STUField(0x470CF3A2)]
        public byte m_470CF3A2;

        [STUField(0x585403E2)]
        public byte m_585403E2;

        [STUField(0xC19A378A, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_C19A378A;

        [STUField(0xCD0A781D)]
        public byte m_CD0A781D;

        [STUField(0xFBB66F03)]
        public byte m_FBB66F03;

        [STUField(0xED61D926, "m_radius")]
        public float m_radius;
    }
}
