// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x72D50764)]
    public class STU_72D50764 : STU_94320319 {
        [STUField(0xE1D625B8)]
        public teStructuredDataAssetRef<STU_D1FE3298> m_E1D625B8;
    }
}
