// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0x967857A2)]
    public class STU_967857A2 : STUStatescriptState {
        [STUField(0x9FED0372)]
        public byte m_9FED0372;

        [STUField(0xAD8C28BA, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_AD8C28BA;

        [STUField(0xAF5DEE6F)]
        public Enum_CA13EDF7 m_AF5DEE6F;

        [STUField(0xC3E03C7F, "m_color", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_color;

        [STUField(0xD7ED647E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_D7ED647E;

        [STUField(0xEC21CC0E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_9D1DEAF2 m_EC21CC0E;

        [STUField(0x5DA62D02, "m_onAbortPlug", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_onAbortPlug;

        [STUField(0xA0B58111, "m_onFinishedPlug", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_onFinishedPlug;
    }
}
