// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x61159CDF)]
    public class STU_61159CDF : STUStatescriptStateUXPresenter {
        [STUField(0x27CA758F, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_27CA758F;
    }
}
