// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x8665DCB5)]
    public class STU_8665DCB5 : STUStatescriptStateUXPresenter { }
}
