// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xF190499F)]
    public class STU_F190499F : STU_4321E3AC {
        [STUField(0x39C08664)]
        public float m_39C08664;

        [STUField(0x57FDDE29)]
        public byte m_57FDDE29;

        [STUField(0xB5ED131B)]
        public teStructuredDataAssetRef<STUAnimation> m_B5ED131B;

        [STUField(0xB683930D)]
        public teStructuredDataAssetRef<STUAnimCategory> m_B683930D;
    }
}
