// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x5F887DF9)]
    public class STU_5F887DF9 : STUStatescriptAction {
        [STUField(0x039D6F04)]
        public teStructuredDataAssetRef<STUIdentifier>[] m_039D6F04;

        [STUField(0x12988ACA, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_12988ACA;

        [STUField(0x2D922A09, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_2D922A09;

        [STUField(0x3222698F, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_3222698F;

        [STUField(0x6A3B2047, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_6A3B2047;

        [STUField(0x736EC9C3, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_736EC9C3;

        [STUField(0xCC5A5415, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_CC5A5415;

        [STUField(0xFE6205BA, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_FE6205BA;
    }
}
