// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xBEA1592D)]
    public class STU_BEA1592D : STUStatescriptScreenVM {
        [STUField(0x1D392DFE)]
        public int m_1D392DFE;

        [STUField(0x3070B691)]
        public teString m_3070B691;

        [STUField(0x3A98F0AD)]
        public teString m_3A98F0AD;

        [STUField(0x501441AB)]
        public teString m_501441AB;

        [STUField(0x516F11AD)]
        public teString m_516F11AD;

        [STUField(0xA0D4A4D7)]
        public byte m_A0D4A4D7;

        [STUField(0xAB1A1E44)]
        public int m_AB1A1E44;

        [STUField(0xCEE5A785)]
        public byte m_CEE5A785;

        [STUField(0xD6DF2A59)]
        public teString m_D6DF2A59;
    }
}
