// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x880F03B4)]
    public class STU_880F03B4 : STUStatescriptState {
        [STUField(0xAC2333F7, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_AC2333F7;
    }
}
