// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0xBD5D80FE)]
    public class STU_BD5D80FE : STUConfigVarResource {
        [STUField(0x5DC61E59, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_5DC61E59;

        [STUField(0xE52AB6E7, "m_info")]
        public Enum_04335D3F m_info;
    }
}
