// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xC656F2E8)]
    public class STU_C656F2E8 : STU_62713FF1 {
        [STUField(0x45561961)]
        public float m_45561961;

        [STUField(0x92BDAB20)]
        public float m_92BDAB20;

        [STUField(0xBFDEB7F1, "m_height", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_816E1D84 m_height;
    }
}
