// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x1973FD2E)]
    public class STU_1973FD2E : STUStatescriptState {
        [STUField(0x089F2C38, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_089F2C38;

        [STUField(0x2802FAEA, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_2802FAEA;

        [STUField(0x47A53681, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_47A53681;

        [STUField(0x5139188E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_2BD8A704 m_5139188E;

        [STUField(0x51A48B8D, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_51A48B8D;

        [STUField(0x53644FCE, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_53644FCE;

        [STUField(0x5CDD1D4B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_5CDD1D4B;

        [STUField(0x5F79638E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_5F79638E;

        [STUField(0x65FB873D, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_65FB873D;

        [STUField(0x837322BA, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_837322BA;

        [STUField(0x86F9FDD3, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_86F9FDD3;

        [STUField(0x88B84578, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_88B84578;

        [STUField(0xA149E368, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_A149E368;

        [STUField(0xA9839B78, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_A9839B78;

        [STUField(0xC5B375DE, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_F0A2EB40 m_C5B375DE;

        [STUField(0xC6B15C25, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_C6B15C25;

        [STUField(0xF288EDBA, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_F288EDBA;

        [STUField(0xF71D3445, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_F71D3445;

        [STUField(0x7D5499A6, "m_speed", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_speed;
    }
}
