// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x49BC3C3C)]
    public class STU_49BC3C3C : STUConfigVarStringBase {
        [STUField(0x37AB13D3, "m_hero", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_hero;
    }
}
