// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xE90FB891)]
    public class STU_E90FB891 : STUConfigVarBoolBase {
        [STUField(0xDE0CEEAC, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_DE0CEEAC;

        [STUField(0xA83C2C26, "m_entity", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_entity;
    }
}
