// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x091261D3)]
    public class STU_091261D3 : STUStatescriptAction {
        [STUField(0xB0FFC9B5, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_B0FFC9B5;
    }
}
