// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xBD02E168)]
    public class STU_BD02E168 : STUStatescriptState {
        [STUField(0x5B10D01F, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_904BFCEC m_5B10D01F;
    }
}
