// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0xBE772C9F)]
    public class STU_BE772C9F : STUConfigVarBoolBase {
        [STUField(0x567AEF59)]
        public ulong m_567AEF59;

        [STUField(0xB8603844)]
        public Enum_B89BB376 m_B8603844;

        [STUField(0xEC043EA6, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_EC043EA6;
    }
}
