// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xD3FB30E2)]
    public class STU_D3FB30E2 : STU_00ABC9FF {
        [STUField(0xB48F1D22, "m_name")]
        public teStructuredDataAssetRef<STUIdentifier> m_name;
    }
}
