// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xDA54F8F7)]
    public class STU_DA54F8F7 : STUStatescriptAction {
        [STUField(0x26E3B366, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_26E3B366;

        [STUField(0xAE2D8911, "m_index", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_index;

        [STUField(0x2F709539, "m_key", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_key;

        [STUField(0x07DD813E, "m_value", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_value;
    }
}
