// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x258AA05C)]
    public class STU_258AA05C : STUInstance {
        [STUField(0x03D88051)]
        public uint m_03D88051;

        [STUField(0x05CD9782)]
        public teStructuredDataAssetRef<STUTargetTag> m_05CD9782;

        [STUField(0x5B621D3B)]
        public byte m_5B621D3B;

        [STUField(0xAD0711CA)]
        public teStructuredDataAssetRef<STUIdentifier> m_AD0711CA;
    }
}
