// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x2107AF60)]
    public class STU_2107AF60 : STUStatescriptState {
        [STUField(0x07ABD7B2, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_07ABD7B2;

        [STUField(0x2FFBD269, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_2FFBD269;

        [STUField(0x3D5CAF44, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_3D5CAF44;

        [STUField(0x6A443DF5, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_6A443DF5;

        [STUField(0x765AD4ED, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_765AD4ED;

        [STUField(0x7B36ED50, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_7B36ED50;

        [STUField(0x942D2129, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_942D2129;

        [STUField(0xDBF2C37A, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_DBF2C37A;

        [STUField(0xE165100C, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_E165100C;

        [STUField(0xEB0A4811, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_0D4680D0[] m_EB0A4811;

        [STUField(0xEB691F64, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_EB691F64;

        [STUField(0xA0B58111, "m_onFinishedPlug", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_onFinishedPlug;
    }
}
