// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0x3A858EF7)]
    public class STU_3A858EF7 : STUInstance {
        [STUField(0x147777B3, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_147777B3;

        [STUField(0x1A15C84F, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_1A15C84F;

        [STUField(0x24EAC676, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_24EAC676;

        [STUField(0x2829D9BF, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_2829D9BF;

        [STUField(0x283B8D7D, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_283B8D7D;

        [STUField(0x47999E82, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_47999E82;

        [STUField(0x5A05F629)]
        public Enum_8C556451 m_5A05F629;

        [STUField(0x89D71A4D, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_89D71A4D;

        [STUField(0xBCC78F70, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_BCC78F70;

        [STUField(0xBE271EB6, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_BE271EB6;

        [STUField(0xBF8E828A, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_BF8E828A;

        [STUField(0xC01C5D2E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_C01C5D2E;

        [STUField(0xE02616D1, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_E02616D1;

        [STUField(0xEBCED433, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_EBCED433;

        [STUField(0xF969FA7A, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_F969FA7A;

        [STUField(0xFAEB0057, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_FAEB0057;
    }
}
