// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xC168636D)]
    public class STU_C168636D : STU_1C2FB897 {
        [STUField(0x34A1CCB7, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_34A1CCB7;

        [STUField(0x6716919E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_6716919E;

        [STUField(0x717EAFE7, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_717EAFE7;

        [STUField(0x9F17FE89, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_9F17FE89;
    }
}
