// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xF75654CF)]
    public class STU_F75654CF : STUInstance {
        [STUField(0x254EE325)]
        public float m_254EE325;

        [STUField(0x55407086, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_D37B551C[] m_55407086;

        [STUField(0xAE2D8911, "m_index")]
        public int m_index;
    }
}
