// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0xE25468B3)]
    public class STU_E25468B3 : STU_3660CDED {
        [STUField(0x3FAFF222)]
        public Enum_ADF0A7EE m_3FAFF222;
    }
}
