// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xC7CA6ECD)]
    public class STU_C7CA6ECD : STUStatescriptState {
        [STUField(0x26451BFB, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar[] m_26451BFB;
    }
}
