// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.Math;
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0x3163D47F)]
    public class STU_3163D47F : STU_DBE83CCA {
        [STUField(0x02283711)]
        public teUUID[] m_02283711;

        [STUField(0x1099D61F)]
        public uint[] m_1099D61F;

        [STUField(0x1626B43B)]
        public float[] m_1626B43B;

        [STUField(0x184328A8)]
        public short[] m_184328A8;

        [STUField(0x1881B1DB)]
        public uint m_1881B1DB;

        [STUField(0x1C4B36DD)]
        public DBID[] m_1C4B36DD;

        [STUField(0x1D1FCA2F)]
        public teVec3A m_1D1FCA2F;

        [STUField(0x1FBE60DF)]
        public teVec2[] m_1FBE60DF;

        [STUField(0x246E6DA2)]
        public double m_246E6DA2;

        [STUField(0x24C8A4B9)]
        public int[] m_24C8A4B9;

        [STUField(0x2667E22F)]
        public ulong m_2667E22F;

        [STUField(0x29760985)]
        public Enum_0EF092C3[] m_29760985;

        [STUField(0x4FFDBD80)]
        public ushort[] m_4FFDBD80;

        [STUField(0x556CD3E6)]
        public teVec3 m_556CD3E6;

        [STUField(0x58C99FBE)]
        public uint m_58C99FBE;

        [STUField(0x5E8EA465)]
        public sbyte[] m_5E8EA465;

        [STUField(0x5FA78ECF)]
        public short m_5FA78ECF;

        [STUField(0x6BC3035B)]
        public int m_6BC3035B;

        [STUField(0x6E46E1A8)]
        public byte m_6E46E1A8;

        [STUField(0x732FD253)]
        public teVec4 m_732FD253;

        [STUField(0x7B4B966E)]
        public teVec2 m_7B4B966E;

        [STUField(0x7C90E110)]
        public byte[] m_7C90E110;

        [STUField(0x86BAF313)]
        public double[] m_86BAF313;

        [STUField(0x960175C9)]
        public ushort m_960175C9;

        [STUField(0x96FAD4F3)]
        public teColorRGB[] m_96FAD4F3;

        [STUField(0x9772D373)]
        public ulong[] m_9772D373;

        [STUField(0x991FD92C)]
        public teColorRGB m_991FD92C;

        [STUField(0x9A43332B)]
        public long[] m_9A43332B;

        [STUField(0x9C5D1371)]
        public int[] m_9C5D1371;

        [STUField(0xA01943B8)]
        public teColorRGBA m_A01943B8;

        [STUField(0xA1D5E162)]
        public teColorRGBA[] m_A1D5E162;

        [STUField(0xAB9BF1E8)]
        public teMtx43A m_AB9BF1E8;

        [STUField(0xB48594E2)]
        public sbyte m_B48594E2;

        [STUField(0xB57A24F3)]
        public teQuat m_B57A24F3;

        [STUField(0xC8071CA4)]
        public byte m_C8071CA4;

        [STUField(0xC9B9BA47)]
        public teString[] m_C9B9BA47;

        [STUField(0xD0171BE8)]
        public teQuat[] m_D0171BE8;

        [STUField(0xD522C4BA)]
        public long m_D522C4BA;

        [STUField(0x802E0900, "m_DBID")]
        public DBID m_DBID;

        [STUField(0xE7D8B682)]
        public teVec4[] m_E7D8B682;

        [STUField(0xEA8E6A19)]
        public byte[] m_EA8E6A19;

        [STUField(0x0D90D271, "m_enum")]
        public Enum_0EF092C3 m_enum;

        [STUField(0xF170BC4D)]
        public float m_F170BC4D;

        [STUField(0xF291BE20)]
        public teVec3[] m_F291BE20;

        [STUField(0xF57D77B2)]
        public teMtx43A[] m_F57D77B2;

        [STUField(0xFE723800)]
        public teVec3A[] m_FE723800;

        [STUField(0x78A08312, "m_string")]
        public teString m_string;

        [STUField(0xF7EF3000, "m_uuid")]
        public teUUID m_uuid;
    }
}
