// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x63ECAC73)]
    public class STU_63ECAC73 : STUUXObject {
        [STUField(0xC3CC205A)]
        public float m_C3CC205A;

        [STUField(0xD5769DCD)]
        public float m_D5769DCD;

        [STUField(0xE4C8DD49)]
        public float m_E4C8DD49;

        [STUField(0xF83DCA70)]
        public float m_F83DCA70;
    }
}
