// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x34B3026E)]
    public class STU_34B3026E : STUStatescriptAction {
        [STUField(0x646B9249, "m_complete")]
        public byte m_complete;
    }
}
