// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xEDFFFDC5)]
    public class STU_EDFFFDC5 : STUUXViewModel {
        [STUField(0xE599058E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_A0BDC3D3 m_E599058E;
    }
}
