// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x00DA94C7)]
    public class STU_00DA94C7 : STU_0D4680D0 {
        [STUField(0x74136F7B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_74136F7B;

        [STUField(0xBB6DED1A, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_BB6DED1A;
    }
}
