// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x6836576E)]
    public class STU_6836576E : STU_C7C085F6 {
        [STUField(0x02400985)]
        public float m_02400985;

        [STUField(0x083715CA)]
        public float m_083715CA;

        [STUField(0x22A075CF)]
        public float m_22A075CF;

        [STUField(0x5DA79F81)]
        public float m_5DA79F81;

        [STUField(0x791E95CB)]
        public float m_791E95CB;

        [STUField(0x83E3F79E)]
        public teStructuredDataAssetRef<STUDataFlow> m_83E3F79E;

        [STUField(0x8D36C2DE)]
        public teStructuredDataAssetRef<STUDataFlow> m_8D36C2DE;

        [STUField(0x9D307F4C)]
        public float m_9D307F4C;

        [STUField(0x9D33F27B)]
        public teStructuredDataAssetRef<STUAnimation> m_9D33F27B;

        [STUField(0xBDCAEED3)]
        public teStructuredDataAssetRef<STUAnimation> m_BDCAEED3;

        [STUField(0xC71F7F06)]
        public float m_C71F7F06;

        [STUField(0xD76FADF8)]
        public teStructuredDataAssetRef<STUAnimation> m_D76FADF8;

        [STUField(0xDE9E722B)]
        public teStructuredDataAssetRef<STUAnimation> m_DE9E722B;

        [STUField(0xFF721DCA)]
        public teStructuredDataAssetRef<STUDataFlow> m_FF721DCA;
    }
}
