// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x13CAF4F2)]
    public class STU_13CAF4F2 : STU_C7C085F6 {
        [STUField(0x04EC121C)]
        public float m_04EC121C;

        [STUField(0x1F09B8D5)]
        public teStructuredDataAssetRef<STUAnimation> m_1F09B8D5;

        [STUField(0x55EF1984)]
        public teStructuredDataAssetRef<STUAnimation> m_55EF1984;

        [STUField(0x6FDEF626)]
        public teStructuredDataAssetRef<STUAnimation> m_6FDEF626;

        [STUField(0x7881B69D)]
        public float m_7881B69D;

        [STUField(0xA9330380)]
        public float m_A9330380;

        [STUField(0xC7D173AC)]
        public teStructuredDataAssetRef<STUAnimation> m_C7D173AC;

        [STUField(0xC9AF9A44)]
        public teStructuredDataAssetRef<STUAnimation> m_C9AF9A44;

        [STUField(0xD520EF14)]
        public float m_D520EF14;
    }
}
