// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x94BB09DF)]
    public class STU_94BB09DF : STU_0E7C8C4F {
        [STUField(0x12D79458)]
        public int m_12D79458;

        [STUField(0x2DBF8DD4)]
        public int m_2DBF8DD4;

        [STUField(0x4740B469)]
        public int m_4740B469;

        [STUField(0x8158F2BB)]
        public int m_8158F2BB;

        [STUField(0xA873EA55, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_E3E48766[] m_A873EA55;

        [STUField(0xAA13C837)]
        public uint m_AA13C837;

        [STUField(0xEBA7CB06)]
        public int m_EBA7CB06;
    }
}
