// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xFCDF431D)]
    public class STU_FCDF431D : STU_4C99A608 {
        [STUField(0x12751DF3, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_12751DF3;

        [STUField(0x6A8F542C, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_6A8F542C;
    }
}
