// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xBC4D3063)]
    public class STU_BC4D3063 : STUStatescriptAction {
        [STUField(0x040B9C77, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_040B9C77;

        [STUField(0x9A9E72EC, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_9A9E72EC;
    }
}
