// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x9CD5CCA4)]
    public class STU_9CD5CCA4 : STU_7C27312D {
        [STUField(0xBA10B1B7, "m_defaultValue", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_C0B05866 m_defaultValue;

        [STUField(0x12716D08, "m_type", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_E5F0AC6A m_type;
    }
}
