// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0x51BAFC27)]
    public class STU_51BAFC27 : STUInstance {
        [STUField(0x0B4F4778)]
        public Enum_0FA36D4A m_0B4F4778;

        [STUField(0xE46EB156)]
        public byte m_E46EB156;

        [STUField(0xFB3B13FA)]
        public teStructuredDataAssetRef<STU_3E07AD9D> m_FB3B13FA;

        [STUField(0xC08C4427, "m_name")]
        public teStructuredDataAssetRef<ulong> m_name;
    }
}
