// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xFF175FB5)]
    public class STU_FF175FB5 : STUInstance {
        [STUField(0x06F26E44)]
        public byte m_06F26E44;

        [STUField(0x9B7A63EA)]
        public float m_9B7A63EA;

        [STUField(0x4D2DB658, "m_identifier")]
        public teStructuredDataAssetRef<STUIdentifier> m_identifier;
    }
}
