// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x016A1DF7)]
    public class STU_016A1DF7 : STU_C7C085F6 {
        [STUField(0x172CAE5E)]
        public teStructuredDataAssetRef<STUAnimation> m_172CAE5E;

        [STUField(0x83CE3EB5)]
        public float m_83CE3EB5;

        [STUField(0xABF34EEF)]
        public float m_ABF34EEF;

        [STUField(0xAD7B135E)]
        public float m_AD7B135E;

        [STUField(0xE8502460)]
        public float m_E8502460;

        [STUField(0xF0E4656D, "m_globalLayerMultipliers", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimGlobalLayerMultipliers m_globalLayerMultipliers;

        [STUField(0x5620DA50, "m_globalWeightMultipliers", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimGlobalWeightMultipliers m_globalWeightMultipliers;

        [STUField(0xEC42051A, "m_userWeights", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimUserWeights m_userWeights;
    }
}
