// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0xC6A37088)]
    public class STU_C6A37088 : STUInstance {
        [STUField(0x0A03D48D)]
        public byte m_0A03D48D;

        [STUField(0x0B243D00)]
        public byte m_0B243D00;

        [STUField(0x27643B96)]
        public teStructuredDataAssetRef<STU_4D28219D> m_27643B96;

        [STUField(0x2AF85F8B)]
        public byte m_2AF85F8B;

        [STUField(0x430F4BFC)]
        public byte m_430F4BFC;

        [STUField(0x69300B47, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_314750D1 m_69300B47;

        [STUField(0x77E70F30)]
        public byte m_77E70F30;

        [STUField(0x90D4477E)]
        public float m_90D4477E;

        [STUField(0x996D7449, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_4B6F9A4C m_996D7449;

        [STUField(0xE498DE7C)]
        public byte m_E498DE7C;

        [STUField(0xE8FB938D)]
        public teColorRGBA m_E8FB938D;

        [STUField(0xEA487267)]
        public byte m_EA487267;

        [STUField(0xF28436BD)]
        public byte m_F28436BD;

        [STUField(0xF707EA70)]
        public byte m_F707EA70;

        [STUField(0x939ABB2C, "m_materialData")]
        public teStructuredDataAssetRef<STUMaterialData> m_materialData;

        [STUField(0xD326911E, "m_thumbnailData")]
        public teStructuredDataAssetRef<STUThumbnailData> m_thumbnailData;
    }
}
