// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x3E434BC1)]
    public class STU_3E434BC1 : STU_7AC83411 {
        [STUField(0x5C013C73, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_5C013C73;

        [STUField(0xFAD4CE17, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_0A9228FE[] m_FAD4CE17;
    }
}
