// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x9D828BEC)]
    public class STU_9D828BEC : STUUXObject {
        [STUField(0x5180E750, "m_value")]
        public ulong m_value;
    }
}
