// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x17CDBE5B)]
    public class STU_17CDBE5B : STUStatescriptState {
        [STUField(0x043333B0, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_043333B0;

        [STUField(0xB8D23FFB, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_B8D23FFB;
    }
}
