// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x6E800F7C)]
    public class STU_6E800F7C : STU_4AA38EA8 {
        [STUField(0x1F791515)]
        public teStructuredDataAssetRef<STUTexture> m_1F791515;

        [STUField(0x35123445)]
        public uint m_35123445;

        [STUField(0x369489D8, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUTextureSource m_369489D8;

        [STUField(0x4DA3254A, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUTextureSource m_4DA3254A;

        [STUField(0x5E813688, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUTextureSource m_5E813688;

        [STUField(0x7BE15319, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUTextureSource m_7BE15319;

        [STUField(0x99039FC8, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUTextureSource m_99039FC8;

        [STUField(0xA665A5E4, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUTextureSource m_A665A5E4;

        [STUField(0xA6CD82B5)]
        public uint m_A6CD82B5;

        [STUField(0xC0DD643E)]
        public uint m_C0DD643E;

        [STUField(0xC276CF5C)]
        public teStructuredDataAssetRef<STU_C6A37088> m_C276CF5C;

        [STUField(0xF1803014)]
        public uint m_F1803014;

        [STUField(0xF0A9405A, "m_sourceTeam")]
        public teStructuredDataAssetRef<STUTeamColor> m_sourceTeam;
    }
}
