// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x43994F1B)]
    public class STU_43994F1B : STUStatescriptState {
        [STUField(0x4A5CA514, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_4A5CA514;

        [STUField(0x0A84537A, "m_contactSet")]
        public teStructuredDataAssetRef<STUContactSet> m_contactSet;
    }
}
