// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x22B0FDB1)]
    public class STU_22B0FDB1 : STUInstance {
        [STUField(0x801BC827, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_95ECA8A6 m_801BC827;

        [STUField(0xB48F1D22, "m_name")]
        public teString m_name;
    }
}
