// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0x15A11424)]
    public class STU_15A11424 : STUInstance {
        [STUField(0x4916E2D4)]
        public byte m_4916E2D4;

        [STUField(0x55033E26)]
        public teVec3 m_55033E26;

        [STUField(0xAA2E694E)]
        public teStructuredDataAssetRef<STUIdentifier> m_AA2E694E;
    }
}
