// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x42A32CEC)]
    public class STU_42A32CEC : STU_62713FF1 {
        [STUField(0x477E0955)]
        public float m_477E0955;

        [STUField(0xA11EA6B4)]
        public float m_A11EA6B4;

        [STUField(0xC0EDFA4B, "m_width", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_816E1D84 m_width;
    }
}
