// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x4831B16F)]
    public class STU_4831B16F : STU_27C6AA11 {
        [STUField(0x07DD813E, "m_value")]
        public teStructuredDataAssetRef<STUAnimCategory> m_value;
    }
}
