// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xFA4520EC)]
    public class STU_FA4520EC : STUStatescriptState {
        [STUField(0x1FE502D7, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_1FE502D7;

        [STUField(0xF8136C96, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_F8136C96;

        [STUField(0xF869F71E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_F869F71E;
    }
}
