// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xA3B38D9A)]
    public class STU_A3B38D9A : STU_05BDD390 {
        [STUField(0xF0A9405A, "m_sourceTeam")]
        public teStructuredDataAssetRef<STUTeamColor> m_sourceTeam;
    }
}
