// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x03780860)]
    public class STU_03780860 : STUConfigVarNumeric {
        [STUField(0x5427168E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_5427168E;

        [STUField(0x669742DF, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_669742DF;
    }
}
