// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0xC35B2B28)]
    public class STU_C35B2B28 : STUStatescriptAction {
        [STUField(0x55B648AA)]
        public Enum_A4A681B1 m_55B648AA;

        [STUField(0xCA7E6EDC, "m_description", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_description;

        [STUField(0xB48F1D22, "m_name", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_name;
    }
}
