// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0xFC2C8334)]
    public class STU_FC2C8334 : STUInstance {
        [STUField(0x7AF85EA9)]
        public Enum_A918B83A m_7AF85EA9;

        [STUField(0xA34366F8)]
        public teStructuredDataAssetRef<STU_A0CFB0F7> m_A34366F8;

        [STUField(0x58D56DD4, "m_effect", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_effect;
    }
}
