// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xD98AE419)]
    public class STU_D98AE419 : STUInstance {
        [STUField(0x64F87F5E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_64F87F5E;

        [STUField(0xB48F1D22, "m_name")]
        public teStructuredDataAssetRef<STUIdentifier> m_name;
    }
}
