// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xEB9564E1)]
    public class STU_EB9564E1 : STUMirroredEntityComponent {
        [STUField(0x95010BBC)]
        public byte m_95010BBC;
    }
}
