// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xA6B80C63)]
    public class STU_A6B80C63 : STUConfigVar {
        [STUField(0x418D9D9D, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_418D9D9D;

        [STUField(0x8054375D, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_8054375D;

        [STUField(0x814F8EC3, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_814F8EC3;

        [STUField(0xC239F989, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_C239F989;
    }
}
