// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x72849AE5)]
    public class STU_72849AE5 : STUStatescriptState {
        [STUField(0x24AB04BB)]
        public byte m_24AB04BB;

        [STUField(0x89402D74, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUStatescriptSubScriptInitData[] m_89402D74;

        [STUField(0xD02E43DC)]
        public byte m_D02E43DC;

        [STUField(0x5DA62D02, "m_onAbortPlug", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_onAbortPlug;

        [STUField(0xA0B58111, "m_onFinishedPlug", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_onFinishedPlug;
    }
}
