// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0xBAB1FAAF)]
    public class STU_BAB1FAAF : STUConfigVarIntBase {
        [STUField(0x503D6044)]
        public Enum_78DABD78 m_503D6044;
    }
}
