// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x4A4BEDAA)]
    public class STU_4A4BEDAA : STUStatescriptAction {
        [STUField(0x32958E47, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_32958E47;

        [STUField(0xAEE4E389, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_AEE4E389;

        [STUField(0xE3798C00, "m_targets", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_targets;
    }
}
