// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x6EDA44A7)]
    public class STU_6EDA44A7 : STUConfigVarNumeric {
        [STUField(0xBD631144, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_BD631144;

        [STUField(0xA83C2C26, "m_entity", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_entity;

        [STUField(0xA16426C6, "m_height", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_height;
    }
}
