// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x0A6BE10E)]
    public class STU_0A6BE10E : STUStatescriptState {
        [STUField(0x17A88AEF, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_17A88AEF;

        [STUField(0x814F8EC3, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_814F8EC3;

        [STUField(0xA70DB860, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_A70DB860;

        [STUField(0xC485751C)]
        public byte m_C485751C;

        [STUField(0xF2805C84, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_F2805C84;

        [STUField(0xF8274C10, "m_filter", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarFilter m_filter;
    }
}
