// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x99EFBC42)]
    public class STU_99EFBC42 : STU_4CD7AF84 {
        [STUField(0x00C4E092, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_00C4E092;

        [STUField(0x0403A33B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_0403A33B;

        [STUField(0x2E05AF4F, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_2E05AF4F;

        [STUField(0x3A205C9C, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_3A205C9C;

        [STUField(0x509903C1, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_509903C1;

        [STUField(0x60C7A1E1, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_60C7A1E1;

        [STUField(0x6FA6AE0D, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_6FA6AE0D;

        [STUField(0xAB865FDF, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_AB865FDF;

        [STUField(0xC3E03C7F, "m_color", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_color;

        [STUField(0xDA1D5BA0, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_DA1D5BA0;
    }
}
