// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x74B41EA0)]
    public class STU_74B41EA0 : STUStatescriptAction {
        [STUField(0x8ABF9743, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_8ABF9743;

        [STUField(0xEDB2BD2A, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_EDB2BD2A;

        [STUField(0xF1AB5AF4, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_F1AB5AF4;

        [STUField(0xF929CB26, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_F929CB26;
    }
}
