// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x2A45E352)]
    public class STU_2A45E352 : STUUXViewModel {
        [STUField(0xDAC93703)]
        public uint m_DAC93703;
    }
}
