// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x704FE611)]
    public class STU_704FE611 : STUInstance {
        [STUField(0xAD37409B)]
        public byte m_AD37409B;
    }
}
