// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x4C96470A)]
    public class STU_4C96470A : STUStatescriptState {
        [STUField(0x00A23E4B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_00A23E4B;

        [STUField(0x1549F0F9, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_1549F0F9;

        [STUField(0x15F880A4, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_15F880A4;

        [STUField(0x1B05EA98, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_1B05EA98;

        [STUField(0x2339572B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_2339572B;

        [STUField(0x2ADABA5F, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_2ADABA5F;

        [STUField(0x2FECD1E3, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_2FECD1E3;

        [STUField(0x30710B76, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_30710B76;

        [STUField(0x33C8E790, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_33C8E790;

        [STUField(0x3656A811, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_3656A811;

        [STUField(0x3E0AE839, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_3E0AE839;

        [STUField(0x425337C6, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_425337C6;

        [STUField(0x60B6AF94, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_60B6AF94;

        [STUField(0x6386E7B4, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_6386E7B4;

        [STUField(0x6647ED22, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_A1AAB8C4 m_6647ED22;

        [STUField(0x6E8CA10B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_6E8CA10B;

        [STUField(0x73D52CDF, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_73D52CDF;

        [STUField(0xB221D18D, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_B221D18D;

        [STUField(0xB3094B0E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_B3094B0E;

        [STUField(0xB42B2BEB, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_B42B2BEB;

        [STUField(0x7404C882, "m_castFilter", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarFilter m_castFilter;

        [STUField(0xDC05B2EE, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_DC05B2EE;

        [STUField(0xE21062B4, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_E21062B4;

        [STUField(0xF6955E81, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_F6955E81;
    }
}
