// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0xF264F092)]
    public class STU_F264F092 : STU_99AE9936 {
        [STUField(0x99008257)]
        public Enum_EBAB7F1B m_99008257;
    }
}
