// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0xAD8319A2)]
    public class STU_AD8319A2 : STUStatescriptAction {
        [STUField(0x310C605F)]
        public Enum_B748E23E m_310C605F;

        [STUField(0xF07A4DC2)]
        public Enum_2225E974 m_F07A4DC2;
    }
}
