// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x2399BBA2)]
    public class STU_2399BBA2 : STUInstance {
        [STUField(0x84E5DE4E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_D4397AB7 m_84E5DE4E;

        [STUField(0x9CDDC24D, "m_weight", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_weight;
    }
}
