// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x25CBEFB0)]
    public class STU_25CBEFB0 : STUStatescriptState {
        [STUField(0x108E51DD)]
        public teStructuredDataHashMap<STUConfigVar> m_108E51DD;
    }
}
