// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x4321E3AC)]
    public class STU_4321E3AC : STU_C7C085F6 {
        [STUField(0x037C2A15)]
        public teStructuredDataAssetRef<STUAnimation> m_037C2A15;

        [STUField(0x11012D0E)]
        public byte m_11012D0E;

        [STUField(0x14E67C73)]
        public float m_14E67C73;

        [STUField(0x2FBD6CBA)]
        public byte m_2FBD6CBA;

        [STUField(0x37EE887D)]
        public byte m_37EE887D;

        [STUField(0x7347115B)]
        public teStructuredDataAssetRef<STUAnimCategory> m_7347115B;

        [STUField(0x9AE71034)]
        public teStructuredDataAssetRef<STUAnimation> m_9AE71034;

        [STUField(0xABF34EEF)]
        public float m_ABF34EEF;

        [STUField(0xD32FA452, "m_categoryDataFlow")]
        public teStructuredDataAssetRef<STUDataFlow> m_categoryDataFlow;

        [STUField(0xD32A2089)]
        public float m_D32A2089;

        [STUField(0xD5EA01B8)]
        public float m_D5EA01B8;

        [STUField(0xE11298F3)]
        public float m_E11298F3;

        [STUField(0xE6952DAC)]
        public byte m_E6952DAC;

        [STUField(0xEC4CAE23)]
        public teStructuredDataAssetRef<STUDataFlow> m_EC4CAE23;

        [STUField(0xF0E4656D, "m_globalLayerMultipliers", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimGlobalLayerMultipliers m_globalLayerMultipliers;

        [STUField(0x5620DA50, "m_globalWeightMultipliers", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimGlobalWeightMultipliers m_globalWeightMultipliers;

        [STUField(0xEC42051A, "m_userWeights", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimUserWeights m_userWeights;
    }
}
