// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x82811BF6)]
    public class STU_82811BF6 : STU_CDA01686 {
        [STUField(0x04501722, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_04501722;

        [STUField(0x2ECA6D29, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_2ECA6D29;

        [STUField(0x431D2B03, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_431D2B03;

        [STUField(0x4CBED882, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_4CBED882;

        [STUField(0x5A252D39, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_5A252D39;

        [STUField(0x90CCEE8B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_90CCEE8B;

        [STUField(0x96ECB1A8, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_96ECB1A8;

        [STUField(0xBDF0A9BC, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_BDF0A9BC;

        [STUField(0xD11E37DB, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_D11E37DB;

        [STUField(0xF48C63FB, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_F48C63FB;

        [STUField(0x37AB13D3, "m_hero", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_hero;

        [STUField(0xF5087894, "m_unlock", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_unlock;
    }
}
