// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x0C963938)]
    public class STU_0C963938 : STUConfigVarEntityID {
        [STUField(0xC19A378A, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_C19A378A;

        [STUField(0xA83C2C26, "m_entity", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_entity;
    }
}
