// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x7CA3B4A0)]
    public class STU_7CA3B4A0 : STU_CCAD18DB {
        [STUField(0x476CCBE6, "m_out_Parameter", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_out_Parameter;
    }
}
