// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xA91790D5)]
    public class STU_A91790D5 : STUConfigVarStringBase {
        [STUField(0xB350E4FD, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_B350E4FD;

        [STUField(0xA83C2C26, "m_entity", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_entity;
    }
}
