// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0xB7DC7A96)]
    public class STU_B7DC7A96 : STU_A3C7077A {
        [STUField(0x09E32A58)]
        public teStructuredDataAssetRef<STUTexture> m_09E32A58;

        [STUField(0x0F10EA0D)]
        public teVec2 m_0F10EA0D;

        [STUField(0x1D220A1D)]
        public float m_1D220A1D;

        [STUField(0x2071DBED)]
        public teStructuredDataAssetRef<STUTexture> m_2071DBED;

        [STUField(0x220E06E7)]
        public teVec2 m_220E06E7;

        [STUField(0x5EEA92CB)]
        public float m_5EEA92CB;

        [STUField(0x61B6514D)]
        public byte m_61B6514D;

        [STUField(0x63E9C1EF)]
        public float m_63E9C1EF;

        [STUField(0x6EE70996)]
        public teStructuredDataAssetRef<STUTexture> m_6EE70996;

        [STUField(0x8B15733F)]
        public teStructuredDataAssetRef<STUTexture> m_8B15733F;

        [STUField(0x97A86B6A)]
        public teVec2 m_97A86B6A;

        [STUField(0xA05C4AB0)]
        public teVec2 m_A05C4AB0;

        [STUField(0xA665A5E4)]
        public teStructuredDataAssetRef<STUTexture> m_A665A5E4;

        [STUField(0xB999DDE2)]
        public teStructuredDataAssetRef<STUEmptyAsset> m_B999DDE2;

        [STUField(0xCDBFC5EC)]
        public teStructuredDataAssetRef<STUTexture> m_CDBFC5EC;

        [STUField(0xD7D21151)]
        public byte m_D7D21151;
    }
}
