// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x473D3BBD)]
    public class STU_473D3BBD : STUStatescriptAction {
        [STUField(0x8B34E9C3, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_8B34E9C3;

        [STUField(0x92A85396, "m_gameMessage", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_gameMessage;

        [STUField(0xBC2A8DA3, "m_params", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_814D595E[] m_params;
    }
}
