// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xCBEC0113)]
    public class STU_CBEC0113 : STUConfigVarBoolBase {
        [STUField(0xFBEBAD6F, "m_endTime")]
        public teStructuredDataDateAndTime m_endTime;

        [STUField(0xF81F4386, "m_startTime")]
        public teStructuredDataDateAndTime m_startTime;
    }
}
