// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x607A6040)]
    public class STU_607A6040 : STU_94CB64FD {
        [STUField(0x0161B83E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_A0BDC3D3 m_0161B83E;

        [STUField(0x6C33250F)]
        public teString m_6C33250F;
    }
}
