// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x98631753)]
    public class STU_98631753 : STU_5D663F1C {
        [STUField(0x01AFADB6)]
        public float m_01AFADB6;

        [STUField(0xEA70ACC2)]
        public float m_EA70ACC2;
    }
}
