// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0x7645DFAE)]
    public class STU_7645DFAE : STUInstance {
        [STUField(0x1EB5B02B)]
        public teVec3A[] m_1EB5B02B;

        [STUField(0x4DC48800)]
        public float[] m_4DC48800;
    }
}
