// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xBD8713E8)]
    public class STU_BD8713E8 : STU_15043B61 {
        [STUField(0x801BC827, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_95ECA8A6 m_801BC827;

        [STUField(0x82165976, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_8823ADCD m_82165976;
    }
}
