// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x3006682C)]
    public class STU_3006682C : STUConfigVar {
        [STUField(0x67465E75, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_67465E75;
    }
}
