// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0x20F25AC6)]
    public class STU_20F25AC6 : STU_A3C7077A {
        [STUField(0x09E32A58)]
        public teStructuredDataAssetRef<STUTexture> m_09E32A58;

        [STUField(0x0A1A2080)]
        public byte m_0A1A2080;

        [STUField(0x2370E609)]
        public teStructuredDataAssetRef<STUTexture> m_2370E609;

        [STUField(0x49F392BD)]
        public float m_49F392BD;

        [STUField(0x9710D80F)]
        public byte m_9710D80F;

        [STUField(0xB999DDE2)]
        public teStructuredDataAssetRef<STUEmptyAsset> m_B999DDE2;

        [STUField(0xBF93327B)]
        public byte m_BF93327B;

        [STUField(0xC9AC8391)]
        public teStructuredDataAssetRef<STUTexture> m_C9AC8391;

        [STUField(0xCC99D954)]
        public Enum_77EE81B2 m_CC99D954;

        [STUField(0xD4C904FE)]
        public uint m_D4C904FE;

        [STUField(0xDB643E43)]
        public teStructuredDataAssetRef<STUDataFlow> m_DB643E43;

        [STUField(0xE1E200DD)]
        public teStructuredDataAssetRef<STUTexture> m_E1E200DD;

        [STUField(0xF129CF0B)]
        public teStructuredDataAssetRef<STUTexture> m_F129CF0B;

        [STUField(0xFDA311DA)]
        public teStructuredDataAssetRef<STUTexture> m_FDA311DA;

        [STUField(0xFF36FFDD)]
        public float m_FF36FFDD;

        [STUField(0xF0A9405A, "m_sourceTeam")]
        public teStructuredDataAssetRef<STUTeamColor> m_sourceTeam;
    }
}
