// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x5B9DCE6E)]
    public class STU_5B9DCE6E : STUConfigVarNumeric {
        [STUField(0x0DC14ABA, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_0DC14ABA;

        [STUField(0xD2582F32, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_D2582F32;
    }
}
