// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xA1FE6B64)]
    public class STU_A1FE6B64 : STU_A3C7077A {
        [STUField(0x071B18CC, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_7B39F7E1 m_071B18CC;

        [STUField(0x0D03FBC8)]
        public byte m_0D03FBC8;

        [STUField(0x8B09679B)]
        public byte m_8B09679B;

        [STUField(0xB999DDE2)]
        public teStructuredDataAssetRef<STUEmptyAsset> m_B999DDE2;

        [STUField(0xDC64DA7B)]
        public byte m_DC64DA7B;
    }
}
