// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xE526E527)]
    public class STU_E526E527 : STUStatescriptStateUXPresenter {
        [STUField(0x5E1E47C5, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_5E1E47C5;

        [STUField(0x70CCDE78, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_70CCDE78;

        [STUField(0xDA239D27, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_DA239D27;

        [STUField(0xE0EAC161, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_E0EAC161;
    }
}
