// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xA2FF486D)]
    public class STU_A2FF486D : STU_C22AE6E9 {
        [STUField(0x9C0FB785, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_38C83B6B[] m_9C0FB785;
    }
}
