// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xA58C1E63)]
    public class STU_A58C1E63 : STUConfigVarBoolBase {
        [STUField(0xAFBBE9C3, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_AFBBE9C3;

        [STUField(0xC62D91EB, "m_source", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_source;

        [STUField(0x8A12D912, "m_target", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_target;
    }
}
