// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x9AB8CF41)]
    public class STU_9AB8CF41 : STUConfigVarIntBase {
        [STUField(0x33B0B2B6, "m_team", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_team;
    }
}
