// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xC4FD6C9D)]
    public class STU_C4FD6C9D : STU_B0C1EEEA {
        [STUField(0x0F63E2E1, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_0F63E2E1;

        [STUField(0x41F8F0F3, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_41F8F0F3;

        [STUField(0xC42F83F7, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_C42F83F7;

        [STUField(0xDC0C1E22, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_DC0C1E22;
    }
}
