// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x96333BBE)]
    public class STU_96333BBE : STUStatescriptState {
        [STUField(0x0626B955, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_0626B955;

        [STUField(0x17A441C0, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_17A441C0;

        [STUField(0x4086A628, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_4086A628;

        [STUField(0x41CF4BA7, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_41CF4BA7;

        [STUField(0x485109CB, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_485109CB;

        [STUField(0x4A5CA514, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_4A5CA514;

        [STUField(0x721250CB, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_721250CB;

        [STUField(0x9524A8D6, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_9524A8D6;

        [STUField(0xA4F55B82, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_A4F55B82;

        [STUField(0xA7B12CE0, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_A7B12CE0;

        [STUField(0xBF438762, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_BF438762;

        [STUField(0xEE23357E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_EE23357E;

        [STUField(0xF1230A98, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_F1230A98;
    }
}
