// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xC9400896)]
    public class STU_C9400896 : STUUXBehavior {
        [STUField(0x0FE110C8, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUUXPropertyPath[] m_0FE110C8;
    }
}
