// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x6050CBD9)]
    public class STU_6050CBD9 : STU_C7C085F6 {
        [STUField(0x0D2049B9)]
        public float m_0D2049B9;

        [STUField(0x18D076A4)]
        public float m_18D076A4;

        [STUField(0x1F5C172D)]
        public float m_1F5C172D;

        [STUField(0x27D83013)]
        public float m_27D83013;

        [STUField(0x3185BC38)]
        public float m_3185BC38;

        [STUField(0x39236909)]
        public float m_39236909;

        [STUField(0x480C9B44)]
        public float m_480C9B44;

        [STUField(0x589E56FC)]
        public float m_589E56FC;

        [STUField(0x6C7B8B1F)]
        public float m_6C7B8B1F;

        [STUField(0x7D22FF82)]
        public float m_7D22FF82;

        [STUField(0x8669A0A6)]
        public float m_8669A0A6;

        [STUField(0xA09915DA)]
        public teStructuredDataAssetRef<STUAnimation> m_A09915DA;

        [STUField(0xA64706DA)]
        public float m_A64706DA;

        [STUField(0xADFC762A)]
        public teStructuredDataAssetRef<STUAnimation> m_ADFC762A;

        [STUField(0xB4C80CCD)]
        public float m_B4C80CCD;

        [STUField(0xEA073914)]
        public teStructuredDataAssetRef<STUAnimation> m_EA073914;

        [STUField(0xF67CA046)]
        public float m_F67CA046;

        [STUField(0x2B6D89C1, "m_idle")]
        public teStructuredDataAssetRef<STUAnimation> m_idle;

        [STUField(0xBDD95289, "m_movement")]
        public teStructuredDataAssetRef<STUAnimation> m_movement;
    }
}
