// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x3F0712C9)]
    public class STU_3F0712C9 : STU_4B6F9A4C {
        [STUField(0x79FF9EB6, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_AE2F63FC m_79FF9EB6;

        [STUField(0x89F953D0, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_0B5C5FB3 m_89F953D0;

        [STUField(0xD697B92C, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_D11C922F m_D697B92C;

        [STUField(0xE0650E62, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_219E8527 m_E0650E62;
    }
}
