// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x153BE5A3)]
    public class STU_153BE5A3 : STUStatescriptAction {
        [STUField(0x72AAB72F, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_72AAB72F;
    }
}
