// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x38EE1100)]
    public class STU_38EE1100 : STUStatescriptState {
        [STUField(0x67FD6A60)]
        public byte m_67FD6A60;

        [STUField(0x92A85396, "m_gameMessage", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_gameMessage;

        [STUField(0xBC2A8DA3, "m_params", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_814D595E[] m_params;

        [STUField(0xBB16810A, "m_priority", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_priority;

        [STUField(0x8A12D912, "m_target", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_F121C8C5 m_target;
    }
}
