// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x1CF818A8)]
    public class STU_1CF818A8 : STUInstance {
        [STUField(0x149092E0)]
        public teString m_149092E0;

        [STUField(0x1F1A84F9)]
        public teString m_1F1A84F9;

        [STUField(0x2D687D5F)]
        public teString m_2D687D5F;

        [STUField(0x39289C7F)]
        public teString m_39289C7F;

        [STUField(0x630747F0)]
        public teString m_630747F0;

        [STUField(0x950A86E6)]
        public teString m_950A86E6;

        [STUField(0xCB239595)]
        public teString m_CB239595;
    }
}
