// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x83DEC8C7)]
    public class STU_83DEC8C7 : STUComponentInstanceData {
        [STUField(0x8AA6504F)]
        public teString m_8AA6504F;
    }
}
