// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xFA600AED)]
    public class STU_FA600AED : STUConfigVarBoolBase {
        [STUField(0x67465E75, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_67465E75;
    }
}
