// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x4BD39CFD)]
    public class STU_4BD39CFD : STUConfigVar {
        [STUField(0x814F8EC3, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_814F8EC3;

        [STUField(0xAE2D8911, "m_index", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_index;
    }
}
