// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xB580EE38)]
    public class STU_B580EE38 : STU_4CD7AF84 {
        [STUField(0xAB865FDF, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_AB865FDF;

        [STUField(0xBA05C78B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_BA05C78B;

        [STUField(0xC3E03C7F, "m_color", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_color;
    }
}
