// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x98A67886)]
    public class STU_98A67886 : STUUXComponent {
        [STUField(0x0CDFEDC6)]
        public teStructuredDataAssetRef<STU_B77FCA72> m_0CDFEDC6;

        [STUField(0x95DF33CE, "m_screen")]
        public teStructuredDataAssetRef<STU_B77FCA72> m_screen;
    }
}
