// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xCF46F0EB)]
    public class STU_CF46F0EB : STUAnimNode_Strafe {
        [STUField(0x4C2A2F3C, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_15EF3A7E m_4C2A2F3C;
    }
}
