// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xA9D1FAD3)]
    public class STU_A9D1FAD3 : STU_B0C1EEEA {
        [STUField(0x0F63E2E1, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_0F63E2E1;

        [STUField(0xA5A7B92D, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_A5A7B92D;

        [STUField(0xB1B808AE, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_B1B808AE;

        [STUField(0xC42F83F7, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_C42F83F7;

        [STUField(0x9352A840, "m_direction", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_direction;

        [STUField(0xED61D926, "m_radius", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_radius;
    }
}
