// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x807927D8)]
    public class STU_807927D8 : STU_952571B3 {
        [STUField(0x256332DE, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_E6999411 m_256332DE;

        [STUField(0x7A34CE58, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_6C8D2AC1 m_7A34CE58;

        [STUField(0x98526854, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_6C8D2AC1 m_98526854;

        [STUField(0x993544D5, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_E6999411 m_993544D5;

        [STUField(0xA63F7950, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_6C8D2AC1 m_A63F7950;

        [STUField(0xC9C104CD, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_E6999411 m_C9C104CD;
    }
}
