// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.Math;
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0xCF8A9391)]
    public class STU_CF8A9391 : STU_A2B9762B {
        [STUField(0x03AACF5A)]
        public Enum_4CE5B8B8 m_03AACF5A;

        [STUField(0x078BFFD1)]
        public byte m_078BFFD1;

        [STUField(0x193D396F)]
        public byte m_193D396F;

        [STUField(0x29369824)]
        public byte m_29369824;

        [STUField(0x35788CF9)]
        public byte m_35788CF9;

        [STUField(0x35EF9697)]
        public teVec3 m_35EF9697;

        [STUField(0x3D2AD214)]
        public byte m_3D2AD214;

        [STUField(0x6D256428)]
        public byte m_6D256428;

        [STUField(0x887A584E)]
        public teVec3 m_887A584E;

        [STUField(0xB889E02C)]
        public teStructuredDataAssetRef<STUEmptyAsset> m_B889E02C;

        [STUField(0xD7B982CF)]
        public float m_D7B982CF;

        [STUField(0xDC735FC7)]
        public byte m_DC735FC7;

        [STUField(0xEE373D6A)]
        public Enum_FAAD9C08 m_EE373D6A;

        [STUField(0xF8D4FCA9)]
        public teVec3 m_F8D4FCA9;
    }
}
