// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x4FC9D3E1)]
    public class STU_4FC9D3E1 : STUConfigVarNumeric {
        [STUField(0x00903303, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_00903303;
    }
}
