// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xFC802009)]
    public class STU_FC802009 : STUStatescriptState {
        [STUField(0x9CF147D3, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_9CF147D3;
    }
}
