// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x540641B9)]
    public class STU_540641B9 : STUUXObject {
        [STUField(0xDB80F546, "m_propertyKey")]
        public uint m_propertyKey;

        [STUField(0x5180E750, "m_value", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUUXObject m_value;
    }
}
