// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xE4F8F828)]
    public class STU_E4F8F828 : STUInstance {
        [STUField(0x51410E7F, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_1D9C01BD[] m_51410E7F;
    }
}
