// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xB101467F)]
    public class STU_B101467F : STUInstance {
        [STUField(0x6425FFB9, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_6425FFB9;

        [STUField(0xB19BD35D, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_B19BD35D;
    }
}
