// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x13E59842)]
    public class STU_13E59842 : STUInstance {
        [STUField(0x291F2404)]
        public long m_291F2404;

        [STUField(0xC0A83121, "m_skin")]
        public teStructuredDataAssetRef<STUSkin> m_skin;
    }
}
