// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xED6496A4)]
    public class STU_ED6496A4 : STUStatescriptStateUXPresenter {
        [STUField(0x0A7ACC79, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_0A7ACC79;

        [STUField(0x68FE8980, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_68FE8980;

        [STUField(0xA8D226DC, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_A8D226DC;

        [STUField(0xE18AD956, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_E18AD956;

        [STUField(0xF67A953D, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_F67A953D;
    }
}
