// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x4A5C847B)]
    public class STU_4A5C847B : STU_C7C085F6 {
        [STUField(0x1923195B)]
        public byte m_1923195B;

        [STUField(0x1F6BBC4D)]
        public teStructuredDataAssetRef<STUAnimation> m_1F6BBC4D;

        [STUField(0x24CEE3E4)]
        public float m_24CEE3E4;

        [STUField(0x2A399D82)]
        public teStructuredDataAssetRef<STUAnimation> m_2A399D82;

        [STUField(0x3017AE06)]
        public float m_3017AE06;

        [STUField(0x3642D4B4)]
        public teStructuredDataAssetRef<STUAnimation> m_3642D4B4;

        [STUField(0x4AE7328B)]
        public float m_4AE7328B;

        [STUField(0x4CB59845)]
        public float m_4CB59845;

        [STUField(0x602FEBA4)]
        public teStructuredDataAssetRef<STUAnimation> m_602FEBA4;

        [STUField(0x65ECFB36)]
        public teStructuredDataAssetRef<STUAnimation> m_65ECFB36;

        [STUField(0xC8D1E719)]
        public float m_C8D1E719;

        [STUField(0xF1E2351A)]
        public teStructuredDataAssetRef<STUAnimation> m_F1E2351A;
    }
}
