// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x1E356736)]
    public class STU_1E356736 : STU_1C2FB897 {
        [STUField(0x19A8584E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_19A8584E;

        [STUField(0x7690E074, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_7690E074;

        [STUField(0xE16940C4, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUAnimCurve m_E16940C4;
    }
}
