// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xF86BCB47)]
    public class STU_F86BCB47 : STU_66209FFD {
        [STUField(0x18A035CB, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_18A035CB;

        [STUField(0x1E44CC91, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_1E44CC91;

        [STUField(0xD5501B83, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_D5501B83;

        [STUField(0xF3380D02, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_F3380D02;
    }
}
