// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.Math;
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0x5769E0DE)]
    public class STU_5769E0DE : STU_A2B9762B {
        [STUField(0x1F4E10A0)]
        public float m_1F4E10A0;

        [STUField(0x3090CB7A)]
        public float m_3090CB7A;

        [STUField(0x3C0F8ED6)]
        public float m_3C0F8ED6;

        [STUField(0x4495D842)]
        public Enum_D5D0D628 m_4495D842;

        [STUField(0x837B7479)]
        public float m_837B7479;

        [STUField(0x9018260C)]
        public Enum_D5D0D628 m_9018260C;

        [STUField(0x9F1FFC2E)]
        public float m_9F1FFC2E;

        [STUField(0xBD631144)]
        public teVec3 m_BD631144;

        [STUField(0xBDBCBB4F)]
        public float m_BDBCBB4F;

        [STUField(0xD1D68906)]
        public teUUID m_D1D68906;

        [STUField(0xF6B52F70)]
        public float m_F6B52F70;
    }
}
