// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0xEC94D644)]
    public class STU_EC94D644 : STU_3660CDED {
        [STUField(0x3FAFF222)]
        public STURagdollMode m_3FAFF222;
    }
}
