// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x627A461C)]
    public class STU_627A461C : STU_E474EECD {
        [STUField(0x4CD101BC, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_4CD101BC;
    }
}
