// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x478436A8)]
    public class STU_478436A8 : STU_820A411A {
        [STUField(0x277AE3DF, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_5FF2A50C m_277AE3DF;

        [STUField(0xB1367BAA, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_4DDEB70A m_B1367BAA;
    }
}
