// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x3403B7AC)]
    public class STU_3403B7AC : STUComponentInstanceData {
        [STUField(0x02B467C6)]
        public ushort m_02B467C6;

        [STUField(0x20DC598F)]
        public byte m_20DC598F;

        [STUField(0x43505DC5)]
        public ushort m_43505DC5;

        [STUField(0xBD631144)]
        public ushort m_BD631144;

        [STUField(0xEED141D9)]
        public byte m_EED141D9;
    }
}
