// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x08305297)]
    public class STU_08305297 : STU_E4324757 {
        [STUField(0xC21DB248)]
        public teStructuredDataAssetRef<ulong> m_C21DB248;
    }
}
