// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0x213A6F1A)]
    public class STU_213A6F1A : STU_9A40D4BB {
        [STUField(0x2E61937B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_2E61937B;

        [STUField(0x503D6044, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_503D6044;

        [STUField(0x9B0385B4, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_9B0385B4;

        [STUField(0xC3E03C7F, "m_color", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_color;

        [STUField(0x9352A840, "m_direction")]
        public Enum_45F0592D m_direction;

        [STUField(0xE315D30F, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_E315D30F;

        [STUField(0xA16426C6, "m_height", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_height;
    }
}
