// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0x9C74F0E2)]
    public class STU_9C74F0E2 : STU_B024BE51 {
        [STUField(0x9B7A63EA, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_9B7A63EA;

        [STUField(0xCFEC5F76)]
        public Enum_1FF31299 m_CFEC5F76;
    }
}
