// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xC8D87B59)]
    public class STU_C8D87B59 : STUInstance {
        [STUField(0x54B071F1)]
        public teStructuredDataAssetRef<STU_1C5DE3A3> m_54B071F1;

        [STUField(0x825B7399)]
        public teStructuredDataAssetRef<STUIdentifier> m_825B7399;
    }
}
