// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x9D8CEE83)]
    public class STU_9D8CEE83 : STU_B28C2E5E {
        [STUField(0x1A7C3230, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_1A7C3230;

        [STUField(0x699A2E5C, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_699A2E5C;

        [STUField(0x9F5E6583, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_9F5E6583;

        [STUField(0xBD2A95EE, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_BD2A95EE;

        [STUField(0xA16426C6, "m_height", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_height;

        [STUField(0xED61D926, "m_radius", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_radius;
    }
}
