// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x4B7B652C)]
    public class STU_4B7B652C : STU_02816D1C {
        [STUField(0xED61D926, "m_radius", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_radius;
    }
}
