// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xCB6C0ED7)]
    public class STU_CB6C0ED7 : STUStatescriptStateUXPresenter {
        [STUField(0x4777D5EE, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_4777D5EE;

        [STUField(0x83DD0ED5, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_83DD0ED5;

        [STUField(0xA83C2C26, "m_entity", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_entity;
    }
}
