// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0x8302E7AC)]
    public class STU_8302E7AC : STU_9F7A0E66 {
        [STUField(0x444416F6)]
        public Enum_43D38C2E m_444416F6;

        [STUField(0xD62358FA)]
        public float m_D62358FA;

        [STUField(0x7CEA65C7, "m_max")]
        public float m_max;

        [STUField(0x7594F80E, "m_min")]
        public float m_min;
    }
}
