// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xF1306D2B)]
    public class STU_F1306D2B : STUUXObject {
        [STUField(0x5180E750, "m_value")]
        public ulong m_value;
    }
}
