// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x328656A2)]
    public class STU_328656A2 : STUStatescriptDataFlowEntity {
        [STUField(0x609E2FBF, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_609E2FBF;
    }
}
