// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0x4703386B)]
    public class STU_4703386B : STUInstance {
        [STUField(0x3D00FDE1)]
        public teUUID m_3D00FDE1;

        [STUField(0x9B62E942)]
        public teString m_9B62E942;

        [STUField(0xEBD8430D)]
        public teUUID m_EBD8430D;
    }
}
