// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0x3CE2BF32)]
    public class STU_3CE2BF32 : STU_7C27312D {
        [STUField(0x0916AFB9, "m_category")]
        public Enum_4CA0F8E0 m_category;

        [STUField(0xBA10B1B7, "m_defaultValue", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_5DDB411A m_defaultValue;
    }
}
