// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xD0806FE4)]
    public class STU_D0806FE4 : STU_CDA01686 {
        [STUField(0x10E16D9D, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_E39E7C11 m_10E16D9D;

        [STUField(0x170234FA, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_170234FA;

        [STUField(0x18202F65, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_18202F65;

        [STUField(0x1D4855CE, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_1D4855CE;

        [STUField(0x20D95F23, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_20D95F23;

        [STUField(0x2985CB94, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_2985CB94;

        [STUField(0x3950A28B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_3950A28B;

        [STUField(0x3E3E203A, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_3E3E203A;

        [STUField(0x425F054A, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_425F054A;

        [STUField(0x4C7AEA39, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_4C7AEA39;

        [STUField(0x5374BCDF, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_5374BCDF;

        [STUField(0x5C59D732, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_5C59D732;

        [STUField(0x60A60C24, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_60A60C24;

        [STUField(0x6D312579, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_6D312579;

        [STUField(0x6EC3F345, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_6EC3F345;

        [STUField(0x7D4F2FF6, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_7D4F2FF6;

        [STUField(0x81C159F0, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_81C159F0;

        [STUField(0x828BBB5F, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_828BBB5F;

        [STUField(0x8E08CB9F, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_8E08CB9F;

        [STUField(0x8E80A08E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_8E80A08E;

        [STUField(0x944B2182, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_944B2182;

        [STUField(0xA124969D, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_A124969D;

        [STUField(0xAFED9891, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_AFED9891;

        [STUField(0xBD631144, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_BD631144;

        [STUField(0xC5743428, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_C5743428;

        [STUField(0xD0EBC4C3, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_D0EBC4C3;

        [STUField(0xDB7E052F, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_DB7E052F;

        [STUField(0xECA9BAAA, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_ECA9BAAA;

        [STUField(0xF09A6FBE, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_F09A6FBE;

        [STUField(0xF5089FE7, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_F5089FE7;
    }
}
