// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x77627F8B)]
    public class STU_77627F8B : STUStatescriptState {
        [STUField(0x620F883F, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_620F883F;

        [STUField(0x6C703AAF, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_6C703AAF;

        [STUField(0x950E2A8F, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_950E2A8F;

        [STUField(0x9D442A12, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_9D442A12;

        [STUField(0xA373BBA0, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_A373BBA0;

        [STUField(0xBD5D0EA8, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_BD5D0EA8;
    }
}
