// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x498067F9)]
    public class STU_498067F9 : STUStatescriptStateUXPresenter { }
}
