// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x6A6BBB8D)]
    public class STU_6A6BBB8D : STUStatescriptState {
        [STUField(0x4F64C1D3, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_4F64C1D3;
    }
}
