// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x982C1218)]
    public class STU_982C1218 : STUGenericSettings_Base {
        [STUField(0x5E15FBE2)]
        public float m_5E15FBE2;
    }
}
