// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x2685961F)]
    public class STU_2685961F : STUStatescriptState {
        [STUField(0x05706D1C, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_AED8365F[] m_05706D1C;

        [STUField(0xA5EF385D, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_904BFCEC m_A5EF385D;
    }
}
