// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xDB5FDC79)]
    public class STU_DB5FDC79 : STUInstance {
        [STUField(0x0C1511C3, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_0C1511C3;

        [STUField(0x0E10C877, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_0E10C877;

        [STUField(0x3C2D8DCE, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_3C2D8DCE;

        [STUField(0x4ADF90EA, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_4ADF90EA;

        [STUField(0x51DC4874, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_51DC4874;

        [STUField(0x6F8895DC, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_6F8895DC;

        [STUField(0x756187FA, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_756187FA;

        [STUField(0x774BACB7, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_774BACB7;

        [STUField(0x82AE8796, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_82AE8796;

        [STUField(0x9BD8268A, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_9BD8268A;

        [STUField(0xA1F5B528, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_A1F5B528;

        [STUField(0xCACCED35, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_CACCED35;

        [STUField(0xD2C24E10, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_D2C24E10;

        [STUField(0xF8BCDB0D, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_F8BCDB0D;

        [STUField(0xFDDD7CED, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_FDDD7CED;

        [STUField(0xFE864313, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_FE864313;

        [STUField(0x3C5E3E62, "m_spread", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_spread;

        [STUField(0xA39847B8, "m_volley", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptStateWeaponVolley m_volley;
    }
}
