// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x789F95B2)]
    public class STU_789F95B2 : STUEntityComponent {
        [STUField(0xAD6037D8, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_D5E47B7B m_AD6037D8;
    }
}
