// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x70C754CD)]
    public class STU_70C754CD : STUInstance {
        [STUField(0x11EFE48E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_11EFE48E;

        [STUField(0x35961153, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_35961153;

        [STUField(0xBC946B94, "m_castLength", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_castLength;

        [STUField(0xCDEB2148, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_CDEB2148;
    }
}
