// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x4BD859E5)]
    public class STU_4BD859E5 : STUGenericSettings_Base {
        [STUField(0x0AEA1B48)]
        public teStructuredDataAssetRef<ulong> m_0AEA1B48;

        [STUField(0x1D7C8ACE)]
        public float m_1D7C8ACE;

        [STUField(0x43928E80)]
        public teStructuredDataAssetRef<ulong> m_43928E80;

        [STUField(0x453447BF)]
        public teStructuredDataAssetRef<ulong> m_453447BF;

        [STUField(0x4D65010B)]
        public float m_4D65010B;

        [STUField(0x54B68306)]
        public float m_54B68306;

        [STUField(0x63FBB2D3)]
        public teStructuredDataAssetRef<ulong> m_63FBB2D3;

        [STUField(0x81DBAA1A, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_FA600F04 m_81DBAA1A;

        [STUField(0x8AC047FE)]
        public float m_8AC047FE;

        [STUField(0x9AF692CD)]
        public teStructuredDataAssetRef<ulong> m_9AF692CD;

        [STUField(0xA1CE6CE9)]
        public float m_A1CE6CE9;

        [STUField(0xC1926B2B, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_FA600F04 m_C1926B2B;

        [STUField(0xD7AFEDBF)]
        public teStructuredDataAssetRef<ulong> m_D7AFEDBF;

        [STUField(0x28994152, "m_deathEffect")]
        public teStructuredDataAssetRef<ulong> m_deathEffect;

        [STUField(0xE37E88F0)]
        public teStructuredDataAssetRef<ulong> m_E37E88F0;
    }
}
