// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xAB2DFE32)]
    public class STU_AB2DFE32 : STU_81C5DE19 {
        [STUField(0xF891229F, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_50177661 m_F891229F;
    }
}
