// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xA810F649)]
    public class STU_A810F649 : STU_81C5DE19 {
        [STUField(0xF891229F, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_C3D42AEF m_F891229F;
    }
}
