// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x4BBC5D09)]
    public class STU_4BBC5D09 : STUStatescriptState {
        [STUField(0x1FFD7AC0, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_1FFD7AC0;

        [STUField(0x2AFC083F, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_2AFC083F;

        [STUField(0x2C40C158, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_2C40C158;

        [STUField(0x2E7D290A, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_2E7D290A;

        [STUField(0x333987A0, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_333987A0;

        [STUField(0x35F14EF6, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_35F14EF6;

        [STUField(0x3D5CAF44, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_3D5CAF44;

        [STUField(0x58B4C4D7, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_58B4C4D7;

        [STUField(0x5ED803CF, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_5ED803CF;

        [STUField(0x64801077, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_64801077;

        [STUField(0x66B658A5, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarFilter m_66B658A5;

        [STUField(0x6A130855, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_6A130855;

        [STUField(0x6F7A45D9, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarFilter m_6F7A45D9;

        [STUField(0x705D6A01, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_705D6A01;

        [STUField(0x78FE8486, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_78FE8486;

        [STUField(0x794A5BCA, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_794A5BCA;

        [STUField(0x7B36ED50, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_7B36ED50;

        [STUField(0x835453C7, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_835453C7;

        [STUField(0x86CF0002, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_86CF0002;

        [STUField(0x9169D109, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_9169D109;

        [STUField(0x9E1A7C58, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_9E1A7C58;

        [STUField(0xD750D816, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_D750D816;

        [STUField(0xD7A2A03B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_D7A2A03B;

        [STUField(0xEA134F86, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_EA134F86;

        [STUField(0xF0F18008, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_F0F18008;

        [STUField(0xF2F8606D, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_F2F8606D;

        [STUField(0xF745334E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_F745334E;

        [STUField(0x7D5499A6, "m_speed", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_speed;
    }
}
