// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0xDFFDCEA7)]
    public class STU_DFFDCEA7 : STUStatescriptAction {
        [STUField(0x2F8460E7)]
        public byte m_2F8460E7;

        [STUField(0x88B25EAB, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_88B25EAB;

        [STUField(0xDE3C867C)]
        public Enum_4D18469F m_DE3C867C;

        [STUField(0xF4F45E57, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_F4F45E57;
    }
}
