// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x9B04BE2D)]
    public class STU_9B04BE2D : STUConfigVarResource {
        [STUField(0x4E87690F, "m_map", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_map;
    }
}
