// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xE820EDF7)]
    public class STU_E820EDF7 : STUStatescriptState {
        [STUField(0xFFA188A2, "m_values", ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_BFA595CA[] m_values;
    }
}
