// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0xF38E9E14)]
    public class STU_F38E9E14 : STUInstance {
        [STUField(0x428FCA02)]
        public byte m_428FCA02;

        [STUField(0x6D964F32)]
        public float m_6D964F32;

        [STUField(0x9F7EBFB2)]
        public byte m_9F7EBFB2;

        [STUField(0xA1876D37)]
        public uint m_A1876D37;

        [STUField(0xB3DC8B74)]
        public float m_B3DC8B74;

        [STUField(0xD640BE62)]
        public Enum_B65B55BF m_D640BE62;

        [STUField(0xEC5EC03E)]
        public byte m_EC5EC03E;
    }
}
