// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x686D7705)]
    public class STU_686D7705 : STUInstance {
        [STUField(0x13AEA600)]
        public teStructuredDataAssetRef<STU_20AD1072> m_13AEA600;

        [STUField(0x4D6047C9)]
        public teString m_4D6047C9;
    }
}
