// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x72035D44)]
    public class STU_72035D44 : STU_6243C374 {
        [STUField(0x40AF7E2D, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_40AF7E2D;

        [STUField(0xE32DA644, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_E32DA644;

        [STUField(0x8A12D912, "m_target", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_target;
    }
}
