// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xB63ECEB8)]
    public class STU_B63ECEB8 : STUStatescriptState {
        [STUField(0x89C93A57, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_89C93A57;

        [STUField(0xCA7AB946, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_CA7AB946;

        [STUField(0x0A84537A, "m_contactSet", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_contactSet;
    }
}
