// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0xDEBD057B)]
    public class STU_DEBD057B : STUStatescriptState {
        [STUField(0x05706D1C, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_ACACAD83[] m_05706D1C;

        [STUField(0x262AE982, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_262AE982;

        [STUField(0x270252ED, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_270252ED;

        [STUField(0xA5EF385D, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_904BFCEC m_A5EF385D;

        [STUField(0xF0F0720B)]
        public Enum_F94C0730 m_F0F0720B;
    }
}
