// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x8AC6C71B)]
    public class STU_8AC6C71B : STUInstance {
        [STUField(0x1937F099, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_74F359CA m_1937F099;

        [STUField(0x775B9C8F, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_74F359CA m_775B9C8F;

        [STUField(0x97B357C0, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_74F359CA m_97B357C0;

        [STUField(0x9C271D24, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_1CF818A8 m_9C271D24;

        [STUField(0xA3728D36)]
        public teString m_A3728D36;

        [STUField(0xB287258A, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_1CF818A8 m_B287258A;

        [STUField(0xCF699D3C)]
        public teString m_CF699D3C;

        [STUField(0xD31502CD)]
        public teString m_D31502CD;

        [STUField(0xD7034F10, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_74F359CA m_D7034F10;
    }
}
