// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0x65F514A5)]
    public class STU_65F514A5 : STU_0CF6650E {
        [STUField(0x08CACF3A)]
        public Enum_149525F6 m_08CACF3A;

        [STUField(0xA76D02A2)]
        public Enum_F5D8585C m_A76D02A2;
    }
}
