// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x96ABC153)]
    public class STU_96ABC153 : STUInstance {
        [STUField(0x94672A2A)]
        public teStructuredDataAssetRef<STUUXDisplayText> m_94672A2A;
    }
}
