// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xE0383160)]
    public class STU_E0383160 : STU_11E07FD7 {
        [STUField(0x1C20F844, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_5FF2A50C m_1C20F844;

        [STUField(0x605E2DC3, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_D5E7FD6F m_605E2DC3;

        [STUField(0x9FACE666, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_D5E7FD6F m_9FACE666;

        [STUField(0xE962CBDB, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_A7049D3D m_E962CBDB;

        [STUField(0xB141AAE4, "m_entityID", ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_6B62E4AD m_entityID;

        [STUField(0x0619C597, "m_type", ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_EC94D644 m_type;
    }
}
