// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x46A228A9)]
    public class STU_46A228A9 : STU_4B6F9A4C {
        [STUField(0xAB878DD1, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_61DACB9B m_AB878DD1;
    }
}
