// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x3F096936)]
    public class STU_3F096936 : STUInstance {
        [STUField(0xC0F5956D)]
        public ulong m_C0F5956D;

        [STUField(0xD4677044, "m_volumes", ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_E57A15FF[] m_volumes;
    }
}
