// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xBC5E4622)]
    public class STU_BC5E4622 : STUStatescriptAction {
        [STUField(0x339A63DB, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_339A63DB;

        [STUField(0xA53FE9DA, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_A53FE9DA;

        [STUField(0xC78954CB, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_C78954CB;

        [STUField(0xBAA74493, "m_condition", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_condition;

        [STUField(0xD10618D1, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_D10618D1;
    }
}
