// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x82EACB6A)]
    public class STU_82EACB6A : STUConfigVarEntityID {
        [STUField(0xF24E4110, "m_slot", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_slot;

        [STUField(0x33B0B2B6, "m_team", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_team;
    }
}
