// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x81F1E42A)]
    public class STU_81F1E42A : STUGenericSettings_Base {
        [STUField(0xE4B201DA)]
        public teStructuredDataAssetRef<STUIdentifier>[] m_E4B201DA;
    }
}
