// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0xD26198B8)]
    public class STU_D26198B8 : STUInstance {
        [STUField(0x5974D584)]
        public Enum_01818BE0 m_5974D584;

        [STUField(0x64F87F5E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_64F87F5E;

        [STUField(0xB48F1D22, "m_name")]
        public teString m_name;
    }
}
