// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x48F4173B)]
    public class STU_48F4173B : STU_4B6F9A4C {
        [STUField(0xA7AC6320, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_20F25AC6 m_A7AC6320;

        [STUField(0xD697B92C, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_D11C922F m_D697B92C;
    }
}
