// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xB17E88C9)]
    public class STU_B17E88C9 : STU_BBF32277 {
        [STUField(0x03147E84, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_03147E84;

        [STUField(0x4F232A5C, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_4F232A5C;

        [STUField(0x51609D56, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_51609D56;

        [STUField(0x6E627021, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_6E627021;

        [STUField(0xB9F1E9B2, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_B9F1E9B2;

        [STUField(0xC952D107, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_C952D107;
    }
}
