// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0x78199064)]
    public class STU_78199064 : STUEntityComponent {
        [STUField(0x08AF89D3)]
        public float m_08AF89D3;

        [STUField(0x65716F95)]
        public teVec3A m_65716F95;

        [STUField(0x79596175)]
        public float m_79596175;

        [STUField(0x7AF913F7)]
        public float m_7AF913F7;

        [STUField(0x7DBA6AAD)]
        public float m_7DBA6AAD;

        [STUField(0x85655EB1)]
        public float m_85655EB1;

        [STUField(0xDC2C3DA0)]
        public teVec3A m_DC2C3DA0;

        [STUField(0xF2A7B045)]
        public float m_F2A7B045;
    }
}
