// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xB9021111)]
    public class STU_B9021111 : STU_F9E17188 {
        [STUField(0x4A67B083)]
        public teStructuredDataAssetRef<STUHardPoint> m_4A67B083;
    }
}
