// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0x9935FBC8)]
    public class STU_9935FBC8 : STUStatescriptState {
        [STUField(0x4BE66EFF, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_4BE66EFF;

        [STUField(0x83221709, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_83221709;

        [STUField(0x8FA7FF85, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_8FA7FF85;

        [STUField(0x93CDFD2F)]
        public Enum_5933D07B m_93CDFD2F;

        [STUField(0xA53161C8, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_A53161C8;

        [STUField(0xAB37A892, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_AB37A892;

        [STUField(0xC33684DE, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_C33684DE;

        [STUField(0xD6119DFB, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_D6119DFB;
    }
}
