// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xD3733E9D)]
    public class STU_D3733E9D : STUUXObject {
        [STUField(0x55905AEC)]
        public ulong m_55905AEC;
    }
}
