// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0x1BCDDC84)]
    public class STU_1BCDDC84 : STUConfigVarIntBase {
        [STUField(0xA9D270A9)]
        public Enum_5A7EBE59 m_A9D270A9;
    }
}
