// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x59D74473)]
    public class STU_59D74473 : STU_1CB8F4B7 {
        [STUField(0xBAA74493, "m_condition", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_condition;
    }
}
