// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x75978E9E)]
    public class STU_75978E9E : STU_2CE5082B {
        [STUField(0x0278FD93, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_0278FD93;

        [STUField(0x2655052E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_2655052E;

        [STUField(0x45CC4270, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_45CC4270;

        [STUField(0x52B7BFC5, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_52B7BFC5;

        [STUField(0x7099FBF3, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_7099FBF3;

        [STUField(0x72839C47, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_72839C47;
    }
}
