// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0x7772912A)]
    public class STU_7772912A : STUInstance {
        [STUField(0xB861351F)]
        public Enum_1C8CB734[] m_B861351F;
    }
}
