// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x776E5ADD)]
    public class STU_776E5ADD : STU_848957AF {
        [STUField(0x3FE1EA9E, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUGameRulesetSchemaValueEnumChoice[] m_3FE1EA9E;

        [STUField(0x45A7A69C, "m_default")]
        public teStructuredDataAssetRef<STUIdentifier> m_default;
    }
}
