// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xC6AF0B22)]
    public class STU_C6AF0B22 : STUStatescriptAction {
        [STUField(0x2F56439D, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_2F56439D;
    }
}
