// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x8B827C67)]
    public class STU_8B827C67 : STUGenericSettings_Base {
        [STUField(0x79A7CB6C)]
        public float m_79A7CB6C;

        [STUField(0xA19599E8)]
        public float m_A19599E8;
    }
}
