// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0x2BF5F776)]
    public class STU_2BF5F776 : STUStatescriptState {
        [STUField(0x14378952, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_14378952;

        [STUField(0x38A8012D, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_38A8012D;

        [STUField(0x56B8547E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_56B8547E;

        [STUField(0x738091A3, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_738091A3;

        [STUField(0x7606BDD7, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_7606BDD7;

        [STUField(0x9102D364)]
        public Enum_DEB9DF3B m_9102D364;

        [STUField(0x9AC007B3, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_9AC007B3;

        [STUField(0xA7EDFBA5, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_A7EDFBA5;

        [STUField(0xF5972437, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_F5972437;
    }
}
