// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x24117401)]
    public class STU_24117401 : STU_48A39D9B {
        [STUField(0xE1D625B8)]
        public teStructuredDataAssetRef<STUEntityDefinition> m_E1D625B8;
    }
}
