// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xA3DC6A25)]
    public class STU_A3DC6A25 : STUStatescriptState {
        [STUField(0x44E07E6E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_44E07E6E;
    }
}
