// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x51A9D9C7)]
    public class STU_51A9D9C7 : STU_27C6AA11 {
        [STUField(0x07DD813E, "m_value")]
        public teStructuredDataAssetRef<STUAnimSynchGroup> m_value;
    }
}
