// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x1B74ED17)]
    public class STU_1B74ED17 : STU_2CE5082B {
        [STUField(0xC6CDB6AB, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_C6CDB6AB;

        [STUField(0xED61D926, "m_radius", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_radius;
    }
}
