// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xA04C6179)]
    public class STU_A04C6179 : STU_769D90C4 {
        [STUField(0x6E01378E)]
        public teStructuredDataAssetRef<STUMap>[] m_6E01378E;
    }
}
