// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x27958A58)]
    public class STU_27958A58 : STUUXViewModel {
        [STUField(0x0E27C815, "m_description")]
        public teString m_description;

        [STUField(0xA5249DE6, "m_text")]
        public teString m_text;
    }
}
