// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x5BBD2A64)]
    public class STU_5BBD2A64 : STUGenericSettings_Base {
        [STUField(0xF2C4BBBC)]
        public teStructuredDataAssetRef<STUTeamColor>[] m_F2C4BBBC;
    }
}
