// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x43B63AD0)]
    public class STU_43B63AD0 : STUStatescriptAction {
        [STUField(0x788CCD47, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_A8DEEA0F[] m_788CCD47;

        [STUField(0x980D78D3, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_980D78D3;

        [STUField(0x9ACAD20A)]
        public teStructuredDataAssetRef<STUIdentifier> m_9ACAD20A;

        [STUField(0xE3798C00, "m_targets", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_targets;
    }
}
