// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x46AB3B40)]
    public class STU_46AB3B40 : STUInstance {
        [STUField(0x59351F33)]
        public teString m_59351F33;

        [STUField(0xD27AE46D, ReaderType = typeof(InlineInstanceFieldReader))]
        public STULobbyMapCatalogInfo[] m_D27AE46D;
    }
}
