// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x30C89937)]
    public class STU_30C89937 : STUConfigVarStringBase {
        [STUField(0x07DD813E, "m_value")]
        public teString m_value;
    }
}
