// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x41484EE1)]
    public class STU_41484EE1 : STUStatescriptState {
        [STUField(0x0F7C3861, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_0F7C3861;

        [STUField(0x179FED70, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_179FED70;

        [STUField(0x9B77AA38, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_9B77AA38;

        [STUField(0xAB733228, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_AB733228;

        [STUField(0xC721B06C, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_A1AAB8C4 m_C721B06C;

        [STUField(0x7404C882, "m_castFilter", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarFilter m_castFilter;

        [STUField(0x9352A840, "m_direction", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_direction;

        [STUField(0xFE7D7AE1, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_FE7D7AE1;

        [STUField(0x7DC1550F, "m_position", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_position;

        [STUField(0x5DC5168B, "m_width", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_width;
    }
}
