// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x2A662C20)]
    public class STU_2A662C20 : STUInstance {
        [STUField(0x7D66D71F)]
        public teStructuredDataAssetRef<STUIdentifier> m_7D66D71F;

        [STUField(0xD10618D1)]
        public uint m_D10618D1;

        [STUField(0xD7183ECF)]
        public teStructuredDataAssetRef<STUIdentifier> m_D7183ECF;
    }
}
