// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xAA1BBA7B)]
    public class STU_AA1BBA7B : STU_15043B61 {
        [STUField(0x801BC827, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_95ECA8A6 m_801BC827;

        [STUField(0x3CD6DC1E, "m_texture", ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_10F1ED2F m_texture;
    }
}
