// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x1150B023)]
    public class STU_1150B023 : STU_79862BCB {
        [STUField(0x2BE305D3, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_2BE305D3;

        [STUField(0x3ED7D66A, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_3ED7D66A;

        [STUField(0x87275065, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_87275065;

        [STUField(0xAD58BBE1, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_AD58BBE1;

        [STUField(0xE92C3801, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_E92C3801;
    }
}
