// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xA1830C5A)]
    public class STU_A1830C5A : STUStatescriptState {
        [STUField(0x04FCCABA, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_04FCCABA;

        [STUField(0x2714FB8C, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_2714FB8C;

        [STUField(0x6EB0CA55, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_6EB0CA55;

        [STUField(0xD3D559F2, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_D3D559F2;

        [STUField(0xD637A32A, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_D637A32A;

        [STUField(0xE23DC584, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_E23DC584;

        [STUField(0xFBA884F4, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_FBA884F4;
    }
}
