// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x371C8946)]
    public class STU_371C8946 : STU_8C127DE2 {
        [STUField(0x7C9BE696)]
        public byte m_7C9BE696;

        [STUField(0xB4FF0E2F, "m_animAlias", ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_C6AA0CA6 m_animAlias;
    }
}
