// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x160F2578)]
    public class STU_160F2578 : STUStatescriptState {
        [STUField(0x4AEEE6A1, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_4AEEE6A1;

        [STUField(0x8B2A4DF3, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_8B2A4DF3;

        [STUField(0x9C7BD8B8, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_9C7BD8B8;

        [STUField(0xB486603E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_B486603E;

        [STUField(0xF8274C10, "m_filter", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarFilter m_filter;
    }
}
