// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xDE66D3F5)]
    public class STU_DE66D3F5 : STUStatescriptAction {
        [STUField(0x0A915A83, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_0A915A83;

        [STUField(0x26667904, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_26667904;

        [STUField(0x33F52A40, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_33F52A40;

        [STUField(0x3AE9A97D, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_28FD717D[] m_3AE9A97D;

        [STUField(0x407D208A, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_407D208A;

        [STUField(0x5502D358, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_5502D358;

        [STUField(0x59FEECBB, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_66209FFD m_59FEECBB;

        [STUField(0x9E677E71, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_9E677E71;

        [STUField(0xF644FB20, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_F644FB20;
    }
}
