// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xC4D13CFE)]
    public class STU_C4D13CFE : STUInstance {
        [STUField(0x27643B96)]
        public teStructuredDataAssetRef<STU_4D28219D> m_27643B96;
    }
}
