// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xABE9D44B)]
    public class STU_ABE9D44B : STUStatescriptOutputPlug {
        [STUField(0x2F709539, "m_key")]
        public uint m_key;
    }
}
