// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x94E489DB)]
    public class STU_94E489DB : STUConfigVarVecBase {
        [STUField(0x7DC1550F, "m_position", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_position;

        [STUField(0xED61D926, "m_radius", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_radius;
    }
}
