// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0x471F9ACB)]
    public class STU_471F9ACB : STUConfigVarIntBase {
        [STUField(0x95E54D5A)]
        public Enum_B38010C4 m_95E54D5A;
    }
}
