// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xACF3D227)]
    public class STU_ACF3D227 : STUConfigVarVecBase {
        [STUField(0x1F545CD8, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_1F545CD8;

        [STUField(0x66FFBEC9, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_66FFBEC9;
    }
}
