// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xEE25ADA5)]
    public class STU_EE25ADA5 : STUStatescriptState {
        [STUField(0x1511D47B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_1511D47B;

        [STUField(0xE75D02C7, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_E75D02C7;

        [STUField(0xEA1C80FF, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_EA1C80FF;
    }
}
