// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x4D076571)]
    public class STU_4D076571 : STUStatescriptState {
        [STUField(0x90C89D90, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_90C89D90;
    }
}
