// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x78F71BED)]
    public class STU_78F71BED : STUStatescriptState {
        [STUField(0x105EDE0D, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_105EDE0D;
    }
}
