// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xE3C424E1)]
    public class STU_E3C424E1 : STUStatescriptState {
        [STUField(0x14EDC50D, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_14EDC50D;

        [STUField(0x2C629B86)]
        public teStructuredDataAssetRef<STUAnimAlias>[] m_2C629B86;

        [STUField(0x8A043AB4, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_8A043AB4;

        [STUField(0xC0D9CA3F, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_C0D9CA3F;
    }
}
