// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xAC14D6F5)]
    public class STU_AC14D6F5 : STU_851FBF1A {
        [STUField(0xA1C4B45C)]
        public float m_A1C4B45C;

        [STUField(0x3CD6DC1E, "m_texture")]
        public teStructuredDataAssetRef<STUTexture> m_texture;
    }
}
