// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x93241E37)]
    public class STU_93241E37 : STUInstance {
        [STUField(0x08D19750)]
        public teStructuredDataAssetRef<STUUXDisplayText> m_08D19750;

        [STUField(0x38B64266)]
        public teString m_38B64266;

        [STUField(0xB9D14B98)]
        public teStructuredDataAssetRef<STUUXDisplayText> m_B9D14B98;

        [STUField(0x87EACF5F, "m_cardTexture")]
        public teStructuredDataAssetRef<STUTexture> m_cardTexture;

        [STUField(0x2EB919C9, "m_categories")]
        public teStructuredDataAssetRef<STUIdentifier>[] m_categories;

        [STUField(0xE02BEE24, "m_celebration")]
        public teStructuredDataAssetRef<STUCelebration> m_celebration;

        [STUField(0xD15238C3)]
        public teString m_D15238C3;

        [STUField(0xD202A3D3)]
        public int m_D202A3D3;
    }
}
