// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x59F0F9EE)]
    public class STU_59F0F9EE : STUStatescriptAction {
        [STUField(0x028C7C53, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_028C7C53;

        [STUField(0x3890919E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_3890919E;

        [STUField(0x79761FAE, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_79761FAE;
    }
}
