// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0xC76C63AF)]
    public class STU_C76C63AF : STUConfigVarNumeric {
        [STUField(0x380AE59C)]
        public Enum_A7DD6145 m_380AE59C;
    }
}
