// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x99ED4486)]
    public class STU_99ED4486 : STUStatescriptAction {
        [STUField(0xF3733689)]
        public byte m_F3733689;
    }
}
