// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xA31C5C63)]
    public class STU_A31C5C63 : STUAnimNode_Animation {
        [STUField(0x23D9E1A7, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_ABD8FE73 m_23D9E1A7;

        [STUField(0x53047E04, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_15EF3A7E m_53047E04;

        [STUField(0x5E009A60, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_15EF3A7E m_5E009A60;
    }
}
