// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xF3894725)]
    public class STU_F3894725 : STUStatescriptAction {
        [STUField(0x66102571, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_66102571;

        [STUField(0x821F831C, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_821F831C;
    }
}
