// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x21106037)]
    public class STU_21106037 : STU_820A411A {
        [STUField(0x2072CCCF, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_0EC9EF75 m_2072CCCF;

        [STUField(0x8A557E94, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_52E468C4 m_8A557E94;

        [STUField(0xA333D9AA, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_A333D9AA;
    }
}
