// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x7D2C14A7)]
    public class STU_7D2C14A7 : STU_81C5DE19 {
        [STUField(0x37EE887D, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_A8EFC6F0 m_37EE887D;

        [STUField(0xF891229F, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_7D91D593 m_F891229F;
    }
}
