// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xFDAB62D6)]
    public class STU_FDAB62D6 : STUStatescriptStateUXPresenter {
        [STUField(0x3859A6E1, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_3859A6E1;

        [STUField(0x49483C59, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_49483C59;

        [STUField(0x651E5402, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_651E5402;

        [STUField(0x846A927B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_846A927B;

        [STUField(0xDC12B34E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_DC12B34E;

        [STUField(0xF195089C, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_F195089C;

        [STUField(0xF71F492C, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_F71F492C;
    }
}
