// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x7F7055AB)]
    public class STU_7F7055AB : STU_28F49095 {
        [STUField(0x90119470, "m_enum")]
        public teStructuredDataAssetRef<STU_53908303> m_enum;
    }
}
