// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0x4A8CA88B)]
    public class STU_4A8CA88B : STUStatescriptAction {
        [STUField(0x93CDFD2F)]
        public Enum_05A537E0 m_93CDFD2F;

        [STUField(0xA978FD35, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_A978FD35;

        [STUField(0x37AB13D3, "m_hero", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_hero;
    }
}
