// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x7197C080)]
    public class STU_7197C080 : STUConfigVarNumeric {
        [STUField(0x01AFADB6, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_01AFADB6;

        [STUField(0x69A20070, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_69A20070;

        [STUField(0xEA70ACC2, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_EA70ACC2;
    }
}
