// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x247A6120)]
    public class STU_247A6120 : STUUXDependencyObject {
        [STUField(0xD60798A0)]
        public uint m_D60798A0;

        [STUField(0xAD409EB1, "m_isFrozen")]
        public byte m_isFrozen;
    }
}
