// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0x44E2A7A6)]
    public class STU_44E2A7A6 : STUConfigVarVecBase {
        [STUField(0x1985EC1A, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_1985EC1A;

        [STUField(0x568DF30E)]
        public Enum_BC7DAD5B m_568DF30E;

        [STUField(0x7826B991, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_7826B991;
    }
}
