// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x9D3AC7FD)]
    public class STU_9D3AC7FD : STUStatescriptAction {
        [STUField(0x8A67F026, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_8A67F026;

        [STUField(0x8A12D912, "m_target", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_target;
    }
}
