// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xFBFF5DE7)]
    public class STU_FBFF5DE7 : STUStatescriptState {
        [STUField(0x26DA7CF8, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_26DA7CF8;

        [STUField(0x3A5CB679, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_3A5CB679;

        [STUField(0x59FD6833, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_59FD6833;

        [STUField(0x7CBA482F, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_7CBA482F;

        [STUField(0x81759372, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_81759372;

        [STUField(0x87A4D0AD, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_87A4D0AD;

        [STUField(0x8A696888, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_8A696888;

        [STUField(0x9A978490, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_9A978490;

        [STUField(0xB1003775, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_B1003775;

        [STUField(0xB988692B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_B988692B;
    }
}
