// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xFDA0D947)]
    public class STU_FDA0D947 : STUUXResource {
        [STUField(0xB5C0F593, "m_guid")]
        public teStructuredDataAssetRef<STUMovie> m_guid;
    }
}
