// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xD45D5973)]
    public class STU_D45D5973 : STUStatescriptAction {
        [STUField(0x4213FC12, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_4213FC12;

        [STUField(0xAA19697A, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_AA19697A;

        [STUField(0x33B0B2B6, "m_team", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_team;
    }
}
