// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x7E9A32C0)]
    public class STU_7E9A32C0 : STU_BBF32277 {
        [STUField(0x51609D56, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_51609D56;
    }
}
