// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x8839933A)]
    public class STU_8839933A : STUStatescriptState {
        [STUField(0x105EDE0D, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_105EDE0D;

        [STUField(0x2B21B3C4, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_2B21B3C4;

        [STUField(0x59F51ED2, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_59F51ED2;

        [STUField(0xBF15AB94, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_BF15AB94;

        [STUField(0xEB4A4687, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_EB4A4687;
    }
}
