// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xF06E752D)]
    public class STU_F06E752D : STUStatescriptAction {
        [STUField(0x6A928816, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_6A928816;

        [STUField(0xD1216388, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_D1216388;

        [STUField(0xFA349AB6, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_FA349AB6;
    }
}
