// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x7F06FF16)]
    public class STU_7F06FF16 : STUStatescriptState {
        [STUField(0x24A44C4A, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_24A44C4A;

        [STUField(0xF93E4686, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_F93E4686;

        [STUField(0x4E87690F, "m_map", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_map;
    }
}
