// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x1B93D61B)]
    public class STU_1B93D61B : STUStatescriptState {
        [STUField(0x1E8637CF, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_1E8637CF;

        [STUField(0x2068FD7A, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_2068FD7A;

        [STUField(0x2D8ADFF8, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_2D8ADFF8;

        [STUField(0xAC183F7E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_AC183F7E;

        [STUField(0xAF872E86, "m_amount", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_amount;

        [STUField(0xC3E03C7F, "m_color", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_color;

        [STUField(0xEC1A7839, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_EC1A7839;
    }
}
