// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x9910B864)]
    public class STU_9910B864 : STUInstance {
        [STUField(0x6DE8A8A1)]
        public ulong m_6DE8A8A1;

        [STUField(0x07DD813E, "m_value")]
        public ulong m_value;
    }
}
