// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x746F8777)]
    public class STU_746F8777 : STUStatescriptState {
        [STUField(0x2B98273A, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_2B98273A;

        [STUField(0x372DEB22, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_99C76CCD m_372DEB22;

        [STUField(0xAF774F7D, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_AF774F7D;

        [STUField(0xBE0A9CC9, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_BE0A9CC9;

        [STUField(0xE3779CD0, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_E3779CD0;

        [STUField(0x5DA62D02, "m_onAbortPlug", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_onAbortPlug;

        [STUField(0xA0B58111, "m_onFinishedPlug", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_onFinishedPlug;

        [STUField(0x8A12D912, "m_target", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_target;
    }
}
