// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x239267EA)]
    public class STU_239267EA : STUInstance {
        [STUField(0xB6C89A17)]
        public teStructuredDataAssetRef<ulong> m_B6C89A17;

        [STUField(0xC65C41CC)]
        public float m_C65C41CC;

        [STUField(0xCAAF80DF)]
        public teStructuredDataAssetRef<ulong> m_CAAF80DF;
    }
}
