// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xB0B07014)]
    public class STU_B0B07014 : STUStatescriptState {
        [STUField(0x21A537D3)]
        public float m_21A537D3;

        [STUField(0x69DB3949)]
        public float m_69DB3949;
    }
}
