// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xE4C6AAB4)]
    public class STU_E4C6AAB4 : STUConfigVarBoolBase {
        [STUField(0xF3E612FD, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_F3E612FD;
    }
}
