// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xCCE86858)]
    public class STU_CCE86858 : STU_E4324757 {
        [STUField(0x5659BA67)]
        public teStructuredDataAssetRef<STU_73AE9738> m_5659BA67;
    }
}
