// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x836EE22E)]
    public class STU_836EE22E : STUGenericSettings_Base {
        [STUField(0xA4832D1D)]
        public teStructuredDataAssetRef<ulong> m_A4832D1D;

        [STUField(0xD27AE46D, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUCustomGameBrowserMapCatalogInfo[] m_D27AE46D;

        [STUField(0xE349AC2C)]
        public teStructuredDataAssetRef<ulong> m_E349AC2C;
    }
}
