// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x37D754C8)]
    public class STU_37D754C8 : STU_72849AE5 {
        [STUField(0x4C82A775, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_4C82A775;

        [STUField(0x69F4B52C, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_69F4B52C;

        [STUField(0xF09A03B3, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_CD398197[] m_F09A03B3;
    }
}
