// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x5DB5B1C9)]
    public class STU_5DB5B1C9 : STUInstance {
        [STUField(0xB2B29774)]
        public teStructuredDataAssetRef<STUIdentifier>[] m_B2B29774;

        [STUField(0xC71EA6BC, "m_graph", ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_754341EB m_graph;
    }
}
