// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x6D803197)]
    public class STU_6D803197 : STU_C7C085F6 {
        [STUField(0x199254D4, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimConfigAnimation m_199254D4;

        [STUField(0x3C835FD0, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimConfigAnimation m_3C835FD0;

        [STUField(0x4BD83A5E, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimConfigAnimation m_4BD83A5E;

        [STUField(0x4D1F0A0E, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimConfigFidgetAnimation m_4D1F0A0E;

        [STUField(0x5300C6FD, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimConfigAnimation m_5300C6FD;

        [STUField(0x5A7E62FF, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimConfigRandomAnimation m_5A7E62FF;

        [STUField(0x5E17B2D6, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimConfigRandomAnimation m_5E17B2D6;

        [STUField(0x65689268, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimConfigRandomAnimation m_65689268;

        [STUField(0x7C125B29, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimConfigAnimation m_7C125B29;

        [STUField(0x8CB351DA, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimConfigAnimation m_8CB351DA;

        [STUField(0xA812D5B0, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimConfigAnimation m_A812D5B0;

        [STUField(0xC73222F7, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimConfigAnimation m_C73222F7;

        [STUField(0xD002ABE8)]
        public byte m_D002ABE8;

        [STUField(0xDE27FD1B, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimConfigRandomAnimation m_DE27FD1B;

        [STUField(0xEB9E8EFD, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimConfigRandomAnimation m_EB9E8EFD;

        [STUField(0xFD722A22, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimConfigRandomAnimation m_FD722A22;
    }
}
