// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x94DAAA8C)]
    public class STU_94DAAA8C : STUStatescriptState {
        [STUField(0x2B98273A, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_2B98273A;

        [STUField(0xBD2A95EE, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_BD2A95EE;

        [STUField(0x7D5499A6, "m_speed", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_speed;
    }
}
