// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0x488E9788)]
    public class STU_488E9788 : STUConfigVarIntBase {
        [STUField(0xAFC6E9BA)]
        public STUUnlockRarity m_AFC6E9BA;
    }
}
