// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x4392F234)]
    public class STU_4392F234 : STUStatescriptWeaponProjectileMotion {
        [STUField(0x2C219106, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_2C219106;

        [STUField(0xC604E722, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_C604E722;
    }
}
