// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0xADE06EB0)]
    public class STU_ADE06EB0 : STUInstance {
        [STUField(0x550D19E2)]
        public ushort m_550D19E2;

        [STUField(0x8A8C6C4F)]
        public Enum_0FD62339 m_8A8C6C4F;

        [STUField(0x7EEFB57A, "m_flags")]
        public byte m_flags;
    }
}
