// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xB7FF3D49)]
    public class STU_B7FF3D49 : STUInstance {
        [STUField(0x0498B97B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_0498B97B;

        [STUField(0x513ECE33, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_513ECE33;

        [STUField(0x55942CC8, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_55942CC8;

        [STUField(0xCFFA6762, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_CFFA6762;
    }
}
