// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x044B595F)]
    public class STU_044B595F : STU_C55609C4 {
        [STUField(0x048D2BC0, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_A0BDC3D3 m_048D2BC0;

        [STUField(0x1C85978C, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_A0BDC3D3 m_1C85978C;

        [STUField(0x22638E8E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_27958A58[] m_22638E8E;

        [STUField(0x24AAB0EF)]
        public byte m_24AAB0EF;

        [STUField(0x2D2E380B)]
        public teString m_2D2E380B;

        [STUField(0x3156FE00)]
        public byte m_3156FE00;

        [STUField(0x39DC845A, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_A0BDC3D3 m_39DC845A;

        [STUField(0x57361E4A)]
        public byte m_57361E4A;

        [STUField(0x70666FD9)]
        public byte m_70666FD9;

        [STUField(0x7708BD32, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_85F98ECC[] m_7708BD32;

        [STUField(0x770E9B95, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_A0BDC3D3 m_770E9B95;

        [STUField(0xA52C5C97, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_A0BDC3D3 m_A52C5C97;

        [STUField(0xB93CB2D5, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_A0BDC3D3 m_B93CB2D5;

        [STUField(0xC2CEBB43)]
        public byte m_C2CEBB43;

        [STUField(0xE96A7D22, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_A0BDC3D3 m_E96A7D22;

        [STUField(0xEA69C274, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_5C465E6A[] m_EA69C274;

        [STUField(0xF87F87D1, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_A0BDC3D3 m_F87F87D1;

        [STUField(0xFD70BCFB, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_A0BDC3D3 m_FD70BCFB;

        [STUField(0xEF646D9F, "m_state")]
        public teStructuredDataAssetRef<STUUXLink> m_state;

        [STUField(0xA5249DE6, "m_text")]
        public teString m_text;
    }
}
