// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x8BBFCD1E)]
    public class STU_8BBFCD1E : STUInstance {
        [STUField(0x770CFAB9)]
        public teString m_770CFAB9;

        [STUField(0xBA53D5ED, "m_guid")]
        public ulong m_guid;
    }
}
