// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xA2D13916)]
    public class STU_A2D13916 : STUConfigVarEntityID {
        [STUField(0x152B6961, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_152B6961;

        [STUField(0x5912C8DF, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_5912C8DF;
    }
}
