// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x74F359CA)]
    public class STU_74F359CA : STUInstance {
        [STUField(0x0177243B)]
        public teString m_0177243B;

        [STUField(0x053AC3EF)]
        public teString m_053AC3EF;

        [STUField(0x0932ED44)]
        public teString m_0932ED44;

        [STUField(0x20A27023)]
        public teString m_20A27023;

        [STUField(0x3D9CF6A1)]
        public teString m_3D9CF6A1;

        [STUField(0x4D447320)]
        public teString m_4D447320;

        [STUField(0x565ECF6B)]
        public teString m_565ECF6B;

        [STUField(0x57523531)]
        public teString m_57523531;

        [STUField(0x68152D6F)]
        public teString m_68152D6F;

        [STUField(0xC17BC33C)]
        public teString m_C17BC33C;

        [STUField(0xF5FE5F2C)]
        public teString m_F5FE5F2C;

        [STUField(0xFC8ED794)]
        public teString m_FC8ED794;
    }
}
