// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xB27AFEC4)]
    public class STU_B27AFEC4 : STUInstance {
        [STUField(0x0FEFF90F, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimBlendTreeSet_BlendTreeItem m_0FEFF90F;

        [STUField(0x2B2C5C7F, "m_animParamUpdater", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_72C48DD7 m_animParamUpdater;

        [STUField(0xD1467FCA, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUAnimGameData_Base m_D1467FCA;

        [STUField(0xF9CA7995, "m_paramIds")]
        public uint[] m_paramIds;
    }
}
