// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x28FE8FB4)]
    public class STU_28FE8FB4 : STUComponentInstanceData {
        [STUField(0x872AC63A)]
        public byte m_872AC63A;

        [STUField(0x9B2B1EC8, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_5BE35DC7[] m_9B2B1EC8;

        [STUField(0xAA8E1BB0, "m_targetTags")]
        public teStructuredDataAssetRef<STUTargetTag>[] m_targetTags;
    }
}
