// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x302A1299)]
    public class STU_302A1299 : STUInstance {
        [STUField(0x01689346)]
        public teStructuredDataAssetRef<STUIdentifier> m_01689346;

        [STUField(0x177B7D4D, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUStatescriptGraphWithOverrides m_177B7D4D;

        [STUField(0x2DEE07D2, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_3CE15663[] m_2DEE07D2;

        [STUField(0x50AE5CF0)]
        public teStructuredDataAssetRef<STU_6BE90C5C>[] m_50AE5CF0;

        [STUField(0x90F1BF40, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUStatescriptGraphWithOverrides m_90F1BF40;

        [STUField(0xA4977032, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_C8D87B59[] m_A4977032;

        [STUField(0xB9D9D3B2, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUStatescriptGraphWithOverrides m_B9D9D3B2;

        [STUField(0xF50771F7)]
        public teStructuredDataAssetRef<STU_6BE90C5C>[] m_F50771F7;
    }
}
