// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x7E2F2739)]
    public class STU_7E2F2739 : STUInstance {
        [STUField(0x0DE857E0, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_0DE857E0;

        [STUField(0x65367986, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_65367986;

        [STUField(0xA9BE86B3, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_A9BE86B3;

        [STUField(0xE5303522, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_E5303522;
    }
}
