// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0xA0872511)]
    public class STU_A0872511 : STUInstance {
        [STUField(0x0827AB28)]
        public teVec3 m_0827AB28;

        [STUField(0x18789D20)]
        public teVec3 m_18789D20;

        [STUField(0x38F997AB, "m_entityDefinition")]
        public teStructuredDataAssetRef<STUEntityDefinition> m_entityDefinition;

        [STUField(0xFF72C038)]
        public teVec3 m_FF72C038;

        [STUField(0xC68C8155, "m_loadout")]
        public teStructuredDataAssetRef<STULoadout> m_loadout;

        [STUField(0xAF9D3A0C, "m_rotation")]
        public teQuat m_rotation;
    }
}
