// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x70FAC627)]
    public class STU_70FAC627 : STUConfigVarNumeric {
        [STUField(0x50F9BBB1, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_50F9BBB1;

        [STUField(0xD017959E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_D017959E;

        [STUField(0xD9A11169, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_D9A11169;
    }
}
