// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xAC5B11ED)]
    public class STU_AC5B11ED : STUInstance {
        [STUField(0x57237EAB, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_57237EAB;

        [STUField(0xDF486EDF, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_DF486EDF;
    }
}
