// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xF06DB961)]
    public class STU_F06DB961 : STU_4B6F9A4C {
        [STUField(0xA7AC6320, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_E65B16E7 m_A7AC6320;

        [STUField(0xD697B92C, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_D11C922F m_D697B92C;
    }
}
