// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x9700865B)]
    public class STU_9700865B : STUStatescriptStateUXPresenter {
        [STUField(0x4A672FC3, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_4A672FC3;

        [STUField(0xB141AAE4, "m_entityID", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_entityID;
    }
}
