// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x1AC76C29)]
    public class STU_1AC76C29 : STU_C7C085F6 {
        [STUField(0x0CA8433C)]
        public teStructuredDataAssetRef<STUAnimation> m_0CA8433C;

        [STUField(0x1A43F416)]
        public teStructuredDataAssetRef<STUAnimation> m_1A43F416;

        [STUField(0x1F8ADBF4)]
        public teStructuredDataAssetRef<STUAnimation> m_1F8ADBF4;

        [STUField(0x1FB4D322)]
        public teStructuredDataAssetRef<STUDataFlow> m_1FB4D322;

        [STUField(0x242C4500)]
        public float m_242C4500;

        [STUField(0x279D582B)]
        public teStructuredDataAssetRef<STUAnimation> m_279D582B;

        [STUField(0x2C7AE560)]
        public teStructuredDataAssetRef<STUAnimation> m_2C7AE560;

        [STUField(0x303E78E7)]
        public teStructuredDataAssetRef<STUAnimation> m_303E78E7;

        [STUField(0x3A7FDAA4)]
        public teStructuredDataAssetRef<STUAnimation> m_3A7FDAA4;

        [STUField(0x3AC8FFB0)]
        public teStructuredDataAssetRef<STUAnimation> m_3AC8FFB0;

        [STUField(0x42F2F987)]
        public teStructuredDataAssetRef<STUAnimation> m_42F2F987;

        [STUField(0x47DE76FF)]
        public teStructuredDataAssetRef<STUAnimation> m_47DE76FF;

        [STUField(0x5E009A60)]
        public byte m_5E009A60;

        [STUField(0x5E52706D)]
        public teStructuredDataAssetRef<STUAnimation> m_5E52706D;

        [STUField(0x668EC893)]
        public teStructuredDataAssetRef<STUAnimation> m_668EC893;

        [STUField(0x66C14A25)]
        public teStructuredDataAssetRef<STUAnimation> m_66C14A25;

        [STUField(0x71622859)]
        public teStructuredDataAssetRef<STUAnimation> m_71622859;

        [STUField(0x7910195B)]
        public byte m_7910195B;

        [STUField(0x83C3864A)]
        public teStructuredDataAssetRef<STUAnimation> m_83C3864A;

        [STUField(0x83CE3EB5)]
        public float m_83CE3EB5;

        [STUField(0x85A569D5)]
        public teStructuredDataAssetRef<STUAnimation> m_85A569D5;

        [STUField(0x89CD1D1C)]
        public teStructuredDataAssetRef<STUAnimation> m_89CD1D1C;

        [STUField(0x8F2638FC)]
        public teStructuredDataAssetRef<STUAnimation> m_8F2638FC;

        [STUField(0x93AE5E28)]
        public teStructuredDataAssetRef<STUAnimation> m_93AE5E28;

        [STUField(0x93BB2F54)]
        public teStructuredDataAssetRef<STUAnimation> m_93BB2F54;

        [STUField(0x9F61129A)]
        public teStructuredDataAssetRef<STUAnimation> m_9F61129A;

        [STUField(0xA12F5018)]
        public teStructuredDataAssetRef<STUAnimation> m_A12F5018;

        [STUField(0xA1AEF21A)]
        public teStructuredDataAssetRef<STUAnimation> m_A1AEF21A;

        [STUField(0xB01A77DC)]
        public teStructuredDataAssetRef<STUAnimation> m_B01A77DC;

        [STUField(0xB20B8E78)]
        public teStructuredDataAssetRef<STUAnimation> m_B20B8E78;

        [STUField(0xB7CB17AD)]
        public teStructuredDataAssetRef<STUAnimation> m_B7CB17AD;

        [STUField(0xCCF9F1E1)]
        public float m_CCF9F1E1;

        [STUField(0xCD496C03)]
        public teStructuredDataAssetRef<STUAnimation> m_CD496C03;

        [STUField(0xCD8428B3)]
        public teStructuredDataAssetRef<STUAnimation> m_CD8428B3;

        [STUField(0xD59918E7)]
        public teStructuredDataAssetRef<STUAnimation> m_D59918E7;

        [STUField(0xDB28A84C)]
        public float m_DB28A84C;

        [STUField(0xDC664728)]
        public teStructuredDataAssetRef<STUAnimation> m_DC664728;

        [STUField(0xE7F89E9E)]
        public teStructuredDataAssetRef<STUAnimation> m_E7F89E9E;

        [STUField(0xF2B9B93F)]
        public teStructuredDataAssetRef<STUAnimation> m_F2B9B93F;

        [STUField(0xF2FF8F99)]
        public teStructuredDataAssetRef<STUAnimation> m_F2FF8F99;

        [STUField(0xFA6440EE)]
        public teStructuredDataAssetRef<STUAnimation> m_FA6440EE;

        [STUField(0xFBDE5564)]
        public teStructuredDataAssetRef<STUAnimation> m_FBDE5564;

        [STUField(0xFE565B99)]
        public teStructuredDataAssetRef<STUAnimation> m_FE565B99;

        [STUField(0xF0E4656D, "m_globalLayerMultipliers", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimGlobalLayerMultipliers m_globalLayerMultipliers;

        [STUField(0x5620DA50, "m_globalWeightMultipliers", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimGlobalWeightMultipliers m_globalWeightMultipliers;

        [STUField(0xEC42051A, "m_userWeights", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimUserWeights m_userWeights;
    }
}
