// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x7C6FC0A4)]
    public class STU_7C6FC0A4 : STU_81C5DE19 {
        [STUField(0x57A336EE, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_A8EFC6F0 m_57A336EE;

        [STUField(0x45A7A69C, "m_default", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_A8EFC6F0 m_default;

        [STUField(0xF891229F, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_7AD4FB0C m_F891229F;
    }
}
