// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x94CB64FD)]
    public class STU_94CB64FD : STUUXViewModel {
        [STUField(0x42177D53)]
        public float m_42177D53;

        [STUField(0x67C1C70F)]
        public teString m_67C1C70F;

        [STUField(0xEC88B9A1)]
        public uint m_EC88B9A1;
    }
}
