// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x5AFB02C7)]
    public class STU_5AFB02C7 : STUStatescriptState {
        [STUField(0x50D63347, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_50D63347;

        [STUField(0xF3E612FD, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_F3E612FD;
    }
}
