// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x09D37AFA)]
    public class STU_09D37AFA : STUInstance {
        [STUField(0x29EFF18D, "m_crc")]
        public uint m_crc;

        [STUField(0xD229B093)]
        public float[] m_D229B093;
    }
}
