// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xD4A018B8)]
    public class STU_D4A018B8 : STUInstance {
        [STUField(0x19B2212F)]
        public float m_19B2212F;
    }
}
