// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x5171EAA1)]
    public class STU_5171EAA1 : STUConfigVarStringBase {
        [STUField(0x39A13B37, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_39A13B37;

        [STUField(0x8524026D, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_8524026D;
    }
}
