// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x23E1B2C7)]
    public class STU_23E1B2C7 : STU_48A39D9B {
        [STUField(0xE1D625B8)]
        public teStructuredDataAssetRef<STUModel> m_E1D625B8;
    }
}
