// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x5E731805)]
    public class STU_5E731805 : STU_820A411A {
        [STUField(0x3E3DFE0F, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_3E3DFE0F;

        [STUField(0x4A5CA514, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_5FF2A50C m_4A5CA514;

        [STUField(0x8F4413B1, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_5FF2A50C m_8F4413B1;

        [STUField(0xBECCAE26, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_BECCAE26;

        [STUField(0xD80AEDB1, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_D80AEDB1;

        [STUField(0x9352A840, "m_direction", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_direction;

        [STUField(0xF6862FE7, "m_falloff", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_falloff;

        [STUField(0xED61D926, "m_radius", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_radius;
    }
}
