// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0xC5C07DF0)]
    public class STU_C5C07DF0 : STUStatescriptOutputPlug {
        [STUField(0x93CDFD2F)]
        public Enum_3F198330 m_93CDFD2F;

        [STUField(0xA99B047B)]
        public teStructuredDataAssetRef<STUUXLink> m_A99B047B;
    }
}
