// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x68788689)]
    public class STU_68788689 : STUStatescriptStateUXPresenter { }
}
