// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.Math;
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0xAA9D0E8A)]
    public class STU_AA9D0E8A : STUInstance {
        [STUField(0x04EC723F)]
        public float m_04EC723F;

        [STUField(0x07C65134)]
        public float m_07C65134;

        [STUField(0x0DFA88E0)]
        public Enum_827B79B0 m_0DFA88E0;

        [STUField(0x1275414A)]
        public float m_1275414A;

        [STUField(0x1EE9E826)]
        public byte m_1EE9E826;

        [STUField(0x2A15AD7F)]
        public float m_2A15AD7F;

        [STUField(0x32AE2B1F)]
        public float m_32AE2B1F;

        [STUField(0x3637F9F3)]
        public float m_3637F9F3;

        [STUField(0x396B0647)]
        public float m_396B0647;

        [STUField(0x5D916FB1)]
        public teStructuredDataAssetRef<STUIdentifier> m_5D916FB1;

        [STUField(0x6749359B)]
        public float m_6749359B;

        [STUField(0x70BFAAA2)]
        public byte m_70BFAAA2;

        [STUField(0x7F7BA65A)]
        public float m_7F7BA65A;

        [STUField(0x83BE3F26)]
        public float m_83BE3F26;

        [STUField(0x9A9E72EC)]
        public byte m_9A9E72EC;

        [STUField(0x9FEF1BD7)]
        public teColorRGBA m_9FEF1BD7;

        [STUField(0xB26710E9)]
        public byte m_B26710E9;

        [STUField(0xC95565E1)]
        public float m_C95565E1;

        [STUField(0xDB251FDD)]
        public float m_DB251FDD;

        [STUField(0xE6480824)]
        public byte m_E6480824;

        [STUField(0x58D56DD4, "m_effect")]
        public teStructuredDataAssetRef<ulong> m_effect;

        [STUField(0xF71BE1E4)]
        public float m_F71BE1E4;

        [STUField(0x3CD6DC1E, "m_texture")]
        public teStructuredDataAssetRef<ulong> m_texture;
    }
}
