// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x5F87B18C)]
    public class STU_5F87B18C : STUGameModeLegacy {
        [STUField(0x7A6E04C3)]
        public uint m_7A6E04C3;

        [STUField(0x37AB13D3, "m_hero")]
        public teStructuredDataAssetRef<STUHero> m_hero;
    }
}
