// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x317ECFC6)]
    public class STU_317ECFC6 : STUStatescriptAction {
        [STUField(0xA4258A77, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_A4258A77;
    }
}
