// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x9DABFA04)]
    public class STU_9DABFA04 : STUStatescriptState {
        [STUField(0x2325FB32, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_50C22F18 m_2325FB32;

        [STUField(0x76958C1B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_76958C1B;

        [STUField(0x8A5B0245, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_C6544761 m_8A5B0245;
    }
}
