// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xC356E3CD)]
    public class STU_C356E3CD : STUStatescriptState {
        [STUField(0xC17E7CA2, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_C17E7CA2;
    }
}
