// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x2AB3F306)]
    public class STU_2AB3F306 : STUStatescriptAction {
        [STUField(0x0468C6D4, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_0468C6D4;

        [STUField(0xE62F36ED, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_E62F36ED;
    }
}
