// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xF3B98513)]
    public class STU_F3B98513 : STUUXDependencyObject {
        [STUField(0xADE95629, "m_items", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_3BE3CDFF[] m_items;
    }
}
