// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xC521DC6E)]
    public class STU_C521DC6E : STUStatescriptAction {
        [STUField(0xAE2D8911, "m_index", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_index;
    }
}
