// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x4291AE3C)]
    public class STU_4291AE3C : STU_48A39D9B {
        [STUField(0xE1D625B8)]
        public teStructuredDataAssetRef<STU_8EFC337B> m_E1D625B8;
    }
}
