// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0xA0806584)]
    public class STU_A0806584 : STUConfigVarBoolBase {
        [STUField(0x0619C597, "m_type")]
        public Enum_A4A681B1 m_type;
    }
}
