// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xE9234E80)]
    public class STU_E9234E80 : STU_5008135C {
        [STUField(0xA8512EDA, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_A8512EDA;

        [STUField(0xBF846909, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_BF846909;
    }
}
