// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xC57FB494)]
    public class STU_C57FB494 : STU_8BE2DB4D {
        [STUField(0x25517A47, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_95ECA8A6 m_25517A47;

        [STUField(0x64F87F5E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_64F87F5E;

        [STUField(0x6FF59B86, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_95ECA8A6 m_6FF59B86;
    }
}
