// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x964E5ADB)]
    public class STU_964E5ADB : STUConfigVarNumeric {
        [STUField(0xA83C2C26, "m_entity", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_entity;

        [STUField(0x2D3CDFA9, "m_hardPoint", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_hardPoint;
    }
}
