// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x8EF9C6EA)]
    public class STU_8EF9C6EA : STUConfigVarNumeric {
        [STUField(0x1511D47B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_1511D47B;

        [STUField(0x6811BD46, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_6811BD46;
    }
}
