// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xFC044112)]
    public class STU_FC044112 : STUStatescriptAction {
        [STUField(0x93DBA8BA, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_93DBA8BA;
    }
}
