// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0x90B26AC5)]
    public class STU_90B26AC5 : STUUXObject {
        [STUField(0x20AE2CCB)]
        public Enum_1E2FFF3B m_20AE2CCB;

        [STUField(0x413F29AE, "m_key", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUUXObject m_key;

        [STUField(0x5180E750, "m_value", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUUXObject m_value;
    }
}
