// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x33A46033)]
    public class STU_33A46033 : STUStatescriptState {
        [STUField(0x069FD7A5, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_069FD7A5;

        [STUField(0x381879C1, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_381879C1;

        [STUField(0x3C443404, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_3C443404;

        [STUField(0x72FD7742, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_72FD7742;

        [STUField(0x7E42F868, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_7E42F868;

        [STUField(0xD82DB14B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_D82DB14B;

        [STUField(0xDFD8E2EA, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_DFD8E2EA;
    }
}
