// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xFA84B5C0)]
    public class STU_FA84B5C0 : STUInstance {
        [STUField(0x37429C94, "m_blendTime", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_blendTime;
    }
}
