// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x867D9CB1)]
    public class STU_867D9CB1 : STUStatescriptState {
        [STUField(0x00D49978, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_00D49978;
    }
}
