// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xCD5A7576)]
    public class STU_CD5A7576 : STUConfigVarVecBase {
        [STUField(0x0BD936CB, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_0BD936CB;

        [STUField(0x17BB822A, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_17BB822A;

        [STUField(0x50A9A234, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_50A9A234;

        [STUField(0x91CFCC9B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_91CFCC9B;
    }
}
