// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xFCC56E4F)]
    public class STU_FCC56E4F : STUUXDependencyObject {
        [STUField(0xADE95629, "m_items", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_5CEB754E[] m_items;
    }
}
