// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xD0E551CA)]
    public class STU_D0E551CA : STU_C7C085F6 {
        [STUField(0x07D3BC68)]
        public teStructuredDataAssetRef<STUDataFlow> m_07D3BC68;

        [STUField(0x100BFA57)]
        public teStructuredDataAssetRef<STUAnimation> m_100BFA57;

        [STUField(0x1FB4D322)]
        public teStructuredDataAssetRef<STUDataFlow> m_1FB4D322;

        [STUField(0x27BE5765)]
        public float m_27BE5765;

        [STUField(0x2DF94DD9)]
        public teStructuredDataAssetRef<STUAnimation> m_2DF94DD9;

        [STUField(0x3A339D0E)]
        public teStructuredDataAssetRef<STUAnimation> m_3A339D0E;

        [STUField(0x439DEB0C)]
        public teStructuredDataAssetRef<STUAnimation> m_439DEB0C;

        [STUField(0x83C3864A)]
        public teStructuredDataAssetRef<STUAnimation> m_83C3864A;

        [STUField(0x83CE3EB5)]
        public float m_83CE3EB5;

        [STUField(0x86C99D83)]
        public teStructuredDataAssetRef<STUAnimation> m_86C99D83;

        [STUField(0x90F1CC7E)]
        public teStructuredDataAssetRef<STUAnimation> m_90F1CC7E;

        [STUField(0x93BB2F54)]
        public teStructuredDataAssetRef<STUAnimation> m_93BB2F54;

        [STUField(0x972C987A)]
        public float m_972C987A;

        [STUField(0xA12F5018)]
        public teStructuredDataAssetRef<STUAnimation> m_A12F5018;

        [STUField(0xA1AEF21A)]
        public teStructuredDataAssetRef<STUAnimation> m_A1AEF21A;

        [STUField(0xA5F4EB8C)]
        public teStructuredDataAssetRef<STUAnimation> m_A5F4EB8C;

        [STUField(0xB20B8E78)]
        public teStructuredDataAssetRef<STUAnimation> m_B20B8E78;

        [STUField(0xBD2F9E2A)]
        public teStructuredDataAssetRef<STUAnimation> m_BD2F9E2A;

        [STUField(0xCD496C03)]
        public teStructuredDataAssetRef<STUAnimation> m_CD496C03;

        [STUField(0xDF9357CF)]
        public float m_DF9357CF;

        [STUField(0xE8502460)]
        public float m_E8502460;

        [STUField(0xFA6440EE)]
        public teStructuredDataAssetRef<STUAnimation> m_FA6440EE;

        [STUField(0xFBDE5564)]
        public teStructuredDataAssetRef<STUAnimation> m_FBDE5564;

        [STUField(0xF0E4656D, "m_globalLayerMultipliers", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimGlobalLayerMultipliers m_globalLayerMultipliers;

        [STUField(0x5620DA50, "m_globalWeightMultipliers", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimGlobalWeightMultipliers m_globalWeightMultipliers;

        [STUField(0xC4EF5D15, "m_synchGroup")]
        public teStructuredDataAssetRef<STUAnimSynchGroup> m_synchGroup;

        [STUField(0xEC42051A, "m_userWeights", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimUserWeights m_userWeights;
    }
}
