// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x87DC971A)]
    public class STU_87DC971A : STU_19A39F25 {
        [STUField(0x3EAA6598)]
        public teStructuredDataAssetRef<STUAnimation> m_3EAA6598;

        [STUField(0x5A9C70BC)]
        public float m_5A9C70BC;

        [STUField(0x8A0EC9FF)]
        public teStructuredDataAssetRef<STUAnimation> m_8A0EC9FF;

        [STUField(0xABA151EF)]
        public teStructuredDataAssetRef<STUAnimation> m_ABA151EF;

        [STUField(0xCC39AA13)]
        public teStructuredDataAssetRef<STUAnimation> m_CC39AA13;

        [STUField(0xDBDDAEE5)]
        public float m_DBDDAEE5;
    }
}
