// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0xD0275504)]
    public class STU_D0275504 : STU_9881546F {
        [STUField(0x26ED8CC3, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimGameData_BlendDriver m_26ED8CC3;

        [STUField(0x38CF6CD3)]
        public byte m_38CF6CD3;

        [STUField(0x4144C394)]
        public teVec3A[] m_4144C394;

        [STUField(0x7F725CCF, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimGameData_BlendDriver m_7F725CCF;

        [STUField(0xAC4426D3, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimGameData_BlendDriver m_AC4426D3;

        [STUField(0xD2169ABB)]
        public ushort[] m_D2169ABB;
    }
}
