// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x7E39EDFE)]
    public class STU_7E39EDFE : STUStatescriptState {
        [STUField(0x1C9EF058, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_904BFCEC m_1C9EF058;

        [STUField(0x80AF45FB, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_904BFCEC m_80AF45FB;

        [STUField(0xFC33191B, "m_logicalButton", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_logicalButton;

        [STUField(0xA36EEE40, "m_onComingUpPlug", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_onComingUpPlug;

        [STUField(0x133B14AC, "m_onGoingDownPlug", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_onGoingDownPlug;
    }
}
