// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xB6E83679)]
    public class STU_B6E83679 : STU_24E99C78 {
        [STUField(0xADE95629, "m_items", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_items;
    }
}
