// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x62755D14)]
    public class STU_62755D14 : STUStatescriptStateUXPresenter { }
}
