// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0xF4010FCE)]
    public class STU_F4010FCE : STU_4B0FCDF6 {
        [STUField(0x2601D61F)]
        public byte m_2601D61F;

        [STUField(0x378079AE)]
        public byte m_378079AE;

        [STUField(0x41B10FF2)]
        public Enum_32773B82 m_41B10FF2;

        [STUField(0x50530EAB)]
        public float m_50530EAB;

        [STUField(0x60703B1E)]
        public teStructuredDataAssetRef<ulong> m_60703B1E;

        [STUField(0xF60AA143)]
        public teStructuredDataAssetRef<STUIdentifier>[] m_F60AA143;
    }
}
