// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x07864C8B)]
    public class STU_07864C8B : STU_02816D1C {
        [STUField(0x19310F9F, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_0080E34B m_19310F9F;

        [STUField(0x366DD634, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_5FF2A50C m_366DD634;

        [STUField(0x52B7BFC5, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_52B7BFC5;

        [STUField(0x68710D47, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_68710D47;

        [STUField(0xBD192314, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_BD192314;

        [STUField(0xC4E76334, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_C4E76334;

        [STUField(0xDEE8195B, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_0080E34B m_DEE8195B;

        [STUField(0xDF7CC910, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_5FF2A50C m_DF7CC910;
    }
}
