// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x97B1B3EC)]
    public class STU_97B1B3EC : STUStatescriptState {
        [STUField(0x0468C6D4, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_0468C6D4;

        [STUField(0xD6E83CD4, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_D6E83CD4;
    }
}
