// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x2207DD60)]
    public class STU_2207DD60 : STUConfigVarNumeric {
        [STUField(0x1C002272, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_1C002272;

        [STUField(0x52CAFE20, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_52CAFE20;

        [STUField(0xAE2D8911, "m_index", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_index;
    }
}
