// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x431F3FCC)]
    public class STU_431F3FCC : STUStatescriptState {
        [STUField(0x3273B2AB, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_3273B2AB;

        [STUField(0xA76A8CF6, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_A76A8CF6;

        [STUField(0xBC2A8DA3, "m_params", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_814D595E[] m_params;

        [STUField(0xE3798C00, "m_targets", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_targets;
    }
}
