// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xCAA96334)]
    public class STU_CAA96334 : STUStatescriptState {
        [STUField(0x4F64C1D3, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_4F64C1D3;
    }
}
