// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xDD194C91)]
    public class STU_DD194C91 : STUStatescriptAction {
        [STUField(0x1F8A5482, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_1F8A5482;
    }
}
