// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x2AFF1293)]
    public class STU_2AFF1293 : STUEntityComponent {
        [STUField(0xAA2E694E)]
        public teStructuredDataAssetRef<STUIdentifier> m_AA2E694E;
    }
}
