// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x78F2E3C5)]
    public class STU_78F2E3C5 : STU_468B1826 {
        [STUField(0x358E477D)]
        public teStructuredDataAssetRef<STUAnimation> m_358E477D;

        [STUField(0x429857AD)]
        public float m_429857AD;

        [STUField(0x6983C968)]
        public teStructuredDataAssetRef<STUAnimation> m_6983C968;

        [STUField(0x6F9F5FD6)]
        public teStructuredDataAssetRef<STUAnimation> m_6F9F5FD6;

        [STUField(0x7E123C2E)]
        public teStructuredDataAssetRef<STUAnimation> m_7E123C2E;

        [STUField(0x855CC418)]
        public teStructuredDataAssetRef<STUAnimation> m_855CC418;

        [STUField(0xAB42A781)]
        public teStructuredDataAssetRef<STUAnimation> m_AB42A781;

        [STUField(0xAB5DBF58)]
        public teStructuredDataAssetRef<STUAnimation> m_AB5DBF58;

        [STUField(0xAD7B135E)]
        public float m_AD7B135E;

        [STUField(0xAED43E89)]
        public teStructuredDataAssetRef<STUAnimation> m_AED43E89;

        [STUField(0xAF1A38B2)]
        public teStructuredDataAssetRef<STUAnimation> m_AF1A38B2;

        [STUField(0xC2A22A94)]
        public teStructuredDataAssetRef<STUAnimation> m_C2A22A94;

        [STUField(0xC326F9FE)]
        public teStructuredDataAssetRef<STUAnimation> m_C326F9FE;

        [STUField(0xC32B37C2)]
        public teStructuredDataAssetRef<STUAnimation> m_C32B37C2;

        [STUField(0xD36D40ED)]
        public teStructuredDataAssetRef<STUAnimation> m_D36D40ED;

        [STUField(0xD7CF34F5)]
        public teStructuredDataAssetRef<STUAnimation> m_D7CF34F5;

        [STUField(0xEC99F9D8)]
        public teStructuredDataAssetRef<STUAnimation> m_EC99F9D8;

        [STUField(0xFD06CAE5)]
        public teStructuredDataAssetRef<STUAnimation> m_FD06CAE5;
    }
}
