// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x05397F08)]
    public class STU_05397F08 : STUUXViewModel {
        [STUField(0x03FDBB6C)]
        public float m_03FDBB6C;

        [STUField(0x14516339)]
        public float m_14516339;

        [STUField(0x3F5111A7)]
        public float m_3F5111A7;

        [STUField(0x4DFC7752)]
        public byte m_4DFC7752;
    }
}
