// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x678BDD6B)]
    public class STU_678BDD6B : STU_81C5DE19 {
        [STUField(0xF891229F, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_BFDFF4D2 m_F891229F;
    }
}
