// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x1425443C)]
    public class STU_1425443C : STUConfigVarResource {
        [STUField(0xFBF51820, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_FBF51820;
    }
}
