// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xB243F612)]
    public class STU_B243F612 : STU_C7C085F6 {
        [STUField(0x07D3BC68)]
        public teStructuredDataAssetRef<STUDataFlow> m_07D3BC68;

        [STUField(0x1FB4D322)]
        public teStructuredDataAssetRef<STUDataFlow> m_1FB4D322;

        [STUField(0x27BE5765)]
        public float m_27BE5765;

        [STUField(0x5E009A60)]
        public byte m_5E009A60;

        [STUField(0x67B28A3B)]
        public float m_67B28A3B;

        [STUField(0x6D2F8BDE)]
        public byte m_6D2F8BDE;

        [STUField(0x972C987A)]
        public float m_972C987A;

        [STUField(0xB9839141)]
        public teStructuredDataAssetRef<STUAnimIdentifier> m_B9839141;

        [STUField(0xBF930850)]
        public teStructuredDataAssetRef<STUAnimIdentifier> m_BF930850;

        [STUField(0xD80506E4)]
        public float m_D80506E4;

        [STUField(0xDA055D06)]
        public teStructuredDataAssetRef<STUAnimIdentifier> m_DA055D06;

        [STUField(0xEE8AE282)]
        public teStructuredDataAssetRef<STUAnimIdentifier> m_EE8AE282;

        [STUField(0xF0E4656D, "m_globalLayerMultipliers", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimGlobalLayerMultipliers m_globalLayerMultipliers;

        [STUField(0x5620DA50, "m_globalWeightMultipliers", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimGlobalWeightMultipliers m_globalWeightMultipliers;

        [STUField(0x7E2A7D18, "m_runAimAdditiveE")]
        public teStructuredDataAssetRef<STUAnimation> m_runAimAdditiveE;

        [STUField(0x59860ABF, "m_runAimAdditiveN")]
        public teStructuredDataAssetRef<STUAnimation> m_runAimAdditiveN;

        [STUField(0x30AC076A, "m_runAimAdditiveS")]
        public teStructuredDataAssetRef<STUAnimation> m_runAimAdditiveS;

        [STUField(0x6A64DD95, "m_runAimAdditiveW")]
        public teStructuredDataAssetRef<STUAnimation> m_runAimAdditiveW;

        [STUField(0xB3DD0020, "m_runE")]
        public teStructuredDataAssetRef<STUAnimation> m_runE;

        [STUField(0x9A7ECA46, "m_runN")]
        public teStructuredDataAssetRef<STUAnimation> m_runN;

        [STUField(0xACB0FAE2, "m_runS")]
        public teStructuredDataAssetRef<STUAnimation> m_runS;

        [STUField(0xB5ECB1C4, "m_runSpeedE")]
        public float m_runSpeedE;

        [STUField(0x4366D221, "m_runSpeedN")]
        public float m_runSpeedN;

        [STUField(0x7201BAA6, "m_runSpeedS")]
        public float m_runSpeedS;

        [STUField(0xB1C32752, "m_runSpeedW")]
        public float m_runSpeedW;

        [STUField(0xE45FBD36, "m_runW")]
        public teStructuredDataAssetRef<STUAnimation> m_runW;

        [STUField(0xEC42051A, "m_userWeights", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimUserWeights m_userWeights;
    }
}
