// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0x20E18047)]
    public class STU_20E18047 : STU_B024BE51 {
        [STUField(0x8213EB22, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_8213EB22;

        [STUField(0x8AD739CE, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_8AD739CE;

        [STUField(0xA9561CA0)]
        public Enum_7BC645F4 m_A9561CA0;
    }
}
