// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x30C2E3AE)]
    public class STU_30C2E3AE : STU_9881546F {
        [STUField(0x38CF6CD3)]
        public byte m_38CF6CD3;

        [STUField(0x7F725CCF, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimGameData_BlendDriver m_7F725CCF;

        [STUField(0xAC4426D3, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimGameData_BlendDriver m_AC4426D3;

        [STUField(0xC15DCB47, "m_IKItems", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimGameData_NodeToDirectionIKItem[] m_IKItems;
    }
}
