// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0x7FE21161)]
    public class STU_7FE21161 : STUConfigVarBoolBase {
        [STUField(0xB1E7FC90)]
        public Enum_A8F9FD89 m_B1E7FC90;
    }
}
