// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x03461D6C)]
    public class STU_03461D6C : STUGenericSettings_Base {
        [STUField(0x04AA1344)]
        public float m_04AA1344;

        [STUField(0x07C65134)]
        public float m_07C65134;

        [STUField(0x0BA27AD2)]
        public float m_0BA27AD2;

        [STUField(0x3637F9F3)]
        public float m_3637F9F3;

        [STUField(0x5E090664)]
        public float m_5E090664;

        [STUField(0x9A9E72EC)]
        public byte m_9A9E72EC;

        [STUField(0xC7074404)]
        public byte m_C7074404;
    }
}
