// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x3E82F994)]
    public class STU_3E82F994 : STU_C7C085F6 {
        [STUField(0x83CE3EB5)]
        public float m_83CE3EB5;

        [STUField(0x990066D8)]
        public teStructuredDataAssetRef<STUDataFlow> m_990066D8;

        [STUField(0xE8502460)]
        public float m_E8502460;
    }
}
