// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0xF6792065)]
    public class STU_F6792065 : STUConfigVarIntBase {
        [STUField(0x3CFA3EE6, "m_locale")]
        public Enum_1C8CB734 m_locale;
    }
}
