// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x2187A0E8)]
    public class STU_2187A0E8 : STUStatescriptWeaponProjectileMotion {
        [STUField(0x0825DC20, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_0825DC20;

        [STUField(0x18A39F22, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_18A39F22;

        [STUField(0x22B7792D, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_22B7792D;

        [STUField(0x56EF0E34, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_56EF0E34;

        [STUField(0x639EC1F1, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_639EC1F1;

        [STUField(0x731CC2AF, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_731CC2AF;

        [STUField(0x7B36BBB6, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_7B36BBB6;

        [STUField(0x8D945F92, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_8D945F92;

        [STUField(0xA621D730, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_A621D730;

        [STUField(0xC36D4DE2, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_C36D4DE2;

        [STUField(0xC886474A, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_C886474A;

        [STUField(0xD02C97C9, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_D02C97C9;

        [STUField(0xD032C9CB, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_D032C9CB;

        [STUField(0xD039E153, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_D039E153;

        [STUField(0xD17D4102, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_D17D4102;

        [STUField(0xECB69C9D, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_ECB69C9D;

        [STUField(0xF700A535, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_F700A535;
    }
}
