// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xFA258ECC)]
    public class STU_FA258ECC : STU_5DB5B1C9 {
        [STUField(0x4D530E8A)]
        public float m_4D530E8A;

        [STUField(0xC41767A5)]
        public float m_C41767A5;
    }
}
