// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x95FA12D3)]
    public class STU_95FA12D3 : STU_48A39D9B {
        [STUField(0xE1D625B8)]
        public teStructuredDataAssetRef<STUVoiceStimulus> m_E1D625B8;
    }
}
