// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x569C801E)]
    public class STU_569C801E : STUInstance {
        [STUField(0x0DFBF3DA, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_6F01D053 m_0DFBF3DA;

        [STUField(0x1E890BF5, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_6F01D053 m_1E890BF5;

        [STUField(0x3661B9E8, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_6F01D053 m_3661B9E8;

        [STUField(0x399EAEC6, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_6F01D053 m_399EAEC6;

        [STUField(0x836924DF, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_6F01D053 m_836924DF;

        [STUField(0x915B1F4B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_6F01D053 m_915B1F4B;

        [STUField(0xACA0C8B2, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_6F01D053 m_ACA0C8B2;

        [STUField(0xC652451B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_6F01D053 m_C652451B;

        [STUField(0x9556D6E4, "m_crouch", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_6F01D053 m_crouch;

        [STUField(0xDD37B450, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_6F01D053 m_DD37B450;

        [STUField(0x5F150DBC, "m_jump", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_6F01D053 m_jump;
    }
}
