// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x39EF4AB5)]
    public class STU_39EF4AB5 : STU_11E07FD7 {
        [STUField(0x2CCD3E96, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_5FF2A50C m_2CCD3E96;

        [STUField(0x3185697A, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_5FF2A50C m_3185697A;

        [STUField(0x7B5A8DA1, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_D5E7FD6F m_7B5A8DA1;
    }
}
