// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x313CCF65)]
    public class STU_313CCF65 : STU_38E34B67 {
        [STUField(0x6E01378E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_5BE96557 m_6E01378E;

        [STUField(0xBC4326FF, "m_stat")]
        public teStructuredDataAssetRef<STUStat> m_stat;
    }
}
