// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x6821380D)]
    public class STU_6821380D : STU_D6F132F4 {
        [STUField(0xE4506875, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_2F472437 m_E4506875;
    }
}
