// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x1E41B675)]
    public class STU_1E41B675 : STUInstance {
        [STUField(0x00E7BB91)]
        public teString m_00E7BB91;

        [STUField(0x03376566, "m_textureType", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_05BDD390 m_textureType;
    }
}
