// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x6ED4837F)]
    public class STU_6ED4837F : STUStatescriptAction {
        [STUField(0x1511D47B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_1511D47B;

        [STUField(0x1A8B926A, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_1A8B926A;

        [STUField(0x22326315, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_22326315;

        [STUField(0x231F9132, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_231F9132;

        [STUField(0x373DBF32, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_373DBF32;

        [STUField(0x664984E6, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_664984E6;

        [STUField(0xA26FDEE9, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_A26FDEE9;

        [STUField(0xA6661042, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_A6661042;

        [STUField(0xB4FF0E2F, "m_animAlias", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_animAlias;

        [STUField(0xB8CC7D64, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_B8CC7D64;

        [STUField(0xD8514AD9, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_D8514AD9;
    }
}
