// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xA1B7741E)]
    public class STU_A1B7741E : STUInstance {
        [STUField(0x42CD3B1E)]
        public teStructuredDataAssetRef<STUTexture> m_42CD3B1E;

        [STUField(0x5E44D8C3)]
        public teStructuredDataAssetRef<STUTexture> m_5E44D8C3;

        [STUField(0xCB803FD9)]
        public float m_CB803FD9;

        [STUField(0xEC613BC5, "m_starData")]
        public teStructuredDataAssetRef<STUTexture> m_starData;

        [STUField(0x01D31F55, "m_twinkleSpeed")]
        public float m_twinkleSpeed;
    }
}
