// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x2D9C8BAD)]
    public class STU_2D9C8BAD : STUGenericSettings_Base {
        [STUField(0x8F5C84AC, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_BEE7F20E[] m_8F5C84AC;
    }
}
