// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0xF4C77F4A)]
    public class STU_F4C77F4A : STUConfigVar {
        [STUField(0x4BA4C058)]
        public Enum_CEBBB217 m_4BA4C058;

        [STUField(0x07DD813E, "m_value", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_value;
    }
}
