// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xA8A6A1AE)]
    public class STU_A8A6A1AE : STU_5BF8DA7A {
        [STUField(0xB3EC7449, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_ABD8FE73 m_B3EC7449;

        [STUField(0xDCBB5B2E, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_ABD8FE73 m_DCBB5B2E;
    }
}
