// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x5FBA8278)]
    public class STU_5FBA8278 : STU_E7DC5ED6 {
        [STUField(0xBD631144, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarVec2 m_BD631144;

        [STUField(0xF24CD9C1, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarVec2 m_F24CD9C1;
    }
}
