// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xE2DB55BC)]
    public class STU_E2DB55BC : STU_C7C085F6 {
        [STUField(0x256D9041)]
        public teStructuredDataAssetRef<STUAnimation> m_256D9041;

        [STUField(0x347ADE35)]
        public float m_347ADE35;

        [STUField(0x3590F2A2)]
        public float m_3590F2A2;

        [STUField(0x3AB4BEA4)]
        public teStructuredDataAssetRef<STUAnimation> m_3AB4BEA4;

        [STUField(0x5154AD22)]
        public teStructuredDataAssetRef<STUAnimation> m_5154AD22;

        [STUField(0x5ABE6621)]
        public teStructuredDataAssetRef<STUAnimation> m_5ABE6621;

        [STUField(0x62438C3C)]
        public float m_62438C3C;

        [STUField(0x73DA6F95)]
        public teStructuredDataAssetRef<STUAnimation> m_73DA6F95;

        [STUField(0x83C3864A)]
        public teStructuredDataAssetRef<STUAnimation> m_83C3864A;

        [STUField(0x83CE3EB5)]
        public float m_83CE3EB5;

        [STUField(0x93BB2F54)]
        public teStructuredDataAssetRef<STUAnimation> m_93BB2F54;

        [STUField(0x93CEEFAE)]
        public teStructuredDataAssetRef<STUAnimation> m_93CEEFAE;

        [STUField(0xA12F5018)]
        public teStructuredDataAssetRef<STUAnimation> m_A12F5018;

        [STUField(0xA1AEF21A)]
        public teStructuredDataAssetRef<STUAnimation> m_A1AEF21A;

        [STUField(0xA4D7E083)]
        public teStructuredDataAssetRef<STUAnimation> m_A4D7E083;

        [STUField(0xB20B8E78)]
        public teStructuredDataAssetRef<STUAnimation> m_B20B8E78;

        [STUField(0xC7EC45F3)]
        public teStructuredDataAssetRef<STUAnimation> m_C7EC45F3;

        [STUField(0xCD496C03)]
        public teStructuredDataAssetRef<STUAnimation> m_CD496C03;

        [STUField(0xE4A352BB)]
        public teStructuredDataAssetRef<STUAnimation> m_E4A352BB;

        [STUField(0xE80A4E89)]
        public teStructuredDataAssetRef<STUAnimation> m_E80A4E89;

        [STUField(0xE8502460)]
        public float m_E8502460;

        [STUField(0xECF32A1D)]
        public float m_ECF32A1D;

        [STUField(0xFA6440EE)]
        public teStructuredDataAssetRef<STUAnimation> m_FA6440EE;

        [STUField(0xFBDE5564)]
        public teStructuredDataAssetRef<STUAnimation> m_FBDE5564;

        [STUField(0xF0E4656D, "m_globalLayerMultipliers", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimGlobalLayerMultipliers m_globalLayerMultipliers;

        [STUField(0x5620DA50, "m_globalWeightMultipliers", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimGlobalWeightMultipliers m_globalWeightMultipliers;

        [STUField(0xEC42051A, "m_userWeights", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimUserWeights m_userWeights;
    }
}
