// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x579AA57A)]
    public class STU_579AA57A : STU_C7C085F6 {
        [STUField(0x0A1AE075)]
        public teStructuredDataAssetRef<STUAnimation> m_0A1AE075;
    }
}
