// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0x0D3E9B37)]
    public class STU_0D3E9B37 : STU_A2B9762B {
        [STUField(0x11665D35)]
        public uint m_11665D35;

        [STUField(0x1EA749A8)]
        public teVec3 m_1EA749A8;

        [STUField(0x2756356E)]
        public teStructuredDataAssetRef<STUEmptyAsset> m_2756356E;

        [STUField(0x3D2FC8F2)]
        public byte m_3D2FC8F2;

        [STUField(0x40CE1934)]
        public byte m_40CE1934;

        [STUField(0x77E70F30)]
        public byte m_77E70F30;

        [STUField(0xBA6E2567)]
        public byte m_BA6E2567;

        [STUField(0xDD193DC7)]
        public int m_DD193DC7;

        [STUField(0xF530632B)]
        public byte m_F530632B;

        [STUField(0x9297ADB4, "m_look")]
        public teStructuredDataAssetRef<STUModelLook> m_look;

        [STUField(0x2D124BE2, "m_model")]
        public teStructuredDataAssetRef<STUModel> m_model;
    }
}
