// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0x1F2DB0E9)]
    public class STU_1F2DB0E9 : STUStatescriptAction {
        [STUField(0x6E2D2269, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_6E2D2269;

        [STUField(0xAF872E86, "m_amount", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_amount;

        [STUField(0xB44A42A0)]
        public Enum_E7FEC166 m_B44A42A0;

        [STUField(0xE3798C00, "m_targets", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_targets;
    }
}
