// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x2ADAE886)]
    public class STU_2ADAE886 : STUConfigVarNumeric {
        [STUField(0x669742DF, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_669742DF;
    }
}
