// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x32A19631)]
    public class STU_32A19631 : STUCriteriaContainer {
        [STUField(0x4FF98D41, "m_criteria", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUCriteria m_criteria;
    }
}
