// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.Math;
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0x43F2D6CE)]
    public class STU_43F2D6CE : STU_A3C7077A {
        [STUField(0x09E32A58)]
        public teStructuredDataAssetRef<STUTexture> m_09E32A58;

        [STUField(0x0F10EA0D)]
        public teVec2 m_0F10EA0D;

        [STUField(0x10952B01)]
        public teStructuredDataAssetRef<STUTexture> m_10952B01;

        [STUField(0x220E06E7)]
        public teVec2 m_220E06E7;

        [STUField(0x2370E609)]
        public teStructuredDataAssetRef<STUTexture> m_2370E609;

        [STUField(0x28FB9D5B)]
        public byte m_28FB9D5B;

        [STUField(0x409AA45A)]
        public teVec2 m_409AA45A;

        [STUField(0x41C1DCFF)]
        public teVec2 m_41C1DCFF;

        [STUField(0x46767D1C)]
        public byte m_46767D1C;

        [STUField(0x56F4DE27)]
        public teStructuredDataAssetRef<STUTexture> m_56F4DE27;

        [STUField(0x79717A32)]
        public teStructuredDataAssetRef<STUTexture> m_79717A32;

        [STUField(0x8F505B17)]
        public byte m_8F505B17;

        [STUField(0x90D4477E)]
        public float m_90D4477E;

        [STUField(0xA665A5E4)]
        public teStructuredDataAssetRef<STUTexture> m_A665A5E4;

        [STUField(0xB999DDE2)]
        public teStructuredDataAssetRef<STUEmptyAsset> m_B999DDE2;

        [STUField(0xCC99D954)]
        public Enum_C3835917 m_CC99D954;

        [STUField(0xD0A9CB68)]
        public teStructuredDataAssetRef<STUTexture> m_D0A9CB68;

        [STUField(0xD7D21151)]
        public byte m_D7D21151;

        [STUField(0xE1E200DD)]
        public teStructuredDataAssetRef<STUTexture> m_E1E200DD;

        [STUField(0xE88B4D9C)]
        public teStructuredDataAssetRef<STUTexture> m_E88B4D9C;
    }
}
