// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x68CCCD14)]
    public class STU_68CCCD14 : STU_81C5DE19 {
        [STUField(0xF891229F, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_B243F612 m_F891229F;
    }
}
