// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x5CD96CBC)]
    public class STU_5CD96CBC : STUUXDependencyObject {
        [STUField(0xC08C4427, "m_name")]
        public teString m_name;
    }
}
