// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x406F6657)]
    public class STU_406F6657 : STUUXObject {
        [STUField(0x32BD58D8)]
        public float m_32BD58D8;

        [STUField(0xABB40962)]
        public float m_ABB40962;

        [STUField(0xDCB339F4)]
        public float m_DCB339F4;
    }
}
