// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xF92E0197)]
    public class STU_F92E0197 : STUInstance {
        [STUField(0x96960C7F)]
        public float m_96960C7F;

        [STUField(0xA3659A33)]
        public float m_A3659A33;

        [STUField(0xDAE04657)]
        public float m_DAE04657;

        [STUField(0x131257CD, "m_root")]
        public float m_root;
    }
}
