// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xA7D47BFB)]
    public class STU_A7D47BFB : STU_A69B15DF {
        [STUField(0x5C37D901, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_5C37D901;

        [STUField(0x7A205EAB, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_7A205EAB;

        [STUField(0xAB865FDF, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_AB865FDF;

        [STUField(0xBD0C1FCC, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_5FF2A50C m_BD0C1FCC;
    }
}
