// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0x816E1D84)]
    public class STU_816E1D84 : STUUXObject {
        [STUField(0xDB7251F5)]
        public Enum_29852471 m_DB7251F5;

        [STUField(0x92456ACD, "m_unitValue")]
        public float m_unitValue;
    }
}
