// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x51BBFB1B)]
    public class STU_51BBFB1B : STUStatescriptState {
        [STUField(0x69A20070, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_69A20070;
    }
}
