// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xD3FE890D)]
    public class STU_D3FE890D : STUAnimNode_Base {
        [STUField(0x41B10FF2, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_D8E10207 m_41B10FF2;

        [STUField(0x541B8505, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_6754CB2C m_541B8505;

        [STUField(0x436BEFE6, "m_child", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_2F6BD485 m_child;

        [STUField(0x0F88291F, "m_weightDriver", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_5861C542 m_weightDriver;
    }
}
