// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x6DD1227E)]
    public class STU_6DD1227E : STUUXViewModel {
        [STUField(0x09FF7FC4)]
        public uint m_09FF7FC4;

        [STUField(0x7EF84F52)]
        public uint m_7EF84F52;

        [STUField(0x8D1920D6)]
        public uint m_8D1920D6;

        [STUField(0xCA2B86CD)]
        public teString m_CA2B86CD;

        [STUField(0xF707E9B2)]
        public byte m_F707E9B2;

        [STUField(0xFA1E1040)]
        public uint m_FA1E1040;

        [STUField(0xD900A4F6, "m_instanceID")]
        public teString m_instanceID;

        [STUField(0x685F2338, "m_mapName")]
        public teString m_mapName;

        [STUField(0xA5249DE6, "m_text")]
        public teString m_text;
    }
}
