// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xC3970933)]
    public class STU_C3970933 : STU_11E07FD7 {
        [STUField(0x04D6C5FB, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_04D6C5FB;

        [STUField(0x11638037, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_11638037;

        [STUField(0x188AB33A, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_188AB33A;

        [STUField(0x22D24F46, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_22D24F46;

        [STUField(0x2368E244, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_5FF2A50C m_2368E244;

        [STUField(0x24CB161B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_24CB161B;

        [STUField(0x36E9C558, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_5FF2A50C m_36E9C558;

        [STUField(0x40AF7E2D, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_40AF7E2D;

        [STUField(0x48D51D05, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_5FF2A50C m_48D51D05;

        [STUField(0x4FBCC91D, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_5FF2A50C m_4FBCC91D;

        [STUField(0x5837EFA9, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_D5E7FD6F m_5837EFA9;

        [STUField(0x5ECE134F, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_5ECE134F;

        [STUField(0x60C7A1E1, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_60C7A1E1;

        [STUField(0x66245BFD, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_5FF2A50C m_66245BFD;

        [STUField(0x704ED897, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_704ED897;

        [STUField(0x771622BE, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_5FF2A50C m_771622BE;

        [STUField(0xAE003B9F, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_5FF2A50C m_AE003B9F;

        [STUField(0xAE6BDE19, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_23E1B2C7 m_AE6BDE19;

        [STUField(0xB999DDE2, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_C1B3C816 m_B999DDE2;

        [STUField(0xC59C2F60, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_C59C2F60;

        [STUField(0xCE228ECE, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_5FF2A50C m_CE228ECE;

        [STUField(0xCF5C7637, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_5FF2A50C m_CF5C7637;

        [STUField(0xD89DEC69, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_D5E7FD6F m_D89DEC69;

        [STUField(0xD8B90B72, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_5FF2A50C m_D8B90B72;

        [STUField(0xE7B8C4D3, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_5FF2A50C m_E7B8C4D3;

        [STUField(0xEC5CB8E5, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_EC5CB8E5;

        [STUField(0xAF9D3A0C, "m_rotation", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_rotation;
    }
}
