// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xB0BDCC9E)]
    public class STU_B0BDCC9E : STU_C25D0808 {
        [STUField(0x1A79E8C2, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_95ECA8A6 m_1A79E8C2;

        [STUField(0x32A4DD2D, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_95ECA8A6 m_32A4DD2D;

        [STUField(0x3DB48AC9, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_95ECA8A6 m_3DB48AC9;

        [STUField(0x6E41B131, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_95ECA8A6 m_6E41B131;

        [STUField(0x7F3D91D1, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_95ECA8A6 m_7F3D91D1;

        [STUField(0x7F7F8EC0, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_95ECA8A6 m_7F7F8EC0;

        [STUField(0x8BA2EA97, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_95ECA8A6 m_8BA2EA97;

        [STUField(0x929AD43D, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_95ECA8A6 m_929AD43D;

        [STUField(0x98790F67, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_95ECA8A6 m_98790F67;

        [STUField(0x99CDB6CB, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_95ECA8A6 m_99CDB6CB;

        [STUField(0xA57C71C4, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_95ECA8A6 m_A57C71C4;

        [STUField(0xAA49CBE9, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_95ECA8A6 m_AA49CBE9;

        [STUField(0xB27CA5AB, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_95ECA8A6 m_B27CA5AB;

        [STUField(0xB4D60420, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_95ECA8A6 m_B4D60420;

        [STUField(0xCED74653, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_95ECA8A6 m_CED74653;

        [STUField(0xDD194B99, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_95ECA8A6 m_DD194B99;
    }
}
