// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xC820D8E1)]
    public class STU_C820D8E1 : STUConfigVarNumeric {
        [STUField(0xA83C2C26, "m_entity", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_entity;

        [STUField(0x2D3CDFA9, "m_hardPoint", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_hardPoint;
    }
}
