// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0x55B3796C)]
    public class STU_55B3796C : STUInstance {
        [STUField(0x07E7E02F)]
        public float m_07E7E02F;

        [STUField(0x28DEBC92)]
        public float m_28DEBC92;

        [STUField(0x73563892)]
        public float m_73563892;

        [STUField(0x762E3F53)]
        public float m_762E3F53;

        [STUField(0xD34DF2A2)]
        public teUUID m_D34DF2A2;

        [STUField(0xEA2702B3)]
        public float m_EA2702B3;
    }
}
