// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x1E2BDD32)]
    public class STU_1E2BDD32 : STU_952571B3 {
        [STUField(0x19B3077A, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_6C8D2AC1 m_19B3077A;

        [STUField(0xABBF26D5, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_E6999411 m_ABBF26D5;

        [STUField(0xF96EF7D0)]
        public float m_F96EF7D0;

        [STUField(0xFCAB3ABC)]
        public float m_FCAB3ABC;
    }
}
