// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x3033FF61)]
    public class STU_3033FF61 : STU_319619ED {
        [STUField(0xF2160520)]
        public teStructuredDataAssetRef<STU_53908303> m_F2160520;

        [STUField(0x2F709539, "m_key")]
        public ulong m_key;
    }
}
