// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0xB9BE2BE1)]
    public class STU_B9BE2BE1 : STUConfigVarIntBase {
        [STUField(0x1A69E234)]
        public Enum_AD46F1CE m_1A69E234;
    }
}
