// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xA3645D25)]
    public class STU_A3645D25 : STUInstance {
        [STUField(0xD45946D7)]
        public uint m_D45946D7;

        [STUField(0x5DB91CE2, "m_displayName")]
        public teString m_displayName;

        [STUField(0xFBB4C33C)]
        public byte[] m_FBB4C33C;
    }
}
