// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0x5E7654D9)]
    public class STU_5E7654D9 : STUConfigVar {
        [STUField(0x030C066C, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_030C066C;

        [STUField(0x7567E07D)]
        public Enum_0DCDF3CD m_7567E07D;
    }
}
