// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0xC3D42AEF)]
    public class STU_C3D42AEF : STU_C7C085F6 {
        [STUField(0x1B4288DF)]
        public teStructuredDataAssetRef<STUAnimation> m_1B4288DF;

        [STUField(0x27158126)]
        public float m_27158126;

        [STUField(0x2C95CD87)]
        public float m_2C95CD87;

        [STUField(0x2D85A9B2)]
        public teStructuredDataAssetRef<STUAnimation> m_2D85A9B2;

        [STUField(0x2DBE921D)]
        public float m_2DBE921D;

        [STUField(0x35D0EDFE)]
        public float m_35D0EDFE;

        [STUField(0x42AD1319)]
        public float m_42AD1319;

        [STUField(0x497ADC45)]
        public float m_497ADC45;

        [STUField(0x5D8DBAF3)]
        public teVec2 m_5D8DBAF3;

        [STUField(0x609AD386)]
        public float m_609AD386;

        [STUField(0x63BA70FA)]
        public float m_63BA70FA;

        [STUField(0x796BAC2C)]
        public float m_796BAC2C;

        [STUField(0xB4C36FFC)]
        public byte m_B4C36FFC;

        [STUField(0xC5E663C0)]
        public float m_C5E663C0;

        [STUField(0xCCDA23EA)]
        public teStructuredDataAssetRef<STUAnimation> m_CCDA23EA;

        [STUField(0xDD794862)]
        public float m_DD794862;
    }
}
