// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x68883EAC)]
    public class STU_68883EAC : STUConfigVarNumeric {
        [STUField(0x7BE02F89, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_7BE02F89;

        [STUField(0x7E8B666C, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_7E8B666C;

        [STUField(0xA83C2C26, "m_entity", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_entity;
    }
}
