// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0x633CF164)]
    public class STU_633CF164 : STUInstance {
        [STUField(0xA096ADDF)]
        public teVec3A m_A096ADDF;

        [STUField(0xED61D926, "m_radius")]
        public float m_radius;
    }
}
