// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x5AA11BA0)]
    public class STU_5AA11BA0 : STUUXObject {
        [STUField(0x5180E750, "m_value")]
        public long m_value;
    }
}
