// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x5F94FAF9)]
    public class STU_5F94FAF9 : STUConfigVarIntBase {
        [STUField(0xE153523C, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_E153523C;

        [STUField(0xA83C2C26, "m_entity", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_entity;
    }
}
