// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x3F65FB99)]
    public class STU_3F65FB99 : STUStatescriptState {
        [STUField(0x0E84B2C3, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_0E84B2C3;

        [STUField(0x799CD1B7, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_799CD1B7;

        [STUField(0x48486367, "m_instigator", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_instigator;
    }
}
