// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xDBC82D48)]
    public class STU_DBC82D48 : STU_BB05BF11 {
        [STUField(0xCC84D865, "m_index")]
        public int m_index;
    }
}
