// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x5AD3B86B)]
    public class STU_5AD3B86B : STUComponentInstanceData {
        [STUField(0x41180910)]
        public int m_41180910;

        [STUField(0xDF9357CF)]
        public float m_DF9357CF;
    }
}
