// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x06FBC46C)]
    public class STU_06FBC46C : STUUXObject {
        [STUField(0x7384070D)]
        public teStructuredDataAssetRef<STU_5A381A2F> m_7384070D;
    }
}
