// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x2D6042D2)]
    public class STU_2D6042D2 : STU_783B8A59 {
        [STUField(0x0ADE5570, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_12ED1E44 m_0ADE5570;
    }
}
