// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x77C3657D)]
    public class STU_77C3657D : STUStatescriptState {
        [STUField(0xE8951580, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_E8951580;

        [STUField(0xF422B42A, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_F422B42A;

        [STUField(0x5DA62D02, "m_onAbortPlug", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_onAbortPlug;

        [STUField(0xA0B58111, "m_onFinishedPlug", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_onFinishedPlug;
    }
}
