// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x2B4F838B)]
    public class STU_2B4F838B : STUConfigVarIntBase {
        [STUField(0x05E64AB8, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_05E64AB8;

        [STUField(0x1C1F2277, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_1C1F2277;

        [STUField(0x25E23697, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_25E23697;

        [STUField(0x2E22E1E8, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_2E22E1E8;

        [STUField(0x456D722B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_456D722B;

        [STUField(0x5D33B02A, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_5D33B02A;

        [STUField(0x688F150F, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_688F150F;

        [STUField(0x7ABA71B8, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_7ABA71B8;

        [STUField(0x7B404F54, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_7B404F54;

        [STUField(0x87A460C3, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_87A460C3;

        [STUField(0xF2B762C2, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_F2B762C2;

        [STUField(0x7DC1550F, "m_position", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_position;
    }
}
