// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x44A67DA2)]
    public class STU_44A67DA2 : STUConfigVarNumeric {
        [STUField(0x7826B991, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_7826B991;

        [STUField(0x8A12D912, "m_target", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_target;
    }
}
