// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x7106C356)]
    public class STU_7106C356 : STUStatescriptAction {
        [STUField(0x63CB0D07, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_63CB0D07;

        [STUField(0x78468866, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_78468866;

        [STUField(0x81C1E518, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_81C1E518;

        [STUField(0xD030750C, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_D030750C;

        [STUField(0xF1CB3BA0, "m_text", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_text;
    }
}
