// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x744BC2A9)]
    public class STU_744BC2A9 : STU_B4CD94F4 {
        [STUField(0x0B528B1E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_0B528B1E;
    }
}
