// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x00707E1E)]
    public class STU_00707E1E : STUConfigVarEntityID {
        [STUField(0x00903303, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_00903303;
    }
}
