// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xE27393EE)]
    public class STU_E27393EE : STUConfigVarStringBase {
        [STUField(0x5DC61E59, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_5DC61E59;

        [STUField(0xCC3ECC89, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_CC3ECC89;
    }
}
