// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x61DACB9B)]
    public class STU_61DACB9B : STU_A3C7077A {
        [STUField(0xB14EAA65)]
        public float m_B14EAA65;

        [STUField(0xB999DDE2)]
        public teStructuredDataAssetRef<STUEmptyAsset> m_B999DDE2;
    }
}
