// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xA753DC79)]
    public class STU_A753DC79 : STUConfigVar {
        [STUField(0x74A2248F)]
        public int m_74A2248F;
    }
}
