// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0xB651E94A)]
    public class STU_B651E94A : STU_3660CDED {
        [STUField(0x3FAFF222)]
        public Enum_BC76726E m_3FAFF222;
    }
}
