// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xAFE67DBF)]
    public class STU_AFE67DBF : STUStatescriptScreenVM {
        [STUField(0x172F73DC)]
        public float m_172F73DC;

        [STUField(0x2D5B443E)]
        public float m_2D5B443E;

        [STUField(0x476C14E5)]
        public byte m_476C14E5;

        [STUField(0x6CEBC552)]
        public byte m_6CEBC552;

        [STUField(0xB03BF481)]
        public byte m_B03BF481;

        [STUField(0x058BE3BD, "m_distanceString")]
        public teString m_distanceString;

        [STUField(0x4B7664AB, "m_pos")]
        public float m_pos;
    }
}
