// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x67B86A92)]
    public class STU_67B86A92 : STU_851FBF1A {
        [STUField(0x3CD6DC1E, "m_texture")]
        public teStructuredDataAssetRef<STUTexture> m_texture;
    }
}
