// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xCF543628)]
    public class STU_CF543628 : STU_05BDD390 {
        [STUField(0x15BE7741, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_F4F1F144 m_15BE7741;
    }
}
