// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x85F98ECC)]
    public class STU_85F98ECC : STUUXViewModel {
        [STUField(0xA5249DE6, "m_text")]
        public teString m_text;

        [STUField(0x34A67CC4, "m_timeRemaining")]
        public float m_timeRemaining;
    }
}
