// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x9489BD3D)]
    public class STU_9489BD3D : STU_820A411A {
        [STUField(0x3E3DFE0F, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_3E3DFE0F;

        [STUField(0x6EFD110C, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_6EFD110C;

        [STUField(0x8F4413B1, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_5FF2A50C m_8F4413B1;

        [STUField(0xD80AEDB1, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_D80AEDB1;

        [STUField(0x9352A840, "m_direction", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_direction;
    }
}
