// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x571A427A)]
    public class STU_571A427A : STUConfigVarNumeric {
        [STUField(0x7826B991, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_7826B991;

        [STUField(0x8A12D912, "m_target", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_target;
    }
}
