// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x2C091D22)]
    public class STU_2C091D22 : STUInstance {
        [STUField(0x1CE54D19)]
        public float m_1CE54D19;

        [STUField(0xD9FC743A)]
        public float m_D9FC743A;
    }
}
