// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x77990ED7)]
    public class STU_77990ED7 : STUStatescriptSchema {
        [STUField(0x89EAAC40)]
        public teStructuredDataAssetRef<STU_6BE90C5C> m_89EAAC40;
    }
}
