// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x111A6193)]
    public class STU_111A6193 : STUInstance {
        [STUField(0x1F3357A2)]
        public byte m_1F3357A2;

        [STUField(0xBA891264, "m_dataFlow")]
        public teStructuredDataAssetRef<STUDataFlow> m_dataFlow;
    }
}
