// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x7C27312D)]
    public class STU_7C27312D : STUInstance {
        [STUField(0xC08C4427, "m_name")]
        public teString m_name;
    }
}
