// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xA0520996)]
    public class STU_A0520996 : STUConfigVarIntBase {
        [STUField(0x4992CB75, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_4992CB75;
    }
}
