// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x38134051)]
    public class STU_38134051 : STUUXResource {
        [STUField(0xB5C0F593, "m_guid")]
        public teStructuredDataAssetRef<STUFontFamily> m_guid;
    }
}
