// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xC7CA73B1)]
    public class STU_C7CA73B1 : STUCriteria {
        [STUField(0xE02BEE24, "m_celebration")]
        public teStructuredDataAssetRef<STUCelebration> m_celebration;
    }
}
