// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x7C123C97)]
    public class STU_7C123C97 : STU_D6F132F4 {
        [STUField(0xD110FFD3, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_258AA05C[] m_D110FFD3;
    }
}
