// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x0FB16000)]
    public class STU_0FB16000 : STUConfigVarBoolBase {
        [STUField(0xAFBBE9C3, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_AFBBE9C3;

        [STUField(0xC62D91EB, "m_source", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_source;

        [STUField(0xE3798C00, "m_targets", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_targets;
    }
}
