// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xEACF8DFB)]
    public class STU_EACF8DFB : STUStatescriptAction {
        [STUField(0xD7DDEEAD, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_D7DDEEAD;
    }
}
