// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0xBDE6CC74)]
    public class STU_BDE6CC74 : STU_8C127DE2 {
        [STUField(0xD98CB73A)]
        public Enum_499AD032 m_D98CB73A;

        [STUField(0xBA891264, "m_dataFlow", ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_25B808BD m_dataFlow;

        [STUField(0xE3BC608F, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_25B808BD m_E3BC608F;
    }
}
