// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xD137ECA0)]
    public class STU_D137ECA0 : STUStatescriptAction {
        [STUField(0x08FBE734, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_08FBE734;

        [STUField(0xD10618D1, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_D10618D1;

        [STUField(0x592D15F7, "m_out_Var", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_out_Var;

        [STUField(0x07DD813E, "m_value", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_value;
    }
}
