// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xB5C87F3D)]
    public class STU_B5C87F3D : STUStatescriptState {
        [STUField(0x4F5799DC, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_4F5799DC;

        [STUField(0xA5A7B92D, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_A5A7B92D;

        [STUField(0xC33731A1, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_C33731A1;

        [STUField(0x9352A840, "m_direction", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_direction;

        [STUField(0x7DC1550F, "m_position", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_position;

        [STUField(0xED61D926, "m_radius", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_radius;
    }
}
