// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x0A9228FE)]
    public class STU_0A9228FE : STUInstance {
        [STUField(0x310C605F)]
        public teStructuredDataAssetRef<STU_FA258ECC> m_310C605F;

        [STUField(0x64F87F5E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_64F87F5E;
    }
}
