// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x919D4DC2)]
    public class STU_919D4DC2 : STU_8C127DE2 {
        [STUField(0x33DCB4EB, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_15EF3A7E m_33DCB4EB;

        [STUField(0x7C9BE696)]
        public byte m_7C9BE696;

        [STUField(0xB4FF0E2F, "m_animAlias", ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_C6AA0CA6 m_animAlias;

        [STUField(0xBA891264, "m_dataFlow", ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_25B808BD m_dataFlow;
    }
}
