// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x1FC87C63)]
    public class STU_1FC87C63 : STU_9631AFC2 {
        [STUField(0x29E5D256)]
        public uint m_29E5D256;

        [STUField(0x3C10EC10)]
        public int m_3C10EC10;

        [STUField(0x9307BB84)]
        public uint m_9307BB84;

        [STUField(0x9BAF78C1)]
        public int m_9BAF78C1;

        [STUField(0xCCF5DD1E)]
        public int m_CCF5DD1E;
    }
}
