// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x474242FA)]
    public class STU_474242FA : STUStatescriptState {
        [STUField(0x558DA6B9)]
        public float m_558DA6B9;
    }
}
