// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x1B5A1F34)]
    public class STU_1B5A1F34 : STUConfigVarBoolBase {
        [STUField(0x28421180, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_28421180;

        [STUField(0x316BC6EF, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_316BC6EF;

        [STUField(0x392D54A6, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_392D54A6;

        [STUField(0x40A70CEE, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_40A70CEE;

        [STUField(0xBD2A95EE, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_BD2A95EE;

        [STUField(0xBD64288B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_BD64288B;

        [STUField(0xECA59BFE, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_ECA59BFE;
    }
}
