// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x6C945453)]
    public class STU_6C945453 : STUStatescriptState {
        [STUField(0x2334A7D6, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_2334A7D6;

        [STUField(0x41F6368D, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_41F6368D;

        [STUField(0x9613163D, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_904BFCEC m_9613163D;

        [STUField(0x4E87690F, "m_map", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_map;
    }
}
