// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0xCB9DED16)]
    public class STU_CB9DED16 : STUConfigVarIntBase {
        [STUField(0x96A05257)]
        public Enum_0A6975F1 m_96A05257;
    }
}
