// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x9726FFB4)]
    public class STU_9726FFB4 : STUStatescriptAction {
        [STUField(0x1A69E234, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_1A69E234;

        [STUField(0x52901F5C, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_52901F5C;

        [STUField(0x80939361, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_80939361;

        [STUField(0x85B247CB, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_85B247CB;

        [STUField(0x88225CDF, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_88225CDF;

        [STUField(0x9B6EE8FC, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_9B6EE8FC;

        [STUField(0xB337A52B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_B337A52B;

        [STUField(0xD115A49D, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_D115A49D;

        [STUField(0xE217A77C, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_E217A77C;

        [STUField(0xE476952B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_E476952B;

        [STUField(0xE59E8B10, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_E59E8B10;

        [STUField(0xFB31AD62, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_FB31AD62;

        [STUField(0xFC1AFF3E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_FC1AFF3E;
    }
}
