// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x1AC9AD09)]
    public class STU_1AC9AD09 : STUInstance {
        [STUField(0x1C8AB680)]
        public float m_1C8AB680;

        [STUField(0xB93FC63C)]
        public float m_B93FC63C;

        [STUField(0xD5BD125F)]
        public byte m_D5BD125F;

        [STUField(0xF59C2982)]
        public float m_F59C2982;

        [STUField(0xFDE9FD5F)]
        public float m_FDE9FD5F;
    }
}
