// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x63D9B81B)]
    public class STU_63D9B81B : STUConfigVarBoolBase {
        [STUField(0x152B6961, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_152B6961;

        [STUField(0x36A65239, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_36A65239;

        [STUField(0x8A12D912, "m_target", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_target;
    }
}
