// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0x5EAA04BB)]
    public class STU_5EAA04BB : STUStatescriptAction {
        [STUField(0x15C19570, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_15C19570;

        [STUField(0xD11CBE74)]
        public Enum_2CFF77C1 m_D11CBE74;

        [STUField(0x92A85396, "m_gameMessage", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_gameMessage;

        [STUField(0xBC2A8DA3, "m_params", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_814D595E[] m_params;

        [STUField(0x4D5597A8, "m_script", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_script;
    }
}
