// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x3BA235C0)]
    public class STU_3BA235C0 : STU_81C5DE19 {
        [STUField(0x1A43B699, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_A8EFC6F0 m_1A43B699;

        [STUField(0xAEDA14F2, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_A8EFC6F0 m_AEDA14F2;

        [STUField(0x45A7A69C, "m_default", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_A8EFC6F0 m_default;

        [STUField(0xEC6FE809, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_A8EFC6F0 m_EC6FE809;

        [STUField(0xF891229F, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_C8C03F04 m_F891229F;

        [STUField(0xFBFFD5F6, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_A8EFC6F0 m_FBFFD5F6;
    }
}
