// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xA66D3CC8)]
    public class STU_A66D3CC8 : STUConfigVarResource {
        [STUField(0xC9AD5769, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_C9AD5769;
    }
}
