// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x3E5D9838)]
    public class STU_3E5D9838 : STUStatescriptAction {
        [STUField(0x31714AFC, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_31714AFC;

        [STUField(0xAA8E1BB0, "m_targetTags", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_targetTags;
    }
}
