// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x0CFE9EB6)]
    public class STU_0CFE9EB6 : STUInstance {
        [STUField(0xBAA74493, "m_condition", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_111A6193[] m_condition;
    }
}
