// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0x1198EF21)]
    public class STU_1198EF21 : STUConfigVar {
        [STUField(0x2F709539, "m_key")]
        public Enum_C3BB057D m_key;
    }
}
