// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x98C7D67E)]
    public class STU_98C7D67E : STUStatescriptState {
        [STUField(0x26E3B366, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_26E3B366;

        [STUField(0x2F709539, "m_key", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_key;
    }
}
