// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xC0B05866)]
    public class STU_C0B05866 : STUInstance {
        [STUField(0x17E5AFB0, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_F1306D2B m_17E5AFB0;

        [STUField(0x24BA1E47, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_04DACD69 m_24BA1E47;
    }
}
