// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x75BCC7F3)]
    public class STU_75BCC7F3 : STUStatescriptState {
        [STUField(0x10195323, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_10195323;

        [STUField(0x24C2DF33, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_24C2DF33;

        [STUField(0x3763D558, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_3763D558;

        [STUField(0x481B15D1, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_481B15D1;

        [STUField(0x62635351, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_62635351;

        [STUField(0x6D9A5F79, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_6D9A5F79;

        [STUField(0x7187A13E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_7187A13E;

        [STUField(0xA14565AD, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_A14565AD;

        [STUField(0xE146FF03, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_E146FF03;

        [STUField(0xE3C105D3, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_E3C105D3;
    }
}
