// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0xB2C8F9FC)]
    public class STU_B2C8F9FC : STUConfigVarVecBase {
        [STUField(0x35F14EF6, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_35F14EF6;

        [STUField(0x485109CB, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_485109CB;

        [STUField(0x5EC107A5, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_5EC107A5;

        [STUField(0x9524A8D6, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_9524A8D6;

        [STUField(0xA2D13D1C)]
        public Enum_440F623B m_A2D13D1C;

        [STUField(0xA7B12CE0, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_A7B12CE0;

        [STUField(0xF9E1E835, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_F9E1E835;
    }
}
