// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xB5621AA7)]
    public class STU_B5621AA7 : STUInstance {
        [STUField(0x5DC61E59)]
        public teStructuredDataAssetRef<STU_2B8093CD> m_5DC61E59;

        [STUField(0x9CDDC24D, "m_weight")]
        public int m_weight;
    }
}
