// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x3FAB2324)]
    public class STU_3FAB2324 : STU_EF734202 {
        [STUField(0x39C08664)]
        public float m_39C08664;

        [STUField(0x57FDDE29)]
        public byte m_57FDDE29;

        [STUField(0xB683930D)]
        public teStructuredDataAssetRef<STUAnimCategory> m_B683930D;
    }
}
