// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xD4E8A23B)]
    public class STU_D4E8A23B : STU_311AE098 {
        [STUField(0xF1C1F010)]
        public float m_F1C1F010;
    }
}
