// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x61A308F3)]
    public class STU_61A308F3 : STU_11E07FD7 {
        [STUField(0x08490493, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_D5E7FD6F m_08490493;

        [STUField(0x18C844D3, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_5FF2A50C m_18C844D3;

        [STUField(0x203C271E, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_5FF2A50C m_203C271E;

        [STUField(0x377CD4E6, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_377CD4E6;

        [STUField(0x37EE887D, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_5FF2A50C m_37EE887D;

        [STUField(0x3C202382, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_3C202382;

        [STUField(0x4A0C8DB0, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_4A0C8DB0;

        [STUField(0x57901A69, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_5FF2A50C m_57901A69;

        [STUField(0x6DD299EE, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_5B9E59A5 m_6DD299EE;

        [STUField(0x723FF819, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_5FF2A50C m_723FF819;

        [STUField(0x761DACB5, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_D5E7FD6F m_761DACB5;

        [STUField(0x99A6E88B, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_5FF2A50C m_99A6E88B;

        [STUField(0x9A475245, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_D5E7FD6F m_9A475245;

        [STUField(0xAFA5D917, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_5FF2A50C m_AFA5D917;

        [STUField(0xB5C84B6C, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_5FF2A50C m_B5C84B6C;

        [STUField(0xBAD85273, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_5FF2A50C m_BAD85273;

        [STUField(0xC826C91D, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_5FF2A50C m_C826C91D;

        [STUField(0xCE925D7C, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_5FF2A50C m_CE925D7C;

        [STUField(0xE8C309DB, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_E8C309DB;
    }
}
