// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x69E78632)]
    public class STU_69E78632 : STU_C7C085F6 {
        [STUField(0x067A516F)]
        public teStructuredDataAssetRef<STUAnimation> m_067A516F;

        [STUField(0x11012D0E)]
        public byte m_11012D0E;

        [STUField(0x28479F36)]
        public float m_28479F36;

        [STUField(0x2FBD6CBA)]
        public byte m_2FBD6CBA;

        [STUField(0x37EE887D)]
        public byte m_37EE887D;

        [STUField(0x3D90A5A2)]
        public float m_3D90A5A2;

        [STUField(0x69E153CE)]
        public float m_69E153CE;

        [STUField(0x83CE3EB5)]
        public float m_83CE3EB5;

        [STUField(0x9303291F)]
        public teStructuredDataAssetRef<STUAnimation> m_9303291F;

        [STUField(0x9ECA41E6)]
        public teStructuredDataAssetRef<STUAnimation> m_9ECA41E6;

        [STUField(0xABF34EEF)]
        public float m_ABF34EEF;

        [STUField(0xE8502460)]
        public float m_E8502460;

        [STUField(0xEC4CAE23)]
        public teStructuredDataAssetRef<STUDataFlow> m_EC4CAE23;

        [STUField(0xF074F97F)]
        public teStructuredDataAssetRef<STUDataFlow> m_F074F97F;

        [STUField(0xF0E4656D, "m_globalLayerMultipliers", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimGlobalLayerMultipliers m_globalLayerMultipliers;

        [STUField(0x5620DA50, "m_globalWeightMultipliers", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimGlobalWeightMultipliers m_globalWeightMultipliers;

        [STUField(0xEC42051A, "m_userWeights", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimUserWeights m_userWeights;
    }
}
