// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x6796C7C3)]
    public class STU_6796C7C3 : STU_58AA5AF4 {
        [STUField(0xC8B9BBD1, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_8FA1A303 m_C8B9BBD1;
    }
}
