// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x4A7A3740)]
    public class STU_4A7A3740 : STUCriteria {
        [STUField(0xEB4F2408, "m_gamemode")]
        public teStructuredDataAssetRef<STUGameMode> m_gamemode;
    }
}
