// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0xBEE7F20E)]
    public class STU_BEE7F20E : STUInstance {
        [STUField(0x37D4F9CD)]
        public int m_37D4F9CD;

        [STUField(0x9031A609)]
        public teStructuredDataAssetRef<STUUXDisplayText> m_9031A609;

        [STUField(0x2C54AEAF, "m_category")]
        public Enum_19FE2EB5 m_category;

        [STUField(0x11B47C68, "m_id")]
        public teStructuredDataAssetRef<STUIdentifier> m_id;

        [STUField(0xB48F1D22, "m_name")]
        public teStructuredDataAssetRef<STUUXDisplayText> m_name;
    }
}
