// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x8CE91499)]
    public class STU_8CE91499 : STUConfigVarBoolBase {
        [STUField(0x18D94B00, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_18D94B00;

        [STUField(0xC0A83121, "m_skin", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_skin;
    }
}
