// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x91121C01)]
    public class STU_91121C01 : STUStatescriptState {
        [STUField(0x0A7A0E8E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_0A7A0E8E;

        [STUField(0x160B5DBE, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_160B5DBE;

        [STUField(0x5ED803CF, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_5ED803CF;

        [STUField(0xF5488957, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_F5488957;
    }
}
