// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xD64C5581)]
    public class STU_D64C5581 : STU_79862BCB {
        [STUField(0x44A87E16, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_44A87E16;

        [STUField(0x554523AD, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_554523AD;

        [STUField(0x71DBDBE0, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_71DBDBE0;

        [STUField(0x976DCF23, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_976DCF23;
    }
}
