// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x7EF21B28)]
    public class STU_7EF21B28 : STUInstance {
        [STUField(0x241EA176)]
        public ushort m_241EA176;

        [STUField(0x291F2404)]
        public long m_291F2404;

        [STUField(0x7A5EB318)]
        public teString m_7A5EB318;

        [STUField(0x7DC75216)]
        public ushort m_7DC75216;
    }
}
