// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x9E9028E6)]
    public class STU_9E9028E6 : STU_1F8FAD25 {
        [STUField(0x6A79BD98, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_6A79BD98;

        [STUField(0x9352A840, "m_direction", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_direction;
    }
}
