// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x762DF755)]
    public class STU_762DF755 : STUStatescriptState {
        [STUField(0x09261671, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_09261671;
    }
}
