// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x7DFB5A54)]
    public class STU_7DFB5A54 : STU_79862BCB {
        [STUField(0x554523AD, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_554523AD;

        [STUField(0x653B5C29, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_653B5C29;

        [STUField(0x71DBDBE0, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_71DBDBE0;

        [STUField(0x976DCF23, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_976DCF23;
    }
}
