// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x904BFCEC)]
    public class STU_904BFCEC : STUStatescriptOutputPlug {
        [STUField(0xFF3DAF1E)]
        public int[] m_FF3DAF1E;
    }
}
