// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x601E7678)]
    public class STU_601E7678 : STUInstance {
        [STUField(0xD10618D1)]
        public int m_D10618D1;

        [STUField(0xF5087894, "m_unlock")]
        public teStructuredDataAssetRef<STUUnlock> m_unlock;
    }
}
