// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x0BFE7E4D)]
    public class STU_0BFE7E4D : STUConfigVarBoolBase {
        [STUField(0x38BFB46C, "m_resourceKey", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_resourceKey;
    }
}
