// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x8B88FA60)]
    public class STU_8B88FA60 : STUConfigVarResource {
        [STUField(0x1B25AB90, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_1B25AB90;
    }
}
