// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xE3BA95E9)]
    public class STU_E3BA95E9 : STU_C7C085F6 {
        [STUField(0x703104E9)]
        public float m_703104E9;

        [STUField(0x76480DA8)]
        public float m_76480DA8;

        [STUField(0x8A7DF36E)]
        public float m_8A7DF36E;

        [STUField(0xBECEB12A)]
        public float m_BECEB12A;

        [STUField(0xDF265AD5)]
        public float m_DF265AD5;

        [STUField(0xE12F90B9)]
        public float m_E12F90B9;
    }
}
