// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0xBA7BF306)]
    public class STU_BA7BF306 : STU_05BDD390 {
        [STUField(0x169B9489)]
        public int m_169B9489;

        [STUField(0x3A8E6AFA)]
        public float m_3A8E6AFA;

        [STUField(0x72440DB6)]
        public teVec3 m_72440DB6;

        [STUField(0x77E7291B)]
        public teColorRGB m_77E7291B;

        [STUField(0xA1F0D518)]
        public int m_A1F0D518;

        [STUField(0xEDEA12FF)]
        public teColorRGB m_EDEA12FF;
    }
}
