// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0x0340770E)]
    public class STU_0340770E : STU_3660CDED {
        [STUField(0x3FAFF222)]
        public Enum_ADA71829 m_3FAFF222;
    }
}
