// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xBD7E14CE)]
    public class STU_BD7E14CE : STUStatescriptState {
        [STUField(0x046E9E4E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_046E9E4E;
    }
}
