// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xF1635DF7)]
    public class STU_F1635DF7 : STU_B28C2E5E {
        [STUField(0x4D9B897F, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_4D9B897F;

        [STUField(0xE75D5CB9, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_E75D5CB9;
    }
}
