// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xCA6C9BEB)]
    public class STU_CA6C9BEB : STUStatescriptState {
        [STUField(0x00B16A0B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_00B16A0B;

        [STUField(0x44BE1B2F, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_44BE1B2F;

        [STUField(0x61D67634, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_61D67634;

        [STUField(0x719CC4B4, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_719CC4B4;

        [STUField(0x7D1E621B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_904BFCEC m_7D1E621B;

        [STUField(0xC8DD44D8, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_C8DD44D8;

        [STUField(0xDF9E590C, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_DF9E590C;

        [STUField(0xEBB77882, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_E56CFA7B m_EBB77882;
    }
}
