// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x8A6CFAD9)]
    public class STU_8A6CFAD9 : STUUXViewModel {
        [STUField(0x5DD15354)]
        public ulong m_5DD15354;

        [STUField(0xABEBA68A)]
        public ulong m_ABEBA68A;
    }
}
