// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xEC666059)]
    public class STU_EC666059 : STU_81C5DE19 {
        [STUField(0x4376ACB9, "m_additiveFiring", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_A8EFC6F0 m_additiveFiring;

        [STUField(0xF01470D0, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_A8EFC6F0 m_F01470D0;

        [STUField(0xF891229F, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_66F2015C m_F891229F;

        [STUField(0x5F150DBC, "m_jump", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_A8EFC6F0 m_jump;
    }
}
