// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x23D45B2A)]
    public class STU_23D45B2A : STUUXDependencyObject {
        [STUField(0xADE95629, "m_items", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_949E1F48[] m_items;
    }
}
