// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x19A5A181)]
    public class STU_19A5A181 : STU_81C5DE19 {
        [STUField(0xF891229F, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_E3F889EE m_F891229F;
    }
}
