// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x4978E1A3)]
    public class STU_4978E1A3 : STU_DB72CA9C {
        [STUField(0x109396D8, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_F7E4CDAC m_109396D8;

        [STUField(0x868A1EC8, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_51A9D9C7 m_868A1EC8;

        [STUField(0xD914F27C, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_ABD8FE73 m_D914F27C;

        [STUField(0xE1D6C91B, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_ABD8FE73 m_E1D6C91B;
    }
}
