// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x07CCF674)]
    public class STU_07CCF674 : STUConfigVarIntBase {
        [STUField(0x78A08312, "m_string", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_string;
    }
}
