// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xBDB687C1)]
    public class STU_BDB687C1 : STUInstance {
        [STUField(0x4C0A85CC)]
        public float m_4C0A85CC;

        [STUField(0x90040B40)]
        public float m_90040B40;
    }
}
