// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xF746901F)]
    public class STU_F746901F : STUInstance {
        [STUField(0x1485B834, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_D744301C m_1485B834;

        [STUField(0x5683B253, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_4493ED2C[] m_5683B253;

        [STUField(0x798027DE, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_D744301C m_798027DE;

        [STUField(0xA84AA2B5, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_D744301C m_A84AA2B5;

        [STUField(0xD872E45C, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_D744301C m_D872E45C;
    }
}
