// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x815DA879)]
    public class STU_815DA879 : STU_319619ED {
        [STUField(0xE41699C9, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_E41699C9;
    }
}
