// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0x22A375E4)]
    public class STU_22A375E4 : STU_9881546F {
        [STUField(0x0EC67F50)]
        public teVec2[] m_0EC67F50;

        [STUField(0x540E2FC8)]
        public byte[] m_540E2FC8;

        [STUField(0x5E009A60)]
        public byte m_5E009A60;

        [STUField(0x8D244EC2, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimGameData_BlendDriver m_8D244EC2;

        [STUField(0xF0CF068D, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimGameData_BlendDriver m_F0CF068D;
    }
}
