// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x545AB3B8)]
    public class STU_545AB3B8 : STUStatescriptAction {
        [STUField(0x0B897113, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_0B897113;

        [STUField(0xC68C8155, "m_loadout", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_loadout;

        [STUField(0x8A12D912, "m_target", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_target;
    }
}
