// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x0BD5EA17, "STUAnimBoneSet")]
    public class STUAnimBoneSet : STUInstance {
        [STUField(0x50558D63, "m_bones")]
        public teStructuredDataAssetRef<STUBoneLabel>[] m_bones;

        [STUField(0x7CBECA0C, "m_hardPoints")]
        public teStructuredDataAssetRef<STUHardPoint>[] m_hardPoints;
    }
}
