// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x0B08FAD5, "STUAnimConfigRandomAnimation")]
    public class STUAnimConfigRandomAnimation : STUInstance {
        [STUField(0x452D0972)]
        public float m_452D0972;

        [STUField(0xAFC41FBA)]
        public float m_AFC41FBA;

        [STUField(0x3F5B86A4, "m_animation")]
        public teStructuredDataAssetRef<STUAnimation> m_animation;
    }
}
