// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xB89B3EF9, "STUAnimNode_ToTargetDirectionIK")]
    public class STUAnimNode_ToTargetDirectionIK : STUAnimNode_Base {
        [STUField(0x4ABE6B19, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimBlendDriverParam m_4ABE6B19;

        [STUField(0x8096CD9B, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimBlendDriverParam m_8096CD9B;

        [STUField(0xAB06D14B, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimConfigBoneWeight_Item[] m_AB06D14B;

        [STUField(0xCC95F1B0, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_5861C542 m_CC95F1B0;

        [STUField(0x436BEFE6, "m_child", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_2F6BD485 m_child;

        [STUField(0xE33AA964, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_ABD8FE73 m_E33AA964;

        [STUField(0xC15DCB47, "m_IKItems", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimNode_ToTargetDirectionIKItem[] m_IKItems;

        [STUField(0x0F88291F, "m_weightDriver", ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_25B808BD m_weightDriver;
    }
}
