// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x19354E9E, "STUAnimGlobalLayerMultipliers")]
    public class STUAnimGlobalLayerMultipliers : STUInstance {
        [STUField(0x89E1564D)]
        public float m_89E1564D;

        [STUField(0xAA38C74B)]
        public float m_AA38C74B;
    }
}
