// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x70BFB706, "STUAnimBoneWeightMask_Item")]
    public class STUAnimBoneWeightMask_Item : STUInstance {
        [STUField(0xA08C6C1C)]
        public byte m_A08C6C1C;

        [STUField(0xF97609C8, "m_bone")]
        public teStructuredDataAssetRef<STUBoneLabel> m_bone;

        [STUField(0xC7E4EB10)]
        public byte m_C7E4EB10;

        [STUField(0x9CDDC24D, "m_weight")]
        public float m_weight;
    }
}
