// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0xCB6035BA, "STUAnimNode_Animation")]
    public class STUAnimNode_Animation : STUAnimNode_Base {
        [STUField(0x11012D0E, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_15EF3A7E m_11012D0E;

        [STUField(0x29AFF063, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_5861C542 m_29AFF063;

        [STUField(0x302DAC17, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_15EF3A7E m_302DAC17;

        [STUField(0x3E3C159E, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_15EF3A7E m_3E3C159E;

        [STUField(0x562445C2, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_51A9D9C7 m_562445C2;

        [STUField(0x73038249, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_15EF3A7E m_73038249;

        [STUField(0x881F239A, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_B9FE55F9 m_881F239A;

        [STUField(0x8A0E5071, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_ABD8FE73 m_8A0E5071;

        [STUField(0x9317B197, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_ABD8FE73 m_9317B197;

        [STUField(0xA3081C7F, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_15EF3A7E m_A3081C7F;

        [STUField(0x3F5B86A4, "m_animation", ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_215BE8F3 m_animation;

        [STUField(0x65033558, "m_animSlotID", ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_C1C7CF4E m_animSlotID;

        [STUField(0xC14EEC71, "m_animTrackOverrides", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimNode_AnimationTrackOverride[] m_animTrackOverrides;

        [STUField(0xB774CFA6)]
        public Enum_9250F4C2 m_B774CFA6;

        [STUField(0xBCC400FE, "m_disableEffect", ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_15EF3A7E m_disableEffect;

        [STUField(0xE382431C, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_F7E4CDAC m_E382431C;

        [STUField(0xED247E81, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_25B808BD m_ED247E81;

        [STUField(0xEE49D811, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_ABD8FE73 m_EE49D811;

        [STUField(0xC4EF5D15, "m_synchGroup", ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_51A9D9C7 m_synchGroup;
    }
}
