// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x65436ABC, "STUAnimBlendTree_PlayAnimCancelCategory")]
    public class STUAnimBlendTree_PlayAnimCancelCategory : STUInstance {
        [STUField(0xB1F28FCA)]
        public byte m_B1F28FCA;

        [STUField(0x2C54AEAF, "m_category")]
        public teStructuredDataAssetRef<STUAnimCategory> m_category;
    }
}
