// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x22BD6AAD, "STUBreakable")]
    public class STUBreakable : STUInstance {
        [STUField(0xA4E3DBA5, "m_zones", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_1C4922D4[] m_zones;
    }
}
