// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0xE5C38E9F, "STUConfigVarVec2")]
    public class STUConfigVarVec2 : STUConfigVarVecBase {
        [STUField(0x07DD813E, "m_value")]
        public teVec2 m_value;
    }
}
