// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x54FD3952, "STUConfigVarEntityID")]
    public class STUConfigVarEntityID : STUConfigVar { }
}
