// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x01676947, "STUConfigVarAnimAlias")]
    public class STUConfigVarAnimAlias : STU_2682C260 {
        [STUField(0xB4FF0E2F, "m_animAlias")]
        public teStructuredDataAssetRef<ulong> m_animAlias;
    }
}
