// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xB70590E4, "STUCaptureAreaComponent")]
    public class STUCaptureAreaComponent : STUMirroredEntityComponent {
        [STUField(0x27410361)]
        public float m_27410361;

        [STUField(0x1CB29B8C, "m_residencyMultipliers", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUCaptureAreaResidencyMultiplier[] m_residencyMultipliers;

        [STUField(0x9472AB02, "m_segments", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUCaptureAreaSegment[] m_segments;
    }
}
