// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0xC1A2DB26, "STUCriteriaContainer")]
    public class STUCriteriaContainer : STUInstance {
        [STUField(0x967A138B)]
        public Enum_AB6CE3D1 m_967A138B;

        [STUField(0xA20DCD80)]
        public ulong m_A20DCD80;

        [STUField(0x0619C597, "m_type")]
        public Enum_9EAD8C06 m_type;
    }
}
