// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0xBDD783B9, "STUCriteria_Team")]
    public class STUCriteria_Team : STUCriteria {
        [STUField(0xEB5492C4)]
        public byte m_EB5492C4;

        [STUField(0x33B0B2B6, "m_team")]
        public TeamIndex m_team;
    }
}
