// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x17E6DDEB, "STUConfigVarExpressionFragment")]
    public class STUConfigVarExpressionFragment : STUInstance {
        [STUField(0xBA53D5ED, "m_guid")]
        public teStructuredDataAssetRef<STUIdentifier> m_guid;

        [STUField(0xF1CB3BA0, "m_text")]
        public teString m_text;
    }
}
