// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xFB366254, "STUConfigVarTexture")]
    public class STUConfigVarTexture : STU_E4324757 {
        [STUField(0x3CD6DC1E, "m_texture")]
        public teStructuredDataAssetRef<ulong> m_texture;
    }
}
