// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0x2F33B1B7, "STUCriteria")]
    public class STUCriteria : STUInstance {
        [STUField(0x07D0F7AA)]
        public int m_07D0F7AA;

        [STUField(0x967A138B)]
        public Enum_AB6CE3D1 m_967A138B;

        [STUField(0xA20DCD80)]
        public ulong m_A20DCD80;

        [STUField(0x0619C597, "m_type")]
        public STUCriteriaType m_type;
    }
}
