// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xF5B49504, "STUCustomGameBrowserMapCatalogInfo")]
    public class STUCustomGameBrowserMapCatalogInfo : STUInstance {
        [STUField(0x2C05CD95, "m_catalog")]
        public teStructuredDataAssetRef<STUMapCatalog> m_catalog;

        [STUField(0xB48F1D22, "m_name")]
        public teStructuredDataAssetRef<ulong> m_name;
    }
}
