// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0xBF0D20BE, "STUDataFlowType_ColorRGBA")]
    public class STUDataFlowType_ColorRGBA : STUDataFlowType {
        [STUField(0x45A7A69C, "m_default")]
        public teColorRGBA m_default;
    }
}
