// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xEADA21EC, "STUHeroSettingBool")]
    public class STUHeroSettingBool : STUHeroSettingBase {
        [STUField(0x45A7A69C, "m_default")]
        public byte m_default;
    }
}
