// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xF2646A89, "STUHeroWeapon")]
    public class STUHeroWeapon : STUSkinBase {
        [STUField(0xA5C9CA02, "m_internalName")]
        public teString m_internalName;
    }
}
