// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0x9FFCF237, "STULootBoxCurrencyRarityUnlock")]
    public class STULootBoxCurrencyRarityUnlock : STUInstance {
        [STUField(0xBB99FCD3, "m_rarity")]
        public STUUnlockRarity m_rarity;

        [STUField(0xF5087894, "m_unlock")]
        public teStructuredDataAssetRef<STUUnlock> m_unlock;
    }
}
