// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x6CBC2E3F, "STULootBoxCelebrationOverride")]
    public class STULootBoxCelebrationOverride : STUInstance {
        [STUField(0xED999C8B, "m_celebrationType")]
        public teStructuredDataAssetRef<STUIdentifier> m_celebrationType;

        [STUField(0xB0EDB99C, "m_lootbox")]
        public teStructuredDataAssetRef<STUUnlock> m_lootbox;
    }
}
