// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x25DA0DF5, "STUMapCatalog")]
    public class STUMapCatalog : STUInstance {
        [STUField(0x669A4581, "m_headerGUIDs")]
        public ulong[] m_headerGUIDs;

        [STUField(0x242E748D, "m_mapGUIDs")]
        public ulong[] m_mapGUIDs;
    }
}
