// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0xC18DC9CD, "STUMapLayer")]
    public class STUMapLayer : STUInstance {
        [STUField(0x175A70AB)]
        public byte m_175A70AB;

        [STUField(0x1A37A8D5)]
        public teStructuredDataAssetRef<STUMapLayer>[] m_1A37A8D5;

        [STUField(0x3400CBD2)]
        public teStructuredDataAssetRef<STUIdentifier> m_3400CBD2;

        [STUField(0x5A60C16E)]
        public byte m_5A60C16E;

        [STUField(0x62B0C83F)]
        public teVec3 m_62B0C83F;

        [STUField(0xA8F4AE5B)]
        public teStructuredDataAssetRef<STUIdentifier> m_A8F4AE5B;

        [STUField(0xBA93D5FE)]
        public teVec3 m_BA93D5FE;

        [STUField(0xC813DA9D)]
        public byte m_C813DA9D;

        [STUField(0xD2464EEA)]
        public teStructuredDataAssetRef<STUMapLayer>[] m_D2464EEA;
    }
}
