// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x3726ACFD, "STUOutlineComponent")]
    public class STUOutlineComponent : STUEntityComponent {
        [STUField(0x338BF6B4)]
        public float m_338BF6B4;

        [STUField(0x74B34A5B)]
        public byte m_74B34A5B;

        [STUField(0xBB1E23FD)]
        public float m_BB1E23FD;
    }
}
