// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0x003C517B, "STUPlaybackProperties")]
    public class STUPlaybackProperties : STUInstance {
        [STUField(0x0AABC91F)]
        public byte m_0AABC91F;

        [STUField(0x14A22FA7)]
        public byte m_14A22FA7;

        [STUField(0x1AD9EC4A)]
        public byte m_1AD9EC4A;

        [STUField(0x1CC5EF25)]
        public float m_1CC5EF25;

        [STUField(0x252D7B29)]
        public byte m_252D7B29;

        [STUField(0x345921CC)]
        public byte m_345921CC;

        [STUField(0x5D07FCC3)]
        public byte m_5D07FCC3;

        [STUField(0x72AA9E92)]
        public byte m_72AA9E92;

        [STUField(0xA73F2EBE)]
        public float m_A73F2EBE;

        [STUField(0xA9A901C1)]
        public byte m_A9A901C1;

        [STUField(0xAFCF2626)]
        public byte m_AFCF2626;

        [STUField(0x2C54AEAF, "m_category")]
        public teStructuredDataAssetRef<STUVoiceCategory> m_category;

        [STUField(0xD7FE39AA)]
        public byte m_D7FE39AA;

        [STUField(0xDD27AC95)]
        public float m_DD27AC95;

        [STUField(0xDF647B95)]
        public Enum_BC00E017 m_DF647B95;

        [STUField(0xEE144B9E)]
        public byte m_EE144B9E;

        [STUField(0x35EC21DC, "m_interrupt")]
        public Enum_4368B765 m_interrupt;

        [STUField(0xF6658B6B, "m_loadData")]
        public Enum_A3FB08F9 m_loadData;

        [STUField(0xBB16810A, "m_priority")]
        public uint m_priority;

        [STUField(0xED61D926, "m_radius")]
        public float m_radius;

        [STUField(0xB1C6CDA2, "m_volume")]
        public float m_volume;
    }
}
