// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x8CE1D110, "STUProgressionUnlocks")]
    public class STUProgressionUnlocks : STUInstance {
        [STUField(0x7846C401, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_1757E817[] m_7846C401;

        [STUField(0x9135A4B2, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUUnlocks m_9135A4B2;

        [STUField(0x473494FF, "m_lootBoxesUnlocks", ReaderType = typeof(InlineInstanceFieldReader))]
        public STULootBoxUnlocks[] m_lootBoxesUnlocks;

        [STUField(0xBF482AA3, "m_otherUnlocks", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUUnlocks m_otherUnlocks;
    }
}
