// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x60090FCE, "STUStatescriptWeaponProjectileExplosionRing")]
    public class STUStatescriptWeaponProjectileExplosionRing : STUInstance {
        [STUField(0xB399CACB, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_B399CACB;

        [STUField(0xED61D926, "m_radius", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_radius;
    }
}
