// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x5981B16B, "STUStatescriptSchema")]
    public class STUStatescriptSchema : STUInstance {
        [STUField(0x16B4863C, "m_entries", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptSchemaEntry[] m_entries;
    }
}
