// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0x04118DBD, "STUSound")]
    public class STUSound : STUInstance {
        [STUField(0x13523278)]
        public float m_13523278;

        [STUField(0x166243EC)]
        public byte m_166243EC;

        [STUField(0x42809FC5)]
        public teStructuredDataAssetRef<STUSound> m_42809FC5;

        [STUField(0x43F0D346)]
        public Enum_D2BF23BC m_43F0D346;

        [STUField(0x6657412F)]
        public uint m_6657412F;

        [STUField(0x66AD5CBC)]
        public float m_66AD5CBC;

        [STUField(0x77092FDD)]
        public byte m_77092FDD;

        [STUField(0xACA7FBC8)]
        public float m_ACA7FBC8;

        [STUField(0xB62657B8)]
        public byte m_B62657B8;

        [STUField(0xBEB35A19)]
        public float m_BEB35A19;

        [STUField(0xC32C2195, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_0FA0034C m_C32C2195;

        [STUField(0xD138B819)]
        public float m_D138B819;

        [STUField(0xEF90634C)]
        public uint m_EF90634C;
    }
}
