// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xFC999513, "STUStatescriptStateGroup")]
    public class STUStatescriptStateGroup : STUInstance { }
}
