// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x91428992, "STUStatescriptStateHero")]
    public class STUStatescriptStateHero : STUStatescriptState {
        [STUField(0x16432044, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_16432044;

        [STUField(0x6447237A, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_6447237A;

        [STUField(0x731EB603, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_731EB603;

        [STUField(0x176ED263, "m_controller", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_controller;

        [STUField(0x37AB13D3, "m_hero", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_hero;
    }
}
