// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xB480A974, "STUStatescriptStateLogicalButton")]
    public class STUStatescriptStateLogicalButton : STUStatescriptState {
        [STUField(0x0B2D5F2F, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_0B2D5F2F;

        [STUField(0x1C9EF058, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_904BFCEC m_1C9EF058;

        [STUField(0x246438AD, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_246438AD;

        [STUField(0x4B925089, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_4B925089;

        [STUField(0x53C4B6A6, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_53C4B6A6;

        [STUField(0x5AE05408, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_5AE05408;

        [STUField(0x80AF45FB, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_904BFCEC m_80AF45FB;

        [STUField(0xFC33191B, "m_logicalButton", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_logicalButton;

        [STUField(0xA36EEE40, "m_onComingUpPlug", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_onComingUpPlug;

        [STUField(0x133B14AC, "m_onGoingDownPlug", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_onGoingDownPlug;
    }
}
