// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x3E88143F, "STUSkinRuntimeOverride")]
    public class STUSkinRuntimeOverride : STUInstance {
        [STUField(0x3D884507)]
        public ulong m_3D884507;

        [STUField(0xDA71BEFE)]
        public byte m_DA71BEFE;
    }
}
