// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x268E773B, "STUStatescriptInputPlug")]
    public class STUStatescriptInputPlug : STUGraphPlug { }
}
