// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x142A27A8, "STUStatescriptCondition")]
    public class STUStatescriptCondition : STUStatescriptBase {
        [STUField(0xA4975E0A, "m_falsePlug", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_falsePlug;

        [STUField(0x54653E9B, "m_inPlug", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptInputPlug m_inPlug;

        [STUField(0x5FB4504B, "m_truePlug", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_truePlug;
    }
}
