// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x23A661BD, "STUStatescriptStateDataFlowMapping")]
    public class STUStatescriptStateDataFlowMapping : STUStatescriptState {
        [STUField(0x5A6D4FBD, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_5A6D4FBD;

        [STUField(0xF92402E9, "m_answer", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_answer;

        [STUField(0xA83C2C26, "m_entity", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptDataFlowEntity m_entity;
    }
}
