// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xF3A63FB4, "STUTip")]
    public class STUTip : STUInstance {
        [STUField(0x54379800, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar[] m_54379800;

        [STUField(0xA127B088)]
        public teStructuredDataAssetRef<STUIdentifier> m_A127B088;

        [STUField(0xBAA74493, "m_condition", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_condition;

        [STUField(0xBB16810A, "m_priority", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_priority;

        [STUField(0x8A5FECAC, "m_tip")]
        public teStructuredDataAssetRef<ulong> m_tip;
    }
}
