// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x8EA96764, "STUUXUniformGrid")]
    public class STUUXUniformGrid : STUUXPanel { }
}
