// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x732508ED, "STUUXCollection")]
    public class STUUXCollection : STUUXDependencyObject {
        [STUField(0x6B0BAD63)]
        public uint m_6B0BAD63;

        [STUField(0xADE95629, "m_items", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUUXObject[] m_items;
    }
}
