// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xAAE96C16, "STUUXTextBoxBase")]
    public class STUUXTextBoxBase : STUUXControl { }
}
