// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0x1815624A, "STUUXDuration")]
    public class STUUXDuration : STUUXObject {
        [STUField(0x1930BE9A, "m_durationBehavior")]
        public Enum_17FD8E7C m_durationBehavior;

        [STUField(0x42636A6F, "m_timeSpan", ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_D3733E9D m_timeSpan;
    }
}
