// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xB1A08D7B, "STUUXPropertyPath")]
    public class STUUXPropertyPath : STUUXObject {
        [STUField(0xBD701DCF, "m_earlyBoundPathParts")]
        public uint[] m_earlyBoundPathParts;

        [STUField(0x812378EB, "m_sourceValueInfo", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_80C108B9[] m_sourceValueInfo;
    }
}
