// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xA30AC223, "STUUXDependencyObject")]
    public class STUUXDependencyObject : STUUXObject {
        [STUField(0xCCBAB44D, "m_localValues", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_540641B9[] m_localValues;
    }
}
