// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x100002C0, "STUUXAnimatable")]
    public class STUUXAnimatable : STU_247A6120 { }
}
