// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x092AFD09, "STUUXTemplate")]
    public class STUUXTemplate : STU_BB7E7366 {
        [STUField(0xB1B74816, "m_resources", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUUXResourceDictionary m_resources;
    }
}
