// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x5C713BD4, "STUUnlock_SprayPaintEffect")]
    public class STUUnlock_SprayPaintEffect : STUInstance {
        [STUField(0x58D56DD4, "m_effect")]
        public teStructuredDataAssetRef<STUEffect> m_effect;

        [STUField(0x2B522C5B, "m_effectLook")]
        public teStructuredDataAssetRef<STUEffectLook> m_effectLook;
    }
}
