// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0xB5D8D58C, "STUUXStoryboardClock")]
    public class STUUXStoryboardClock : STUUXObject { }
}
