// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x8AA50FF2, "STUUXPanel")]
    public class STUUXPanel : STUUXElement {
        [STUField(0xAECD07C2, "m_children", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUUXElement[] m_children;
    }
}
