// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x2E042A64, "STUUXHeaderedContentControl")]
    public class STUUXHeaderedContentControl : STUUXContentControl { }
}
