// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x6ACE6097, "STUUXPriorityBinding")]
    public class STUUXPriorityBinding : STUUXBindingBase {
        [STUField(0x5F03FB03, "m_bindings", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUUXBinding[] m_bindings;
    }
}
