// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0x8E77E8A1, "STUUnlock_POTGAnimation")]
    public class STUUnlock_POTGAnimation : STUUnlock {
        [STUField(0x3F5B86A4, "m_animation")]
        public teStructuredDataAssetRef<STUAnimation> m_animation;

        [STUField(0x0619C597, "m_type")]
        public Enum_E5327514 m_type;
    }
}
