// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x6B77CF61, "STUUXPopupRoot")]
    public class STUUXPopupRoot : STUUXElement { }
}
