// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x67F9627E, "STUUXVisualStateManager")]
    public class STUUXVisualStateManager : STUUXDependencyObject { }
}
