// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All

namespace TankLib.STU.Types {
    [STU(0x8745618A, "STUVoiceSetComponent")]
    public class STUVoiceSetComponent : STUEntityComponent {
        [STUField(0x8A4FF89C, "m_voiceDefinition")]
        public teStructuredDataAssetRef<STUVoiceSet> m_voiceDefinition;
    }
}
