// Instance generated by TankLibHelper.InstanceBuilder

using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STU(0xC611D2BA, "teAITotem")]
    public class teAITotem : STUInstance {
        [STUField(0xD7943D68, "Area")]
        public float Area;

        [STUField(0xBF396750)]
        public int m_BF396750;

        [STUField(0x4E9F6278, "Neighbors", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public teAITotem[] Neighbors;

        [STUField(0xCC50013B, "PathableCentroid")]
        public teVec3A PathableCentroid;

        [STUField(0x3B7C6E5A, "Radius")]
        public float Radius;

        [STUField(0xD3CF5F85, "SphereCentroid")]
        public teVec3A SphereCentroid;

        [STUField(0x9789E7EB, "SurfaceAdditionalData", ReaderType = typeof(InlineInstanceFieldReader))]
        public teAITotemSurfaceAdditionalData[] SurfaceAdditionalData;

        [STUField(0xDC8A979C, "SurfaceIds")]
        public ulong[] SurfaceIds;
    }
}
