// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x5B361C17)]
    public enum Enum_5B361C17 : uint {
        [STUField(0x3EA7BE2A)]
        x3EA7BE2A = 0x0,

        [STUField(0x933F3923)]
        x933F3923 = 0x1,

        [STUField(0x666FD065)]
        x666FD065 = 0x2,

        [STUField(0x56316843)]
        x56316843 = 0x3,
    }
}
