// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x45F0592D)]
    public enum Enum_45F0592D : uint {
        [STUField(0x295D5B6A)]
        x295D5B6A = 0x0,

        [STUField(0xAD4C81B6)]
        xAD4C81B6 = 0x1,

        [STUField(0x642AC7AD)]
        x642AC7AD = 0x2,

        [STUField(0x3434FEE8)]
        x3434FEE8 = 0x3,
    }
}
