// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x827B79B0)]
    public enum Enum_827B79B0 : uint {
        [STUField(0x13EDC259)]
        x13EDC259 = 0x0,

        [STUField(0x1942739E)]
        x1942739E = 0x1,

        [STUField(0xCCE4B399)]
        xCCE4B399 = 0x2,
    }
}
