// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0xC7966EC7)]
    public enum Enum_C7966EC7 : uint {
        [STUField(0x2703A0E1)]
        x2703A0E1 = 0x0,

        [STUField(0x60D0A7EF)]
        x60D0A7EF = 0x1,

        [STUField(0xD709662E)]
        xD709662E = 0x2,
    }
}
