// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x577E7214)]
    public enum Enum_577E7214 : uint {
        [STUField(0xA7445AFD)]
        xA7445AFD = 0x0,

        [STUField(0x3CD193BB)]
        x3CD193BB = 0x1,

        [STUField(0xE1229624)]
        xE1229624 = 0x2,

        [STUField(0xF2963A56)]
        xF2963A56 = 0x3,
    }
}
