// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0xA6954035)]
    public enum Enum_A6954035 : uint {
        [STUField(0x00495C6B)]
        x00495C6B = 0x0,

        [STUField(0xE2E7072C)]
        xE2E7072C = 0x1,

        [STUField(0x45F1F77C)]
        x45F1F77C = 0x2,
    }
}
