// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0xB7AABB54)]
    public enum Enum_B7AABB54 : uint {
        [STUField(0x71F646D3)]
        x71F646D3 = 0x0,

        [STUField(0x879E09A4)]
        x879E09A4 = 0x1,
    }
}
