// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x2D0A59BA)]
    public enum Enum_2D0A59BA : uint {
        [STUField(0x3C541ECF)]
        x3C541ECF = 0x0,

        [STUField(0x5D109818)]
        x5D109818 = 0x1,

        [STUField(0xAB0DD28C)]
        xAB0DD28C = 0x2,

        [STUField(0x29BB6C48)]
        x29BB6C48 = 0x3,

        [STUField(0x712178EF)]
        x712178EF = 0x4,
    }
}
