// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x19853D98)]
    public enum Enum_19853D98 : uint {
        [STUField(0xD795A15F)]
        xD795A15F = 0x0,

        [STUField(0x2D14E0F8)]
        x2D14E0F8 = 0x1,

        [STUField(0xF8F8CEF1)]
        xF8F8CEF1 = 0x2,
    }
}
