// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0xBC76726E)]
    public enum Enum_BC76726E : uint {
        [STUField(0x748C53D6)]
        x748C53D6 = 0x0,

        [STUField(0xCE9281CA)]
        xCE9281CA = 0x1,

        [STUField(0xCF9B9DFD)]
        xCF9B9DFD = 0x2,
    }
}
