// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x19FE2EB5)]
    public enum Enum_19FE2EB5 : uint {
        [STUField(0x4B6553D9)]
        x4B6553D9 = 0x0,

        [STUField(0xCAA7448E)]
        xCAA7448E = 0x1,

        [STUField(0x45BF4296)]
        x45BF4296 = 0x2,
    }
}
