// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0xCF8C2267)]
    public enum Enum_CF8C2267 : uint {
        [STUField(0x8817BF32)]
        x8817BF32 = 0x1,
    }
}
