// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0xBA664FFA)]
    public enum Enum_BA664FFA : uint {
        [STUField(0xD28A2665)]
        xD28A2665 = 0x1,

        [STUField(0x6DAE6A6F)]
        x6DAE6A6F = 0x2,

        [STUField(0x4A4DFAD7)]
        x4A4DFAD7 = 0x4,
    }
}
