// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x0604DC07)]
    public enum Enum_0604DC07 : uint {
        [STUField(0x5F4EB24A)]
        x5F4EB24A = 0x0,

        [STUField(0xB78A9497)]
        xB78A9497 = 0x1,
    }
}
