// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0xB06ED6CF)]
    public enum Enum_B06ED6CF : uint {
        [STUField(0xAAB957E1)]
        xAAB957E1 = 0x0,

        [STUField(0x07C0A3D2)]
        x07C0A3D2 = 0x1,

        [STUField(0x42C84994)]
        x42C84994 = 0x2,
    }
}
