// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0xD34AFC2B)]
    public enum Enum_D34AFC2B : uint {
        [STUField(0x6F23A739)]
        x6F23A739 = 0x0,

        [STUField(0x5E2E665D)]
        x5E2E665D = 0x1,

        [STUField(0xBE1AFE1B)]
        xBE1AFE1B = 0x2,
    }
}
