// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x981FD5ED)]
    public enum Enum_981FD5ED : uint {
        [STUField(0x7EB8741F)]
        x7EB8741F = 0x0,

        [STUField(0xE5B23172)]
        xE5B23172 = 0x1,

        [STUField(0x794EC311)]
        x794EC311 = 0x2,

        [STUField(0x9774E0F5)]
        x9774E0F5 = 0x3,

        [STUField(0x134412CB)]
        x134412CB = 0x4,

        [STUField(0x00564806)]
        x00564806 = 0x5,

        [STUField(0xBCB77C71)]
        xBCB77C71 = 0x6,

        [STUField(0xC76907C8)]
        xC76907C8 = 0x7,

        [STUField(0x7259C9AE)]
        x7259C9AE = 0x8,

        [STUField(0x2FE71A40)]
        x2FE71A40 = 0x9,

        [STUField(0x7C4DB5D8)]
        x7C4DB5D8 = 0xA,

        [STUField(0xD2393CAF)]
        xD2393CAF = 0xB,

        [STUField(0x69F4D3DA)]
        x69F4D3DA = 0xC,

        [STUField(0x8905E9AF)]
        x8905E9AF = 0xD,

        [STUField(0x1699FB1D)]
        x1699FB1D = 0xE,

        [STUField(0xE13A024A)]
        xE13A024A = 0xF,

        [STUField(0xB5D57637)]
        xB5D57637 = 0x10,

        [STUField(0x6CA4F209)]
        x6CA4F209 = 0x11,

        [STUField(0x7551DAEF)]
        x7551DAEF = 0x12,

        [STUField(0x3E0E82EC)]
        x3E0E82EC = 0x13,

        [STUField(0x1A93135F)]
        x1A93135F = 0x14,

        [STUField(0x2325DD14)]
        x2325DD14 = 0x15,

        [STUField(0x4B25EF5A)]
        x4B25EF5A = 0x16,

        [STUField(0xEEA44BF1)]
        xEEA44BF1 = 0x17,
    }
}
