// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x950F7205)]
    public enum Enum_950F7205 : byte {
        [STUField(0xE8ACB95D)]
        xE8ACB95D = 0x0,

        [STUField(0x5CC6C8F1)]
        x5CC6C8F1 = 0x1,

        [STUField(0xE977FE71)]
        xE977FE71 = 0x2,

        [STUField(0xBDC1A69F)]
        xBDC1A69F = 0x3,

        [STUField(0x8980E04E)]
        x8980E04E = 0x4,

        [STUField(0xFBD0021A)]
        xFBD0021A = 0x5,

        [STUField(0xA01E1DFC)]
        xA01E1DFC = 0x6,

        [STUField(0x65DCB8C9)]
        x65DCB8C9 = 0x7,

        [STUField(0xAB17283E)]
        xAB17283E = 0x8,

        [STUField(0xD7E15C8D)]
        xD7E15C8D = 0x9,

        [STUField(0xB4A4BF5D)]
        xB4A4BF5D = 0xA,

        [STUField(0xD5BCD1B2)]
        xD5BCD1B2 = 0xB,

        [STUField(0x387DAF79)]
        x387DAF79 = 0xC,

        [STUField(0xE90BB207)]
        xE90BB207 = 0xD,
    }
}
