// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x135DBBD2)]
    public enum Enum_135DBBD2 : uint {
        [STUField(0x29078B2A)]
        x29078B2A = 0x0,

        [STUField(0xEE1AC663)]
        xEE1AC663 = 0x1,

        [STUField(0x7C9383E2)]
        x7C9383E2 = 0x2,
    }
}
