// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x10001C30)]
    public enum Enum_10001C30 : uint {
        [STUField(0x7B4E6233)]
        x7B4E6233 = 0x0,

        [STUField(0xFA55EA37)]
        xFA55EA37 = 0x1,

        [STUField(0xC297A21D)]
        xC297A21D = 0x2,
    }
}
