// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0xBB6BE610)]
    public enum Enum_BB6BE610 : uint {
        [STUField(0xDF346F04)]
        xDF346F04 = 0x1,
    }
}
