// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0xA1A3592C)]
    public enum Enum_A1A3592C : uint {
        [STUField(0x6698F470)]
        x6698F470 = 0x0,

        [STUField(0xA7BA1251)]
        xA7BA1251 = 0x1,

        [STUField(0x46552E5C)]
        x46552E5C = 0x2,

        [STUField(0xB0CA54AE)]
        xB0CA54AE = 0x3,
    }
}
