// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x4A620507)]
    public enum Enum_4A620507 : uint {
        [STUField(0x0F3FE1DF)]
        x0F3FE1DF = 0x0,

        [STUField(0x2BAA597B)]
        x2BAA597B = 0x1,
    }
}
