// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0xC37E9E24)]
    public enum Enum_C37E9E24 : byte {
        [STUField(0x636EB452)]
        x636EB452 = 0x0,

        [STUField(0x660FC4CE)]
        x660FC4CE = 0x1,

        [STUField(0x31AE8634)]
        x31AE8634 = 0x2,
    }
}
