// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0xB29910EC)]
    public enum Enum_B29910EC : uint {
        [STUField(0x3FEAC5B8)]
        x3FEAC5B8 = 0x0,

        [STUField(0x878BECC2)]
        x878BECC2 = 0x1,

        [STUField(0x4D067AF8)]
        x4D067AF8 = 0x2,

        [STUField(0x899D69D1)]
        x899D69D1 = 0x3,

        [STUField(0x605424CE)]
        x605424CE = 0x4,
    }
}
