// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x0A0E23A4)]
    public enum Enum_0A0E23A4 : uint {
        [STUField(0x1572A31F)]
        x1572A31F = 0x0,

        [STUField(0xAC35EB67)]
        xAC35EB67 = 0x1,

        [STUField(0xE2E4631B)]
        xE2E4631B = 0x2,

        [STUField(0xE07742B4)]
        xE07742B4 = 0x3,
    }
}
