// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x629A6EE7)]
    public enum Enum_629A6EE7 : uint {
        [STUField(0x7287B7DF)]
        x7287B7DF = 0x0,

        [STUField(0x6D8DC20E)]
        x6D8DC20E = 0x1,

        [STUField(0x4BC69F3E)]
        x4BC69F3E = 0x2,

        [STUField(0x60CE9D54)]
        x60CE9D54 = 0x3,
    }
}
