// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x113A7BAD)]
    public enum Enum_113A7BAD : uint {
        [STUField(0x323235A2)]
        x323235A2 = 0x0,

        [STUField(0xBF43C646)]
        xBF43C646 = 0x1,

        [STUField(0x8B552B1C)]
        x8B552B1C = 0x2,

        [STUField(0x857242D3)]
        x857242D3 = 0x3,

        [STUField(0xB50D2FFE)]
        xB50D2FFE = 0x4,

        [STUField(0x58A1AB51)]
        x58A1AB51 = 0x5,

        [STUField(0xC1D4F7CA)]
        xC1D4F7CA = 0x6,

        [STUField(0x2AB2E5B1)]
        x2AB2E5B1 = 0x7,
    }
}
