// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0xDC41F586)]
    public enum Enum_DC41F586 : uint {
        [STUField(0xF658871C)]
        xF658871C = 0x0,

        [STUField(0x385FEB45)]
        x385FEB45 = 0x1,

        [STUField(0x0CD79EEC)]
        x0CD79EEC = 0x2,

        [STUField(0xECABE0C8)]
        xECABE0C8 = 0x3,

        [STUField(0x340336C9)]
        x340336C9 = 0x4,
    }
}
