// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0xC9A3B99F)]
    public enum Enum_C9A3B99F : uint {
        [STUField(0x02084B84)]
        x02084B84 = 0x0,

        [STUField(0x74FE91FD)]
        x74FE91FD = 0x1,

        [STUField(0xBC8ABD12)]
        xBC8ABD12 = 0x2,

        [STUField(0xC471B7FB)]
        xC471B7FB = 0x3,

        [STUField(0x41E67686)]
        x41E67686 = 0x4,
    }
}
