// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0xFAA0CF30)]
    public enum Enum_FAA0CF30 : uint {
        [STUField(0xA2590977)]
        xA2590977 = 0x0,

        [STUField(0x221F5E1C)]
        x221F5E1C = 0x1,

        [STUField(0x0215A267)]
        x0215A267 = 0x2,
    }
}
