// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x9C12ABD8)]
    public enum Enum_9C12ABD8 : uint {
        [STUField(0x468B525B)]
        x468B525B = 0x13D,
    }
}
