// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x168A2E71)]
    public enum Enum_168A2E71 : uint {
        [STUField(0xDE7A17EB)]
        xDE7A17EB = 0x0,

        [STUField(0x97682997)]
        x97682997 = 0x1,

        [STUField(0x2F0D0C34)]
        x2F0D0C34 = 0x2,

        [STUField(0xD1491AB9)]
        xD1491AB9 = 0x3,

        [STUField(0x53266EC1)]
        x53266EC1 = 0x4,

        [STUField(0x7081AB98)]
        x7081AB98 = 0x5,

        [STUField(0x8EEDCBCE)]
        x8EEDCBCE = 0x6,

        [STUField(0x1324B85D)]
        x1324B85D = 0x7,

        [STUField(0x4E472B57)]
        x4E472B57 = 0x8,
    }
}
