// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x1FDFA05C)]
    public enum Enum_1FDFA05C : uint {
        [STUField(0x4B79A256)]
        x4B79A256 = 0x0,

        [STUField(0x6A199996)]
        x6A199996 = 0x1,

        [STUField(0x5AF7A254)]
        x5AF7A254 = 0x2,

        [STUField(0x0B9A9D65)]
        x0B9A9D65 = 0x3,
    }
}
