// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x29E5788D)]
    public enum Enum_29E5788D : uint {
        [STUField(0x19207D56)]
        x19207D56 = 0x1,

        [STUField(0x5F2FF8D7)]
        x5F2FF8D7 = 0x2,

        [STUField(0x75C82F25)]
        x75C82F25 = 0x4,

        [STUField(0xD84070C4)]
        xD84070C4 = 0x8,

        [STUField(0x7AEE96C0)]
        x7AEE96C0 = 0xF,
    }
}
