// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x5933D07B)]
    public enum Enum_5933D07B : uint {
        [STUField(0xC388D482)]
        xC388D482 = 0x0,

        [STUField(0x3C78F19A)]
        x3C78F19A = 0x1,
    }
}
