// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x291A6A7D)]
    public enum Enum_291A6A7D : uint {
        [STUField(0x1655B8CE)]
        x1655B8CE = 0x22,
    }
}
