// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x33DACF1D)]
    public enum Enum_33DACF1D : uint {
        [STUField(0xDA8B70BD)]
        xDA8B70BD = 0x0,

        [STUField(0xB35B8D08)]
        xB35B8D08 = 0x1,

        [STUField(0x2F7BF6C8)]
        x2F7BF6C8 = 0x2,

        [STUField(0xDAF3A2AA)]
        xDAF3A2AA = 0x3,
    }
}
