// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0xE31C1A1D)]
    public enum Enum_E31C1A1D : uint {
        [STUField(0xCFA1A27F)]
        xCFA1A27F = 0x0,
    }
}
