// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x9929A4C5)]
    public enum Enum_9929A4C5 : uint {
        [STUField(0x88CAE845)]
        x88CAE845 = 0x5,
    }
}
