// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x2063627E)]
    public enum Enum_2063627E : uint {
        [STUField(0x82652769)]
        x82652769 = 0x0,

        [STUField(0xE1DC19F3)]
        xE1DC19F3 = 0x1,
    }
}
