// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0xDAE586FD)]
    public enum Enum_DAE586FD : uint {
        [STUField(0xBD2609A6)]
        xBD2609A6 = 0x0,

        [STUField(0xF4F7990A)]
        xF4F7990A = 0x1,

        [STUField(0x2B47E68D)]
        x2B47E68D = 0x2,

        [STUField(0xC58F599F)]
        xC58F599F = 0x1,
    }
}
