// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x0FD62339)]
    public enum Enum_0FD62339 : byte {
        [STUField(0xEE54CAB2)]
        xEE54CAB2 = 0x0,

        [STUField(0xC2FF1F99)]
        xC2FF1F99 = 0x1,
    }
}
