// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x42692E7B)]
    public enum Enum_42692E7B : uint {
        [STUField(0xEF024622)]
        xEF024622 = 0x1,

        [STUField(0xF2C44878)]
        xF2C44878 = 0x2,

        [STUField(0xF6F65D9A)]
        xF6F65D9A = 0x3,

        [STUField(0xB11973CA)]
        xB11973CA = 0x3,
    }
}
