// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x6EBD2672)]
    public enum Enum_6EBD2672 : uint {
        [STUField(0x16023D67)]
        x16023D67 = 0x0,

        [STUField(0xF469C887)]
        xF469C887 = 0x1,

        [STUField(0x43932286)]
        x43932286 = 0x2,

        [STUField(0x34941210)]
        x34941210 = 0x3,

        [STUField(0xBA0B4DC7)]
        xBA0B4DC7 = 0x4,

        [STUField(0x9D827132)]
        x9D827132 = 0x5,

        [STUField(0xEA8541A4)]
        xEA8541A4 = 0x6,

        [STUField(0x84AB6289)]
        x84AB6289 = 0x7,

        [STUField(0x55DDFE3F)]
        x55DDFE3F = 0x8,

        [STUField(0x41EA0B5A)]
        x41EA0B5A = 0x9,

        [STUField(0xD5645B85)]
        xD5645B85 = 0xA,

        [STUField(0x6ADEE86D)]
        x6ADEE86D = 0xB,

        [STUField(0x7A7CDF80)]
        x7A7CDF80 = 0xC,

        [STUField(0x0D7BEF16)]
        x0D7BEF16 = 0xD,

        [STUField(0xC2D89CF5)]
        xC2D89CF5 = 0xE,

        [STUField(0xB4CF9628)]
        xB4CF9628 = 0xF,

        [STUField(0xDA6B1F03)]
        xDA6B1F03 = 0x10,

        [STUField(0xD257E17B)]
        xD257E17B = 0x11,

        [STUField(0xF18396BF)]
        xF18396BF = 0x12,

        [STUField(0xBA9A4318)]
        xBA9A4318 = 0x13,

        [STUField(0x5AE73852)]
        x5AE73852 = 0x14,

        [STUField(0x72E62C79)]
        x72E62C79 = 0x15,
    }
}
