// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x439E511C)]
    public enum Enum_439E511C : uint {
        [STUField(0xB9007024)]
        xB9007024 = 0x1,
    }
}
