// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x51D55386)]
    public enum Enum_51D55386 : uint {
        [STUField(0x22246458)]
        x22246458 = 0x1,
    }
}
