// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x12A65521)]
    public enum Enum_12A65521 : uint {
        [STUField(0xDA828FBC)]
        xDA828FBC = 0x0,

        [STUField(0x8FCFE0B0)]
        x8FCFE0B0 = 0x1,

        [STUField(0x0C98622F)]
        x0C98622F = 0x2,

        [STUField(0x8F8C70B7)]
        x8F8C70B7 = 0x3,

        [STUField(0xA614CD64)]
        xA614CD64 = 0x4,
    }
}
