// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x9C634DEA)]
    public enum Enum_9C634DEA : uint {
        [STUField(0x8E965E97)]
        x8E965E97 = 0x1,

        [STUField(0x3054BA4A)]
        x3054BA4A = 0x2,

        [STUField(0x5475767C)]
        x5475767C = 0x4,

        [STUField(0xFC40468E)]
        xFC40468E = 0x8,
    }
}
