// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0xBABC4175)]
    public enum Enum_BABC4175 : uint {
        [STUField(0x22A72C00)]
        Base = 0x0,

        [STUField(0x9722B6D4)]
        SummerGames = 0x1,

        [STUField(0x6771D6F5)]
        Halloween = 0x2,

        [STUField(0x641ED9C7)]
        Winter = 0x3,

        [STUField(0xC6836954)]
        LunarNewYear = 0x4,

        [STUField(0x31800B95)]
        Archives = 0x5,

        [STUField(0xBDBB3D54)]
        Anniversary = 0x6,

        [STUField(0x8B02F5D7)]
        Golden = 0x7,

        [STUField(0xD6954B53)]
        Internal = 0x8,

        [STUField(0x6C02F9A7)]
        LegendaryAnniversary = 0x9,

        [STUField(0xC026BA80)]
        Hammond = 0xA,

        [STUField(0xBE88B178)]
        xBE88B178 = 0xB,

        [STUField(0x8A0F302F)]
        x8A0F302F = 0xC,

        [STUField(0xC1854306)]
        xC1854306 = 0xFFFFFF,
    }
}
