// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x4368B765)]
    public enum Enum_4368B765 : uint {
        [STUField(0xEFAD49F4)]
        xEFAD49F4 = 0x0,

        [STUField(0x62E88BEB)]
        x62E88BEB = 0x1,

        [STUField(0x5BA81B50)]
        x5BA81B50 = 0x2,
    }
}
