// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0xE4984496)]
    public enum Enum_E4984496 : uint {
        [STUField(0xF2CE40AF)]
        xF2CE40AF = 0x0,

        [STUField(0x4A63F265)]
        x4A63F265 = 0x1,

        [STUField(0x9F71CD1B)]
        x9F71CD1B = 0x2,

        [STUField(0x7BAB9A69)]
        x7BAB9A69 = 0x3,

        [STUField(0x08F59071)]
        x08F59071 = 0x4,

        [STUField(0xFCE0F0B8)]
        xFCE0F0B8 = 0x5,

        [STUField(0x6C38421E)]
        x6C38421E = 0x6,

        [STUField(0xCD538571)]
        xCD538571 = 0x7,

        [STUField(0x988CB021)]
        x988CB021 = 0x8,

        [STUField(0x2BB582FD)]
        x2BB582FD = 0x9,

        [STUField(0xFDBE1EB4)]
        xFDBE1EB4 = 0xA,

        [STUField(0x27896E6E)]
        x27896E6E = 0xB,

        [STUField(0xCFD9D34B)]
        xCFD9D34B = 0xC,

        [STUField(0x22505162)]
        x22505162 = 0xD,

        [STUField(0x2CA5D4C8)]
        x2CA5D4C8 = 0xE,

        [STUField(0x11069D44)]
        x11069D44 = 0xF,

        [STUField(0xE39C962B)]
        xE39C962B = 0x10,

        [STUField(0x100CCC56)]
        x100CCC56 = 0x11,

        [STUField(0xFFE1306B)]
        xFFE1306B = 0x12,

        [STUField(0xF2FFB2D6)]
        xF2FFB2D6 = 0x13,

        [STUField(0x406B2D03)]
        x406B2D03 = 0x14,

        [STUField(0xB9A626DC)]
        xB9A626DC = 0x15,

        [STUField(0x52335045)]
        x52335045 = 0x16,

        [STUField(0xFE277E35)]
        xFE277E35 = 0x17,

        [STUField(0x71445C1B)]
        x71445C1B = 0x18,

        [STUField(0x9AAB22F2)]
        x9AAB22F2 = 0x19,

        [STUField(0x1C498574)]
        x1C498574 = 0x1A,

        [STUField(0x00D71FB8)]
        x00D71FB8 = 0x1B,

        [STUField(0xC369CC88)]
        xC369CC88 = 0x1C,

        [STUField(0x2C97654E)]
        x2C97654E = 0x1D,

        [STUField(0x1E7EFAE3)]
        x1E7EFAE3 = 0x1E,
    }
}
