// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0xBD82F7F1)]
    public enum Enum_BD82F7F1 : uint {
        [STUField(0x07EF9FC9)]
        x07EF9FC9 = 0x1,

        [STUField(0xF94825AC)]
        xF94825AC = 0x2,
    }
}
