// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0xA71BB347)]
    public enum Enum_A71BB347 : uint {
        [STUField(0x479C8AB5)]
        x479C8AB5 = 0x0,

        [STUField(0x15DD0F50)]
        x15DD0F50 = 0x1,

        [STUField(0xDC7296D0)]
        xDC7296D0 = 0x2,

        [STUField(0x56C967C2)]
        x56C967C2 = 0x3,
    }
}
