// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0xC074B9DE)]
    public enum Enum_C074B9DE : uint {
        [STUField(0x12BFB26A)]
        x12BFB26A = 0x0,

        [STUField(0xBBD9179C)]
        xBBD9179C = 0x1,

        [STUField(0x4F1B70A3)]
        x4F1B70A3 = 0x2,

        [STUField(0x5F77605D)]
        x5F77605D = 0x3,
    }
}
