// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x7649ABFB)]
    public enum Enum_7649ABFB : uint {
        [STUField(0x141BAE67)]
        x141BAE67 = 0x0,

        [STUField(0x779E25F6)]
        x779E25F6 = 0x1,

        [STUField(0x6ED85295)]
        x6ED85295 = 0x2,

        [STUField(0x5AEF17FB)]
        x5AEF17FB = 0x3,

        [STUField(0x6A535933)]
        x6A535933 = 0x4,

        [STUField(0x4863C9D6)]
        x4863C9D6 = 0x5,

        [STUField(0x89F45872)]
        x89F45872 = 0x6,

        [STUField(0x0CCB2E60)]
        x0CCB2E60 = 0x7,
    }
}
