// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x499AD032)]
    public enum Enum_499AD032 : uint {
        [STUField(0x3DBF0522)]
        x3DBF0522 = 0x0,

        [STUField(0x99084708)]
        x99084708 = 0x1,

        [STUField(0x154CF5E9)]
        x154CF5E9 = 0x2,

        [STUField(0xF7124D50)]
        xF7124D50 = 0x3,

        [STUField(0xFF864741)]
        xFF864741 = 0x4,

        [STUField(0xD1211BCD)]
        xD1211BCD = 0x5,
    }
}
