// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x25F056D0)]
    public enum Enum_25F056D0 : uint {
        [STUField(0x9003E84B)]
        x9003E84B = 0x0,

        [STUField(0xE97CF292)]
        xE97CF292 = 0x1,

        [STUField(0xE29DD09F)]
        xE29DD09F = 0x2,

        [STUField(0x937E7EC2)]
        x937E7EC2 = 0x3,
    }
}
