// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0xFB7F61B4)]
    public enum Enum_FB7F61B4 : uint {
        [STUField(0x686745A7)]
        x686745A7 = 0x0,

        [STUField(0x126D59AF)]
        x126D59AF = 0x1,
    }
}
