// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x4D18469F)]
    public enum Enum_4D18469F : uint {
        [STUField(0x7974C479)]
        x7974C479 = 0x0,

        [STUField(0xF0A7DE7A)]
        xF0A7DE7A = 0x1,

        [STUField(0x4BB69BFD)]
        x4BB69BFD = 0x2,
    }
}
