// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x86B34B33)]
    public enum Enum_86B34B33 : uint {
        [STUField(0xB0F9EF64)]
        xB0F9EF64 = 0x1,

        [STUField(0x844D7994)]
        x844D7994 = 0x2,

        [STUField(0x8C2B6E67)]
        x8C2B6E67 = 0x4,
    }
}
