// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x10064D07)]
    public enum Enum_10064D07 : uint {
        [STUField(0xF2CADE38)]
        xF2CADE38 = 0x0,

        [STUField(0x5D6705A9)]
        x5D6705A9 = 0x1,

        [STUField(0x560F3DEE)]
        x560F3DEE = 0x2,

        [STUField(0x81B56726)]
        x81B56726 = 0x3,

        [STUField(0x344E6B62)]
        x344E6B62 = 0x4,

        [STUField(0xF13E5FF4)]
        xF13E5FF4 = 0x5,

        [STUField(0x6715FD8E)]
        x6715FD8E = 0x6,
    }
}
