// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0xBC00E017)]
    public enum Enum_BC00E017 : uint {
        [STUField(0x426CE267)]
        x426CE267 = 0x0,

        [STUField(0xAC7BD9AC)]
        xAC7BD9AC = 0x1,

        [STUField(0x25B1AED8)]
        x25B1AED8 = 0x2,

        [STUField(0x104CDEDC)]
        x104CDEDC = 0x3,
    }
}
