// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x022EE925)]
    public enum Enum_022EE925 : uint {
        [STUField(0x1C5258CC)]
        x1C5258CC = 0x0,

        [STUField(0xED58251C)]
        xED58251C = 0x1,
    }
}
