// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x0C014B4A)]
    public enum Enum_0C014B4A : uint {
        [STUField(0x1745B921)]
        Neither = 0x1,

        [STUField(0x5123F4E9)]
        Male = 0x2,

        [STUField(0xAFA0BA5C)]
        Female = 0x3,
    }
}
