// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x8F651EAA)]
    public enum Enum_8F651EAA : uint {
        [STUField(0x24753B29)]
        x24753B29 = 0x2,
    }
}
