// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x0089A8AE)]
    public enum Enum_0089A8AE : uint {
        [STUField(0x82AA97FD)]
        x82AA97FD = 0x0,

        [STUField(0xF2743D80)]
        xF2743D80 = 0x1,

        [STUField(0x5402D705)]
        x5402D705 = 0x2,

        [STUField(0x58038199)]
        x58038199 = 0x3,

        [STUField(0xDCFB011F)]
        xDCFB011F = 0x4,

        [STUField(0x076F3692)]
        x076F3692 = 0x5,

        [STUField(0xD4244F36)]
        xD4244F36 = 0x6,

        [STUField(0x6B129FA2)]
        x6B129FA2 = 0x7,

        [STUField(0xA69C1FA0)]
        xA69C1FA0 = 0x8,

        [STUField(0xBB2B9092)]
        xBB2B9092 = 0x9,

        [STUField(0xCC8F05CF)]
        xCC8F05CF = 0xA,

        [STUField(0x996CFCAF)]
        x996CFCAF = 0xB,

        [STUField(0x9B57C592)]
        x9B57C592 = 0xC,

        [STUField(0x6F26D9EF)]
        x6F26D9EF = 0xD,
    }
}
