// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x13D7298D)]
    public enum Enum_13D7298D : uint {
        [STUField(0x36A0010B)]
        x36A0010B = 0x0,

        [STUField(0x44F3D31E)]
        x44F3D31E = 0x1,

        [STUField(0xFC8F59BA)]
        xFC8F59BA = 0x2,

        [STUField(0x4826AFE2)]
        x4826AFE2 = 0x3,
    }
}
