// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0xA7DD6145)]
    public enum Enum_A7DD6145 : uint {
        [STUField(0xB57D80A0)]
        xB57D80A0 = 0x0,

        [STUField(0xECCEBD49)]
        xECCEBD49 = 0x1,

        [STUField(0x16601BFE)]
        x16601BFE = 0x2,

        [STUField(0xEF4E0159)]
        xEF4E0159 = 0x3,

        [STUField(0xDEFEFA25)]
        xDEFEFA25 = 0x4,

        [STUField(0xD4636AF7)]
        xD4636AF7 = 0x5,

        [STUField(0x87AA0DF3)]
        x87AA0DF3 = 0x6,
    }
}
