// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0xB220D6E4)]
    public enum Enum_B220D6E4 : uint {
        [STUField(0x3A6D687B)]
        x3A6D687B = 0x0,

        [STUField(0xF669002F)]
        xF669002F = 0x1,

        [STUField(0x69F07E27)]
        x69F07E27 = 0x2,

        [STUField(0xF54EBBAB)]
        xF54EBBAB = 0x3,

        [STUField(0xF428C120)]
        xF428C120 = 0x4,

        [STUField(0x21B679C7)]
        x21B679C7 = 0x5,

        [STUField(0x1FB5608D)]
        x1FB5608D = 0x6,

        [STUField(0x25B1D62F)]
        x25B1D62F = 0x7,

        [STUField(0x75CB2306)]
        x75CB2306 = 0x8,

        [STUField(0xD631CF0E)]
        xD631CF0E = 0x9,

        [STUField(0x95A0BB39)]
        x95A0BB39 = 0xA,

        [STUField(0x81681B66)]
        x81681B66 = 0xB,
    }
}
