// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x32497A1C)]
    public enum Enum_32497A1C : uint {
        [STUField(0x4EEA61C1)]
        x4EEA61C1 = 0x0,

        [STUField(0xFF157A46)]
        xFF157A46 = 0x1,

        [STUField(0xC158D2C5)]
        xC158D2C5 = 0x2,
    }
}
