// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x29852471)]
    public enum Enum_29852471 : uint {
        [STUField(0xA168B36F)]
        xA168B36F = 0x0,

        [STUField(0xFF10917F)]
        xFF10917F = 0x1,

        [STUField(0x0E09CC81)]
        x0E09CC81 = 0x2,
    }
}
