// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0xD4BAD8E7)]
    public enum Enum_D4BAD8E7 : uint {
        [STUField(0xA31A3675)]
        xA31A3675 = 0x0,

        [STUField(0xE2FC06E1)]
        xE2FC06E1 = 0x1,

        [STUField(0x00943466)]
        x00943466 = 0x2,

        [STUField(0x60671788)]
        x60671788 = 0x3,

        [STUField(0xA1758ACA)]
        xA1758ACA = 0x4,
    }
}
