// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x05A537E0)]
    public enum Enum_05A537E0 : uint {
        [STUField(0x52ACD5CE)]
        x52ACD5CE = 0x0,

        [STUField(0xB58796E2)]
        xB58796E2 = 0x1,

        [STUField(0x0869CDA9)]
        x0869CDA9 = 0x2,

        [STUField(0x9B9DD2C0)]
        x9B9DD2C0 = 0x3,

        [STUField(0xD5000E39)]
        xD5000E39 = 0x4,
    }
}
