// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x4FC86C3B)]
    public enum Enum_4FC86C3B : uint {
        [STUField(0x470B4C06)]
        x470B4C06 = 0x5,
    }
}
