// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x8FBC5449)]
    public enum Enum_8FBC5449 : uint {
        [STUField(0x8A492D44)]
        x8A492D44 = 0x2,
    }
}
