// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x88C669F3)]
    public enum Enum_88C669F3 : uint {
        [STUField(0x94F1A4DE)]
        x94F1A4DE = 0x0,

        [STUField(0x79F121C6)]
        x79F121C6 = 0x1,

        [STUField(0x594A71B2)]
        x594A71B2 = 0x2,

        [STUField(0xA8108694)]
        xA8108694 = 0x3,

        [STUField(0x39A22FF3)]
        x39A22FF3 = 0x4,

        [STUField(0x8DC9714E)]
        x8DC9714E = 0x5,

        [STUField(0xD34B512A)]
        xD34B512A = 0x6,

        [STUField(0xEBD54C02)]
        xEBD54C02 = 0x7,

        [STUField(0x4A27DBA2)]
        x4A27DBA2 = 0x8,

        [STUField(0x7C8CAD46)]
        x7C8CAD46 = 0x9,

        [STUField(0x00BB98A0)]
        x00BB98A0 = 0xA,

        [STUField(0x59883E0E)]
        x59883E0E = 0xB,
    }
}
