// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0xFC615679)]
    public enum Enum_FC615679 : uint {
        [STUField(0x0C242552)]
        x0C242552 = 0x0,

        [STUField(0xB996EA09)]
        xB996EA09 = 0x1,

        [STUField(0x2E0FE530)]
        x2E0FE530 = 0x2,

        [STUField(0x9118D4BE)]
        x9118D4BE = 0x3,

        [STUField(0xC9502447)]
        xC9502447 = 0x0,
    }
}
