// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x07D62806)]
    public enum Enum_07D62806 : uint {
        [STUField(0x57904394)]
        x57904394 = 0x0,

        [STUField(0xB60315DE)]
        xB60315DE = 0x1,

        [STUField(0x2FAAAA37)]
        x2FAAAA37 = 0x2,

        [STUField(0xA1183B07)]
        xA1183B07 = 0x3,
    }
}
