// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x1ABD3A0E)]
    public enum Enum_1ABD3A0E : uint {
        [STUField(0x5C5844AE)]
        x5C5844AE = 0x1,

        [STUField(0x459E3E50)]
        x459E3E50 = 0x2,
    }
}
