// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x2942AA95)]
    public enum Enum_2942AA95 : uint {
        [STUField(0xF544009B)]
        xF544009B = 0x0,

        [STUField(0xB241C633)]
        xB241C633 = 0x1,
    }
}
