// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0xB050693E)]
    public enum Enum_B050693E : uint {
        [STUField(0xC9A8FC72)]
        xC9A8FC72 = 0x1,

        [STUField(0x67980F98)]
        x67980F98 = 0x2C,

        [STUField(0xACCA4D85)]
        xACCA4D85 = 0xD0046,
    }
}
