// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0xAD2CA2C1)]
    public enum Enum_AD2CA2C1 : uint {
        [STUField(0x9BCF6E68)]
        x9BCF6E68 = 0x0,

        [STUField(0x0F479049)]
        x0F479049 = 0x1,

        [STUField(0x77470BF2)]
        x77470BF2 = 0x2,

        [STUField(0xDFB472C2)]
        xDFB472C2 = 0x3,

        [STUField(0xD898AD87)]
        xD898AD87 = 0x4,

        [STUField(0x7DA22026)]
        x7DA22026 = 0x5,
    }
}
