// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x788B1979)]
    public enum Enum_788B1979 : uint {
        [STUField(0xB9DFDDAF)]
        xB9DFDDAF = 0x1E,
    }
}
