// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0xBBBF4A78)]
    public enum Enum_BBBF4A78 : uint {
        [STUField(0x725433C5)]
        x725433C5 = 0x0,

        [STUField(0x85397BCB)]
        x85397BCB = 0x1,

        [STUField(0xF73971E4)]
        xF73971E4 = 0x2,

        [STUField(0xB59A6736)]
        xB59A6736 = 0x3,

        [STUField(0x5A513AF5)]
        x5A513AF5 = 0x4,

        [STUField(0xDCF6F726)]
        xDCF6F726 = 0x5,

        [STUField(0x58A9FF59)]
        x58A9FF59 = 0x6,

        [STUField(0x09CF4D58)]
        x09CF4D58 = 0x7,

        [STUField(0xFF48FC08)]
        xFF48FC08 = 0x8,

        [STUField(0x21C6B4EF)]
        x21C6B4EF = 0x9,

        [STUField(0xBA60E48C)]
        xBA60E48C = 0xA,

        [STUField(0x7480AA42)]
        x7480AA42 = 0xB,

        [STUField(0x9FA08D50)]
        x9FA08D50 = 0xC,

        [STUField(0x0A71F992)]
        x0A71F992 = 0xD,

        [STUField(0xD63B03CE)]
        xD63B03CE = 0xE,

        [STUField(0xF346B563)]
        xF346B563 = 0xF,

        [STUField(0x4E1E8DC6)]
        x4E1E8DC6 = 0x10,

        [STUField(0x12581568)]
        x12581568 = 0x11,

        [STUField(0x9A9A647E)]
        x9A9A647E = 0x12,

        [STUField(0x1BBA919F)]
        x1BBA919F = 0x13,

        [STUField(0xBB8AE3A0)]
        xBB8AE3A0 = 0x14,

        [STUField(0x35A8656C)]
        x35A8656C = 0x15,

        [STUField(0x5C17C717)]
        x5C17C717 = 0x16,

        [STUField(0x60F13A58)]
        x60F13A58 = 0x17,

        [STUField(0x7A95E29D)]
        x7A95E29D = 0x18,

        [STUField(0xD34BA136)]
        xD34BA136 = 0x19,

        [STUField(0x43CAFB1D)]
        x43CAFB1D = 0x1A,

        [STUField(0xA6BFB9C3)]
        xA6BFB9C3 = 0x1B,

        [STUField(0x06CE90AC)]
        x06CE90AC = 0x1C,

        [STUField(0xBCD58CB1)]
        xBCD58CB1 = 0x1D,

        [STUField(0x84A0A320)]
        x84A0A320 = 0x1E,

        [STUField(0x924D42EF)]
        x924D42EF = 0x1F,

        [STUField(0xE2F69F7F)]
        xE2F69F7F = 0x20,

        [STUField(0x8E69DDE7)]
        x8E69DDE7 = 0x21,

        [STUField(0xBD9F658E)]
        xBD9F658E = 0x22,

        [STUField(0xB922634C)]
        xB922634C = 0x23,

        [STUField(0x47BED440)]
        x47BED440 = 0x24,

        [STUField(0x6C9191B4)]
        x6C9191B4 = 0x25,

        [STUField(0x1CDC276A)]
        x1CDC276A = 0x26,

        [STUField(0xFEAB06DF)]
        xFEAB06DF = 0x27,

        [STUField(0xD7BE6075)]
        xD7BE6075 = 0x28,

        [STUField(0xB9D6803D)]
        xB9D6803D = 0x29,

        [STUField(0x99D8747F)]
        x99D8747F = 0x2A,

        [STUField(0x747B57D3)]
        x747B57D3 = 0x2B,

        [STUField(0x486EEB50)]
        x486EEB50 = 0x2C,

        [STUField(0xC91C4F01)]
        xC91C4F01 = 0x2D,

        [STUField(0x105ADCA9)]
        x105ADCA9 = 0x2E,

        [STUField(0x1890C1CD)]
        x1890C1CD = 0x2F,

        [STUField(0xA27B8B9F)]
        xA27B8B9F = 0x30,

        [STUField(0xAE5A290B)]
        xAE5A290B = 0x31,

        [STUField(0x8309D714)]
        x8309D714 = 0x32,
    }
}
