// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0xD02E5ECD)]
    public enum Enum_D02E5ECD : uint {
        [STUField(0x99E8A7AD)]
        x99E8A7AD = 0x0,

        [STUField(0x86BF986B)]
        x86BF986B = 0x1,
    }
}
