// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x4BE16CA5)]
    public enum Enum_4BE16CA5 : uint {
        [STUField(0xA830D07D)]
        xA830D07D = 0x0,

        [STUField(0x7D6D2A68)]
        x7D6D2A68 = 0x1,

        [STUField(0xEE29D0A2)]
        xEE29D0A2 = 0x2,

        [STUField(0xCF872CA8)]
        xCF872CA8 = 0x3,

        [STUField(0x08F70978)]
        x08F70978 = 0x4,

        [STUField(0x027926D5)]
        x027926D5 = 0x5,

        [STUField(0x654A7C97)]
        x654A7C97 = 0x6,

        [STUField(0x3774AB86)]
        x3774AB86 = 0xFFFFFF,
    }
}
