// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x686430C5)]
    public enum Enum_686430C5 : uint {
        [STUField(0xF60D1E93)]
        xF60D1E93 = 0xFFFFFF,

        [STUField(0x8D37165A)]
        x8D37165A = 0x0,

        [STUField(0x5E1EA191)]
        x5E1EA191 = 0xF,

        [STUField(0xF0D4CEF7)]
        xF0D4CEF7 = 0x10,

        [STUField(0xFCDBBA70)]
        xFCDBBA70 = 0x12,

        [STUField(0xDCFC5F5D)]
        xDCFC5F5D = 0x11,

        [STUField(0x81B68748)]
        x81B68748 = 0x13,

        [STUField(0x2DAE970D)]
        x2DAE970D = 0x14,

        [STUField(0xBD482636)]
        xBD482636 = 0x15,

        [STUField(0x458CA3BA)]
        x458CA3BA = 0x16,

        [STUField(0xFBDF307B)]
        xFBDF307B = 0x17,

        [STUField(0x0EF09F2D)]
        x0EF09F2D = 0x18,

        [STUField(0x3AF50E2B)]
        x3AF50E2B = 0x19,

        [STUField(0x27397E85)]
        x27397E85 = 0x1A,

        [STUField(0xEE341776)]
        xEE341776 = 0x1C,

        [STUField(0x3C2D1C40)]
        x3C2D1C40 = 0x20,

        [STUField(0x38B5C7FA)]
        x38B5C7FA = 0x24,

        [STUField(0x858EDFB1)]
        x858EDFB1 = 0x98,

        [STUField(0xA27D20DE)]
        xA27D20DE = 0x19A,

        [STUField(0x8B82D858)]
        x8B82D858 = 0x1E4,

        [STUField(0x402A8EBA)]
        x402A8EBA = 0x283,

        [STUField(0x5C17AB34)]
        x5C17AB34 = 0x2BE,

        [STUField(0x1D77EB16)]
        x1D77EB16 = 0x33A,

        [STUField(0xA68E35BB)]
        xA68E35BB = 0x348,

        [STUField(0x2C99CE0E)]
        x2C99CE0E = 0x3C3,

        [STUField(0x64229CBD)]
        x64229CBD = 0x3D2,

        [STUField(0x893ADAC8)]
        x893ADAC8 = 0x3DA,

        [STUField(0xBFCA7271)]
        xBFCA7271 = 0x3E7,
    }
}
