// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0xB101E48A)]
    public enum Enum_B101E48A : uint {
        [STUField(0xCBB435B1)]
        xCBB435B1 = 0x0,

        [STUField(0x96A83DAE)]
        x96A83DAE = 0x1,

        [STUField(0x55509643)]
        x55509643 = 0x2,

        [STUField(0xBB2CFC53)]
        xBB2CFC53 = 0x3,

        [STUField(0x7B8A8D07)]
        x7B8A8D07 = 0x4,
    }
}
