// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x95337ED2)]
    public enum Enum_95337ED2 : uint {
        [STUField(0x8672716A)]
        x8672716A = 0x0,

        [STUField(0x7DEC675D)]
        x7DEC675D = 0x1,

        [STUField(0xBFF8DAD6)]
        xBFF8DAD6 = 0x2,
    }
}
