// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x3611641A)]
    public enum Enum_3611641A : uint {
        [STUField(0x7685E4B8)]
        x7685E4B8 = 0x0,

        [STUField(0xEEAD03BC)]
        xEEAD03BC = 0x1,

        [STUField(0xF74A0CA8)]
        xF74A0CA8 = 0x2,

        [STUField(0x369B7CDF)]
        x369B7CDF = 0x3,
    }
}
