// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x2C810789)]
    public enum Enum_2C810789 : uint {
        [STUField(0x4E4B0D46)]
        x4E4B0D46 = 0x0,

        [STUField(0xA91ED9D6)]
        xA91ED9D6 = 0x1,

        [STUField(0xF70157CA)]
        xF70157CA = 0x2,

        [STUField(0x096AD3D8)]
        x096AD3D8 = 0x3,
    }
}
