// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0xD2C937FA)]
    public enum Enum_D2C937FA : uint {
        [STUField(0x86D10300)]
        x86D10300 = 0x0,

        [STUField(0x4AB3D05C)]
        x4AB3D05C = 0x1,

        [STUField(0xF75F2A9A)]
        xF75F2A9A = 0x2,

        [STUField(0x5F204536)]
        x5F204536 = 0x3,
    }
}
