// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x5F827B4A)]
    public enum Enum_5F827B4A : uint {
        [STUField(0x5D9370D2)]
        x5D9370D2 = 0x0,

        [STUField(0x295CE85B)]
        x295CE85B = 0x1,
    }
}
