// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x18F42478)]
    public enum Enum_18F42478 : uint {
        [STUField(0x52309517)]
        x52309517 = 0x0,

        [STUField(0xA3C2988F)]
        xA3C2988F = 0x1,

        [STUField(0x476A9B37)]
        x476A9B37 = 0x2,

        [STUField(0x67766438)]
        x67766438 = 0x3,
    }
}
