// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x53896941)]
    public enum Enum_53896941 : uint {
        [STUField(0x6C43EBD4)]
        x6C43EBD4 = 0x0,

        [STUField(0xF7521A8C)]
        xF7521A8C = 0x1,

        [STUField(0x0B30669D)]
        x0B30669D = 0x2,

        [STUField(0x3AC548AB)]
        x3AC548AB = 0x3,
    }
}
