// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x8E40F295)]
    public enum Enum_8E40F295 : uint {
        [STUField(0xD27AEA24)]
        None = 0x0,

        [STUField(0x208351B7)]
        Bronze = 0x1,

        [STUField(0x9BB185E7)]
        Silver = 0x2,

        [STUField(0x90914889)]
        Gold = 0x3,

        [STUField(0xDD6A5B64)]
        Platinum = 0x4,
    }
}
