// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x4AD2A6AD)]
    public enum Enum_4AD2A6AD : uint {
        [STUField(0xEE741A0E)]
        xEE741A0E = 0x0,

        [STUField(0x226A66A4)]
        x226A66A4 = 0x1,

        [STUField(0xEE15CC3C)]
        xEE15CC3C = 0x2,

        [STUField(0xE9F447EE)]
        xE9F447EE = 0x3,

        [STUField(0x8B88A35D)]
        x8B88A35D = 0x4,
    }
}
