// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0xC3BB057D)]
    public enum Enum_C3BB057D : uint {
        [STUField(0x6DD57B74)]
        x6DD57B74 = 0x0,

        [STUField(0x596B91F4)]
        x596B91F4 = 0x1,

        [STUField(0x1429FA87)]
        x1429FA87 = 0x2,

        [STUField(0x74D68D41)]
        x74D68D41 = 0x3,

        [STUField(0x1293F995)]
        x1293F995 = 0x4,

        [STUField(0x891DAF4D)]
        x891DAF4D = 0x5,

        [STUField(0xE0A2D53B)]
        xE0A2D53B = 0x6,

        [STUField(0x54840FB0)]
        x54840FB0 = 0x7,

        [STUField(0x14A057D0)]
        x14A057D0 = 0x8,

        [STUField(0x58177EAA)]
        x58177EAA = 0x9,

        [STUField(0x8937ED6B)]
        x8937ED6B = 0xA,

        [STUField(0x9736FD02)]
        x9736FD02 = 0xB,

        [STUField(0xE4E922E2)]
        xE4E922E2 = 0xC,

        [STUField(0x152BD7F5)]
        x152BD7F5 = 0xD,

        [STUField(0xA0A97772)]
        xA0A97772 = 0xE,

        [STUField(0xF8563D34)]
        xF8563D34 = 0xF,

        [STUField(0x69222E42)]
        x69222E42 = 0x10,

        [STUField(0xEC8256BE)]
        xEC8256BE = 0x11,

        [STUField(0x47F57D59)]
        x47F57D59 = 0x12,

        [STUField(0x04483190)]
        x04483190 = 0x13,

        [STUField(0x3F44916F)]
        x3F44916F = 0x14,

        [STUField(0xAB5A1779)]
        xAB5A1779 = 0x15,

        [STUField(0xC3C4291A)]
        xC3C4291A = 0x16,

        [STUField(0x6F107FC5)]
        x6F107FC5 = 0x17,

        [STUField(0xD18828C4)]
        xD18828C4 = 0x18,

        [STUField(0x96397DDF)]
        x96397DDF = 0x19,

        [STUField(0x383F1737)]
        x383F1737 = 0x1A,

        [STUField(0x8A45215F)]
        x8A45215F = 0x1B,

        [STUField(0x55DF8639)]
        x55DF8639 = 0x1C,

        [STUField(0x61C3F4B9)]
        x61C3F4B9 = 0x1D,

        [STUField(0x0D4B56F6)]
        x0D4B56F6 = 0x1E,

        [STUField(0x75352D85)]
        x75352D85 = 0x1F,

        [STUField(0xA890F479)]
        xA890F479 = 0x0,
    }
}
