// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x38661995)]
    public enum Enum_38661995 : uint {
        [STUField(0x6F0874C0)]
        x6F0874C0 = 0x0,

        [STUField(0x7826ABB9)]
        x7826ABB9 = 0x1,
    }
}
