// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x447977DB)]
    public enum Enum_447977DB : uint {
        [STUField(0x12FC2D98)]
        x12FC2D98 = 0x0,

        [STUField(0x5D02B014)]
        x5D02B014 = 0x1,

        [STUField(0xFC190A11)]
        xFC190A11 = 0x2,
    }
}
