// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x69A5857B)]
    public enum Enum_69A5857B : uint {
        [STUField(0xE4BB121B)]
        xE4BB121B = 0x8,

        [STUField(0x9B1DFDE8)]
        x9B1DFDE8 = 0x6,

        [STUField(0xEB9C98E3)]
        xEB9C98E3 = 0x5,
    }
}
