// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0xB83B5693)]
    public enum Enum_B83B5693 : uint {
        [STUField(0x4F8A3A34)]
        x4F8A3A34 = 0x20,
    }
}
