// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x44BC57E3)]
    public enum Enum_44BC57E3 : uint {
        [STUField(0xAA7ECD32)]
        xAA7ECD32 = 0x0,

        [STUField(0x9762274A)]
        x9762274A = 0x1,

        [STUField(0xA0B8899D)]
        xA0B8899D = 0x2,

        [STUField(0x9BB25455)]
        x9BB25455 = 0x3,

        [STUField(0xED745A68)]
        xED745A68 = 0x4,

        [STUField(0x9BE8D0E6)]
        x9BE8D0E6 = 0x5,
    }
}
