// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x04481077)]
    public enum Enum_04481077 : uint {
        [STUField(0x56034F5F)]
        x56034F5F = 0x1,

        [STUField(0x6C73CD5C)]
        x6C73CD5C = 0x2,

        [STUField(0x32347949)]
        x32347949 = 0x4,

        [STUField(0x88A6FCD4)]
        x88A6FCD4 = 0x8,

        [STUField(0xE4147D2E)]
        xE4147D2E = 0x10,
    }
}
