// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0xB8A067E1)]
    public enum Enum_B8A067E1 : uint {
        [STUField(0x31321DE8)]
        x31321DE8 = 0x0,

        [STUField(0x6CDFA6EA)]
        x6CDFA6EA = 0x1,

        [STUField(0x6EA43F9D)]
        x6EA43F9D = 0x2,

        [STUField(0x02EF0261)]
        x02EF0261 = 0x3,

        [STUField(0xF16B3418)]
        xF16B3418 = 0x4,
    }
}
