// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x1FF31299)]
    public enum Enum_1FF31299 : uint {
        [STUField(0xED936589)]
        xED936589 = 0x0,

        [STUField(0xA634D7B9)]
        xA634D7B9 = 0x1,
    }
}
