// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0xCE6658F5)]
    public enum Enum_CE6658F5 : uint {
        [STUField(0xF58CDBDF)]
        xF58CDBDF = 0x0,

        [STUField(0xA9AB0C1D)]
        xA9AB0C1D = 0x1,
    }
}
