// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0xA0B56219)]
    public enum Enum_A0B56219 : uint {
        [STUField(0x168571B4)]
        x168571B4 = 0x0,

        [STUField(0xB57826EC)]
        xB57826EC = 0x1,

        [STUField(0x2282A206)]
        x2282A206 = 0x2,

        [STUField(0x0F75D255)]
        x0F75D255 = 0x3,

        [STUField(0x973B68A1)]
        x973B68A1 = 0x4,

        [STUField(0x66053BFA)]
        x66053BFA = 0x5,

        [STUField(0xC20AA2B7)]
        xC20AA2B7 = 0x6,

        [STUField(0x662ED8FC)]
        x662ED8FC = 0x7,

        [STUField(0x447C5222)]
        x447C5222 = 0x8,
    }
}
