// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x0DBEB14F)]
    public enum Enum_0DBEB14F : uint {
        [STUField(0xDA14C24A)]
        xDA14C24A = 0x0,

        [STUField(0x31FDC6CF)]
        x31FDC6CF = 0x1,
    }
}
