// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0xB3FCE7D5)]
    public enum Enum_B3FCE7D5 : uint {
        [STUField(0x9D3B5CD3)]
        x9D3B5CD3 = 0x0,

        [STUField(0xEFE5F337)]
        xEFE5F337 = 0x1,

        [STUField(0x8C7FE92A)]
        x8C7FE92A = 0x2,
    }
}
