// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x3BFBC0C2)]
    public enum Enum_3BFBC0C2 : uint {
        [STUField(0x386738FB)]
        x386738FB = 0x14,

        [STUField(0x0C38C9FD)]
        x0C38C9FD = 0x2DFFF,

        [STUField(0x2429AAC2)]
        x2429AAC2 = 0x2DFFE,

        [STUField(0x5CBC640F)]
        x5CBC640F = 0x7FFFF,

        [STUField(0xFDC8F423)]
        xFDC8F423 = 0x7FFFE,
    }
}
