// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x34285FC3)]
    public enum Enum_34285FC3 : uint {
        [STUField(0x059EF14D)]
        x059EF14D = 0x4,
    }
}
