// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x6CBB673B)]
    public enum Enum_6CBB673B : uint {
        [STUField(0xA083C2EF)]
        xA083C2EF = 0x0,

        [STUField(0xB2C401CA)]
        xB2C401CA = 0x1,

        [STUField(0xEDE032FB)]
        xEDE032FB = 0x2,

        [STUField(0x5B2DE07A)]
        x5B2DE07A = 0x3,

        [STUField(0x093910CE)]
        x093910CE = 0x4,

        [STUField(0x6435CDCE)]
        x6435CDCE = 0x5,

        [STUField(0xBFFC2549)]
        xBFFC2549 = 0x6,

        [STUField(0x11918EC7)]
        x11918EC7 = 0x7,
    }
}
