// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x3C51C251)]
    public enum Enum_3C51C251 : uint {
        [STUField(0xCAEFDD6A)]
        xCAEFDD6A = 0x0,

        [STUField(0x9DF2A056)]
        x9DF2A056 = 0x1,

        [STUField(0xA436E5FF)]
        xA436E5FF = 0x2,

        [STUField(0x6E7E3BE3)]
        x6E7E3BE3 = 0x3,

        [STUField(0x8DF78954)]
        x8DF78954 = 0x4,

        [STUField(0x01B76CD3)]
        x01B76CD3 = 0x5,

        [STUField(0x37FFFFC3)]
        x37FFFFC3 = 0x6,
    }
}
