// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x3DEC11A9)]
    public enum Enum_3DEC11A9 : uint {
        [STUField(0x75E92EAA)]
        x75E92EAA = 0x0,

        [STUField(0x14C30976)]
        x14C30976 = 0x1,

        [STUField(0x083D9FC5)]
        x083D9FC5 = 0x2,
    }
}
