// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x42D371BD)]
    public enum Enum_42D371BD : uint {
        [STUField(0x37432366)]
        x37432366 = 0x0,

        [STUField(0x8653E639)]
        x8653E639 = 0x1,

        [STUField(0x20AA4DC5)]
        x20AA4DC5 = 0x2,

        [STUField(0xBF31F440)]
        xBF31F440 = 0x3,

        [STUField(0x05982E71)]
        x05982E71 = 0x4,
    }
}
