// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All

namespace TankLib.STU.Types.Enums {
    [STUEnum(0x4E56D01D, "STUWeaponType")]
    public enum STUWeaponType : uint {
        [STUField(0xE87119C8)]
        xE87119C8 = 0x0,

        [STUField(0xF63DFCBD)]
        xF63DFCBD = 0x1,
    }
}
