name: .NET

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore OverwatchToolchain.sln --verbosity m -r win7-x64
    - name: Build Release
      run: dotnet publish --configuration ReleasePublish -r win7-x64 -o dist/Release
    - name: Build Debug
      run: dotnet publish --configuration DebugPublish -r win7-x64 -o dist/Debug
    - name: Upload Release build
      uses: actions/upload-artifact@v3
      with:
        name: Release
        path: dist/Release
    - name: Upload debug build
      uses: actions/upload-artifact@v3
      with:
        name: Debug
        path: dist/Debug
